### ISSUE TITLE
Search bar is not working

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#1]

**Comment by Vidhanvyrs** [comment]
Hey @HimanshuNarware Maybe i could help with this issue Can you assign it to me

**Comment by HimanshuNarware** [comment]
@Vidhanvyrs  you are assigned

**Comment by Vidhanvyrs** [comment]
hey @HimanshuNarware Can you please elaborate exactly what all changes do you require to be done for the search bar

**Comment by Vidhanvyrs** [comment]
like this is the function that is written in the Navbar.js file 
```
 const [showSideNav, setShowSideNav] = useState(false); // Initialize showSideNav state

  function handleClick(e) {
    e.preventDefault();
    console.log('hello world');
    setShowSideNav(!showSideNav); // Toggle the state when the button is clicked
  }
```

**Comment by HimanshuNarware** [comment]
> like this is the function that is written in the Navbar.js file
> 
> ```
>  const [showSideNav, setShowSideNav] = useState(false); // Initialize showSideNav state
> 
>   function handleClick(e) {
>     e.preventDefault();
>     console.log('hello world');
>     setShowSideNav(!showSideNav); // Toggle the state when the button is clicked
>   }
> ```
> 
> Is this the code that requires the change or its just the styling that is done to the search bar that need to be changed

@Vidhanvyrs Nope this function is for the sidebar, you need to write logic/code for the search functionality

**Comment by HimanshuNarware** [comment]
@Vidhanvyrs  so that users can search tools with the help of the search bar,

**Comment by Vidhanvyrs** [comment]
Got it mate! Gonna start working on it

**Comment by HimanshuNarware** [comment]
> Got it mate! Gonna start working on it

Yep👍👍
