### ISSUE TITLE
[New Tool]: Adding Foundation Tool Frontend Framework 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a Foundation framework which is a css framework which is used to use css class just with a small words .

### Use Case

This will help users to complete their work fast instead of typing the whole class 

### Add ScreenShots

![Screenshot 2024-06-21 094729](https://github.com/HimanshuNarware/Devlabs/assets/118350936/3ad5c150-0296-47df-a0f0-e421a2d6abfa)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 ,  i am assigning this task to you. Kindly complete within 4 days and also add a 30-second demo video with PR. Good Luck!
