### ISSUE TITLE
[Feature Request]: Adding Loading SKeleton 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a loading skeleton which looks awesome which will be shown for 5s just before loading the cards .

### Use Case

This will make website more attractive 

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/118350936/9087b12f-b7ab-49b2-957d-18d26f1ffff3

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 ,  i am assigning this task to you. Kindly complete within a week and also add a 30-second demo video with PR. Good Luck!
