### ISSUE TITLE
Sidebar Navigation Auto-Close and Search Bar missing

### ISSUE THREAD

**Issue by urz-ahmed** [HimanshuNarware/Devlabs#101]
**Describe the bug**
**Sidebar Navigation Auto-Close**: When navigating through the sidebar navigation items, the sidebar does not close automatically after selecting an item. Users expect the sidebar to collapse after clicking on a navigation link for a better user experience.

**Bookmark Page Responsiveness:** The responsiveness of the bookmark page is not correct. It does not adapt properly to various screen sizes, leading to layout issues and a less-than-optimal user experience.
**Missing Search bar in smaller screens:** : Due to missing responsiveness Search bar icon is missing

**Expected behavior**
1. After clicking on a sidebar navigation item, the sidebar should automatically collapse to provide more screen space for the main content.

2. The bookmark page should be responsive, adjusting its layout and elements gracefully to fit different screen sizes and orientations.

**Screenshots**
![Screenshot 2023-10-21 092900](https://github.com/HimanshuNarware/Devlabs/assets/106316083/5f0533ce-65d7-44cd-b125-f07edfd2b68d) 

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Hacktoberfest/Hacksquad*

**Comment by sudhz** [comment]
Hi @urz-ahmed, I would like to work on this under hacktoberfest. Could you please assign me to this?

**Comment by urz-ahmed** [comment]
No actually I would like to work on this and I have done most of the part already.@HimanshuNarware Assign me this issue under hacktobest tag.

**Comment by HimanshuNarware** [comment]
@urz-ahmed  Assigned you

**Comment by HimanshuNarware** [comment]
@sudhz  you can work on implementing search bar functionality on the website, where user can find tools by searching their name

**Comment by sudhz** [comment]
okay, sure

**Comment by urz-ahmed** [comment]
Hi there 👋, I have fixed the problem of search bar. Now working fine. I have raised - PR named working search function please merge it.
