### ISSUE TITLE
[New Tool]: Adding leetcode and codechef in coding platforms

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

They are platforms where you can practice with a programming language of your choice

### Use Case

It will be helpful for problem practice 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ayush-848 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!

**Comment by ayush-848** [comment]
@panwar8279 please check the PR #783
