### ISSUE TITLE
[New Tool]: Adding SASS as a frontend tool

### ISSUE THREAD

**Issue by poseidonsanket** [HimanshuNarware/Devlabs#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Sass is the most mature, stable, and powerful professional grade CSS extension language in the world.

### Use Case

Sass is completely compatible with all versions of CSS

### Add ScreenShots

![Screenshot (98)](https://github.com/HimanshuNarware/Devlabs/assets/112609618/feab4d89-36bc-4bba-bf59-ecc800952123)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by poseidonsanket** [comment]
@panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Hi @poseidonsanket ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
