### ISSUE TITLE
[Feature Request]: Enhance search bar

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to modify the existing searchbar and redesign it to be more user friendly and attractive. 

### Use Case

When the website UI is good but a search bar stands as a black mark noone would like it, so by enhancing the search bar the whole website UI can be improved as search bar is one of the most imp feature in the website.

### Benefits

By enhancing the Search bar, the website UI can be improved.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
