### ISSUE TITLE
[Feature Request]: Update Remote Job Section

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the remote job section is empty
![Screenshot 2024-06-22 133338](https://github.com/HimanshuNarware/Devlabs/assets/125206920/b981aae9-b66e-4b41-9b9d-d2a5d9ed8a1a)
I  will add multiple remote job tools and design it similar to other sections to match the theme like in the below image of coding platforms.
![Screenshot 2024-06-22 133356](https://github.com/HimanshuNarware/Devlabs/assets/125206920/3a6db5a0-2274-46eb-9b92-329347ff53e3)

### Use Case

It helps the user find tools related to remote jobs.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Chandu6702** [comment]
@panwar8279 please assign this to me

**Comment by panwar8279** [comment]
hi @Chandu6702 ,  I am assigning this task to you. Kindly complete this work within 2 days And also add 30sec demo video. Good Luck!
