### ISSUE TITLE
[Bug]: Issue in review form

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text does not appear in the review form input.
![Screenshot 2024-06-22 133511](https://github.com/HimanshuNarware/Devlabs/assets/125206920/cf605940-8fc8-4921-9996-4db3d0d6f6ae)
![Screenshot 2024-06-22 134839](https://github.com/HimanshuNarware/Devlabs/assets/125206920/13a3e9b9-9c81-49dc-b93f-f36b805c5be6)

### Expected behavior

The Data entered must be visible to the user 

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Chandu6702** [comment]
@panwar8279 please assign this to me

**Comment by panwar8279** [comment]
hi @Chandu6702 , I am assigning this task to you. Kindly complete this work within 2 days And also add 30sec demo video. Good Luck!
