### ISSUE TITLE
[BUG}: Navbar btn not working in Mobile/Tablet Mode

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Navbar Hamburger does not respond when clicked.

### Expected behavior

After clicking the Navbar Hamburger, the navbar should become visible on the screen.appear

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/105718863/1eb6b1ea-be88-490b-a6f9-be7141b2b6ac

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
