### ISSUE TITLE
[Bug]: Scroll-To-Btn hiding in footer

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The scroll to top button is hiding behind the footer.the 

### Expected behavior

The scroll to top button should be visible above the footer.the 

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/105718863/7b557cc9-f1be-4223-8995-9f46ecad0bd5
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/05811e2e-f8db-42aa-8628-30a55d995af1)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 ,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
