### ISSUE TITLE
[New Tool]: Add Infosys springboard 

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Infosys Springboard is a digital learning platform offering a wide range of courses and resources to help individuals upskill and enhance their career prospects. It provides access to high-quality educational content and certifications across various domains, fostering continuous learning and development.

### Use Case

Infosys Springboard is a digital learning platform offering a wide range of courses and resources to help individuals upskill and enhance their career prospects. It provides access to high-quality educational content and certifications across various domains, fostering continuous learning and development.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
