### ISSUE TITLE
[New Tool]: Add Coderbyte 

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Coderbyte is a popular platform for coding challenges and algorithm practice, designed to help developers improve their programming skills. It offers a variety of challenges, tutorials, and resources for developers of all levels to enhance their problem-solving abilities.

### Use Case

Coderbyte is a popular platform for coding challenges and algorithm practice, designed to help developers improve their programming skills. It offers a variety of challenges, tutorials, and resources for developers of all levels to enhance their problem-solving abilities.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
