### ISSUE TITLE
[Feature Request]:i want to fix the search button to there right position

### ISSUE THREAD

**Issue by kunalmaurya6** [HimanshuNarware/Devlabs#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i have seen in you pager search button hide contact link

### Use Case

improve UI of page and increase user conectivity

### Add ScreenShots

![Screenshot 2024-06-23 194412](https://github.com/HimanshuNarware/Devlabs/assets/109097899/e6d2fd74-5131-45d4-a361-5f46fa37ced2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
hi @kunalmaurya6 , i am assigning this task to you. Kindly complete within 2 days and Also add 30sec demo video. Good Luck!

**Comment by kunalmaurya6** [comment]
### is this position is relevent plz responce of search box


![image](https://github.com/HimanshuNarware/Devlabs/assets/109097899/7faa9949-c334-4ab0-ab9f-416c25db02a4)
