### ISSUE TITLE
[Feature Request]: i want to add tooltip

### ISSUE THREAD

**Issue by kunalmaurya6** [HimanshuNarware/Devlabs#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Hi @HimanshuNarware  i want to add tool tip in chat boat icon and theme chang icon

![image](https://github.com/HimanshuNarware/Devlabs/assets/109097899/04b42e75-6d90-47a4-a604-bf6f73896016)

### Use Case

inhence UI and user experience. 
work flow of tooltip is when we hover on these button it will suggest us what is the use of this button

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kunalmaurya6 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
