### ISSUE TITLE
[Feature Request]: i want to fix scroll top button

### ISSUE THREAD

**Issue by kunalmaurya6** [HimanshuNarware/Devlabs#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @HimanshuNarware 
i want to fix an issue of scroll top button which is disapear when footer body arrises

https://github.com/HimanshuNarware/Devlabs/assets/109097899/6f212850-513c-4286-adc6-85661cb93fcb

### Use Case

it help user to go on top while he is at bottom

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kunalmaurya6 , I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
