### ISSUE TITLE
[New Tool]: code avengers

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Code Avengers is an interactive platform that teaches coding through engaging challenges and tutorials. It caters to beginners and advanced learners alike, focusing on practical coding skills and problem-solving abilities.

### Use Case

Code Avengers is an interactive platform that teaches coding through engaging challenges and tutorials. It caters to beginners and advanced learners alike, focusing on practical coding skills and problem-solving abilities.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
