### ISSUE TITLE
[New Tool]: Linkedin learning

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

LinkedIn Learning, formerly known as Lynda.com, provides a vast library of online courses covering business, technology, and creative skills. It offers personalized learning paths and certificates, tailored to enhance professional development and career growth.

### Use Case

LinkedIn Learning, formerly known as Lynda.com, provides a vast library of online courses covering business, technology, and creative skills. It offers personalized learning paths and certificates, tailored to enhance professional development and career growth.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  I am assigning this task to you. Kindly complete within 3 days and also add demo video. Good luck!
