### ISSUE TITLE
[New Tool]: Google colab

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A cloud-based platform for running Python code, particularly suited for machine learning and deep learning.

### Use Case

A cloud-based platform for running Python code, particularly suited for machine learning and deep learning.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  I am assigning this task to you. Kindly complete within 4 days and also add demo video. Good luck!
