### ISSUE TITLE
[New Tool]: Add Bollyflix

### ISSUE THREAD

**Issue by jinx-vi-0** [HimanshuNarware/Devlabs#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Bollyflix is a popular website to download movies, webshows, anime and much more. Bollyflix provides users to download content in different quality with multi audio support.

### Use Case

Bollyflix is a popular website to download movies, webshows, anime and much more. Bollyflix provides users to download content in different quality with multi audio support.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jinx-vi-0 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!

**Comment by jinx-vi-0** [comment]
hey @panwar8279 , I have created a pr, please check it.
