### ISSUE TITLE
[New Tool]: Add Binged

### ISSUE THREAD

**Issue by jinx-vi-0** [HimanshuNarware/Devlabs#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Binged is a popular website to stream movies, webshows, anime and much more. Binged provides users to stream content in different quality with multi audio support. Users can watch their favourite shows and movies live instead of worring to download it.

### Use Case

Binged is a popular website to stream movies, webshows, anime and much more. Binged provides users to stream content in different quality with multi audio support. Users can watch their favourite shows and movies live instead of worring to download it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jinx-vi-0 ,  I am assigning this task to you. Kindly complete within 3 days and also add demo video. Good luck!

**Comment by jinx-vi-0** [comment]
hey @panwar8279 , I have created a pr, please check it.
