### ISSUE TITLE
[New Tool]: Add 1Flix

### ISSUE THREAD

**Issue by jinx-vi-0** [HimanshuNarware/Devlabs#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

1Flix is one of the most visited sites for free movie streaming. Unlike other free movie sites, 1Flix does not only provide top-notch content and features but also complete safety. This free site allows users to watch and download tens of thousands of movies and TV shows in HD quality with no ads. 1Flix owns one of the biggest content libraries and premium features that normally cost you ten bucks a month elsewhere.

### Use Case

You can find here almost every title of interest, be it the latest release, a classic, a worldwide famous blockbuster or an underrated indie. Apart from the impressive collection of movies and TV shows, what helps 1Flix stand out from the crowd as one of the best free movie sites is its features. 1Flix is the site you should head to for an enhanced watching experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jinx-vi-0 ,  I am assigning this task to you. Kindly complete within 4 days and also add demo video. Good luck!

**Comment by jinx-vi-0** [comment]
hey @panwar8279 , I have created a pr, please check it.
