### ISSUE TITLE
We can Design Logo and Website Color 

### ISSUE THREAD

**Issue by Mohiit70** [HimanshuNarware/Devlabs#11]
The current logo and color theme of our website are not visually appealing and do not align with the quality we want to represent for our event. It's crucial to update these elements to provide a more captivating and professional user experience.

**Comment by Mohiit70** [comment]
> The current logo and color theme of our website are not visually appealing and do not align with the quality we want to represent for our event. It's crucial to update these elements to provide a more captivating and professional user experience.

I'm happy to work on this issue! @HimanshuNarware

**Comment by HimanshuNarware** [comment]
@Mohiit70  Assigned you

**Comment by sakshipatil4403** [comment]
@HimanshuNarware pls assign me this issue
