### ISSUE TITLE
[New Tool]: HiAnime

### ISSUE THREAD

**Issue by jinx-vi-0** [HimanshuNarware/Devlabs#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

HiAnime.to is a very popular free site to watch anime and you can even download subbed or dubbed anime.

### Use Case

HiAnime.to is a very popular free site to watch anime and you can even download subbed or dubbed anime.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jinx-vi-0 ,  I am assigning this task to you. Kindly complete within 3 days and also add demo video. Good luck!

**Comment by jinx-vi-0** [comment]
hey @panwar8279 , I have created a pr, please check it.
