### ISSUE TITLE
[New Tool]: Add MangaReader

### ISSUE THREAD

**Issue by jinx-vi-0** [HimanshuNarware/Devlabs#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

MangaReader is an ad-free manga site that allows users to read and download thousands of manga for free. MangaReader has one of the largest databases of manga covering all genres and subgenres with numerous topics and themes. Apart from an extensive content library, MangaReader also provides free users with premium quality features that might be costly elsewhere.

### Use Case

MangaReader is an ad-free manga site that allows users to read and download thousands of manga for free. MangaReader has one of the largest databases of manga covering all genres and subgenres with numerous topics and themes. Apart from an extensive content library, MangaReader also provides free users with premium quality features that might be costly elsewhere.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jinx-vi-0 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!

**Comment by jinx-vi-0** [comment]
hey @panwar8279 , I have created a pr, please check it.
