### ISSUE TITLE
[Feature Request]:  Add Movies and Series page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@HimanshuNarware 
@panwar8279 

we can add `/movies-and-series` route 

### Use Case

help to learn about `Devlabs`

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/91ac4642-cbb7-4530-844f-8da74ac22163)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I am assigning this task to you. Kindly complete within 3 days and also add 30 sec demo video. Good luck!

**Comment by dhruv8433** [comment]
Thank you @panwar8279
