### ISSUE TITLE
[Feature Request]:  Add Extension page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@HimanshuNarware 
@panwar8279 

we can add new route `/extension` for 'Devlabs'

### Use Case

it help to learn particular  `Extension`

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/461aa0a7-8101-4aae-ad93-c764b60e8c1a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I am assigning this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!

**Comment by dhruv8433** [comment]
Thank you @panwar8279
