### ISSUE TITLE
[Bug]:  Model doesn't close when we click outside

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@HimanshuNarware 
@panwar8279 

check this out

### Expected behavior

the modul should be closed when we click outside

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/01221c69-639b-435e-94de-f4b0dbd5f1ff)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I am assigning this task to you. Kindly complete within 3 days and also add 30 sec demo video. Good luck!
