### ISSUE TITLE
[Feature Request]: Adding a Search Bar the Category Sorting

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can add a Search bar above category sorting UI, So it will be more user-friendly.

### Use Case

This will help user to search and sort both at the same time.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
