### ISSUE TITLE
[New Tool]: A video Downloader Extension to download any online video

### ISSUE THREAD

**Issue by ThisIsSahaj** [HimanshuNarware/Devlabs#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Download videos from the web. Easy, smart, no tracking.

### Use Case

- Video Download: 1000+ websites supported (Dash, HLS, MPD, …)
- Live Stream Support: Enjoy offline viewing of live streams, freeing you from real-time constraints.
- HD Download and Conversion: Download videos in high-definition and convert them to your preferred formats (MP4, MKV, WebM, …) for optimal viewing pleasure
- Audio Download: Extract audio from videos, converting them into MP3s or podcasts for easy listening.

### Benefits

Can download videos even if the download is restricted for the website

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ThisIsSahaj ,  I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
