### ISSUE TITLE
A new Open Source Software Page

### ISSUE THREAD

**Issue by vihar-s1** [HimanshuNarware/Devlabs#112]
### **Problem Statement**
A page where various developers can post their Open Source Software open for public contribution. Most of the times, it is difficult for people to find repositories that are open for contribution and is active, as in the owners actively accept and merge the PRs. It would be very helpful to have a platform where the only listed repositories are available to OSS and active.

### **Proposed Solution**
- A page with design similar to contributors page and tools page. Each card will have project title, some tags that owner thinks suitable, and the languages used in the project. A JSON file similar to product.json for tools can be created in the `db` folder to save the OSS projects.
- The page would look like a combination of these two...

| ![image](https://github.com/HimanshuNarware/Devlabs/assets/96971096/95ac1369-a822-4731-b046-0a8e5e4c0f51) | ![image](https://github.com/HimanshuNarware/Devlabs/assets/96971096/91a2c144-7d67-4bf1-9918-90d55a31d7ad) |
| ----|----|
| Standard Devlabs format of displaying cards | A list of various projects available for OSS |

> Each card in the Devlabs display format would be an individual project with some tags, languages, and project link.

### Checklist

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Hacktoberfest*
- [x] Working under Slop 3.0 *

**Comment by vihar-s1** [comment]
@HimanshuNarware I would like to work on this idea I had about a new feature to for the website.

**Comment by HimanshuNarware** [comment]
@vihar-s1  Nice, I like you Idea

**Comment by vihar-s1** [comment]
Thankyou 😀
