### ISSUE TITLE
[New Tool]:  MLWBD 

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

MLWBD is a website known for offering a wide variety of movies and TV shows for free download and streaming. The content available on MLWBD typically includes films from various industries, including Hollywood, Bollywood, and regional cinema. 

### Use Case

If you want to watch any netflex , amazon prime or any other OTT file for free this website is the way to go.

### Benefits

This website helps users to easily download movies , webseries and more with user preferred quality.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I am assigning this task to you. Kindly complete within 2 days and also add demo video. Good luck!
