### ISSUE TITLE
[Feature Request]:  Adding BEM Naming Convention 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

BEM naming convention is a type of naming convention for the classes used in the html tags . 
With the help of these conventions developers can easily understand the classes .
It will help in increase the productivity

### Use Case

This will help to easily understand the classes used for 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 ,  I am assigning this task to you. Kindly complete within 3 days and also add 30 sec demo video. Good luck!
