### ISSUE TITLE
Scroll bar needed in sidebar

### ISSUE THREAD

**Issue by Devrishi-Dutta** [HimanshuNarware/Devlabs#114]
**Describe the bug**
All menu options are not visible in the sidebar (depending on screen size). Thus a vertical scrollbar is needed .

**Expected behavior**
Users will be able to see all options by scrolling down

**Screenshots**
<img width="371" alt="Screenshot 2023-10-24 113224" src="https://github.com/HimanshuNarware/Devlabs/assets/97834009/23173813-2c29-42a8-9e90-786b90451e22">

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Hacktomberfest/Hacksquad*
- [x] Working under Slop 3.0 *

**Comment by Devrishi-Dutta** [comment]
@HimanshuNarware plz assign me this issue if it is applicable.

**Comment by HimanshuNarware** [comment]
someone already did this
