### ISSUE TITLE
NOT GOOD hero section for mobile screen overlapping of objects

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It should be proper in size to give better user experience

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/23f175dd-da88-4083-a712-4e82b8be0b5b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia ,  I am assigning this task to you. Kindly complete within 3 days and also add 30 sec demo video. Good luck!
