### ISSUE TITLE
[New Tool]: Adding shadcn/ui tool

### ISSUE THREAD

**Issue by poseidonsanket** [HimanshuNarware/Devlabs#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Component Library

### Use Case

Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/112609618/cfae7dba-39a5-46d6-bd8d-c9588e1e8fb4)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by poseidonsanket** [comment]
@panwar8279 please assign me this issue under gssoc24

**Comment by panwar8279** [comment]
Hi @poseidonsanket ,  I am assigning this task to you. Kindly complete within 3 days and also add demo video. Good luck!
