### ISSUE TITLE
[New Tool]: Adding Supabase tool

### ISSUE THREAD

**Issue by poseidonsanket** [HimanshuNarware/Devlabs#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Supabase is an open source Firebase alternative.

### Use Case

Start your project with a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, Storage, and Vector embeddings.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/112609618/6366ffce-84e7-480d-9377-b41d59e13620)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by poseidonsanket** [comment]
@panwar8279 can you please assign me this issue

**Comment by panwar8279** [comment]
Hi @poseidonsanket ,  I am assigning this task to you. Kindly complete within 3 days and also add demo video. Good luck!
