### ISSUE TITLE
[New Tool]: Adding Gitpod

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Gitpod is a cloud development environment for teams to efficiently and securely develop software. Improve your team's developer experience by coding in a CDE."

### Use Case

Gitpod is a cloud development environment for teams to efficiently and securely develop software. Improve your team's developer experience by coding in a CDE."

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ayush-848 ,  I am assigning this task to you. Kindly complete within 3 days and also add demo video. Good luck!
