### ISSUE TITLE
[Feature Request]:  NavItems Missing in Responsive burger menu

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

check this out,

### Use Case

Navbar items missing in responsive menu

### Benefits

they don't have rate us and other stuff in responsive devices

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/a70216dc-555b-4083-955a-88298180d537)

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/47ed4457-6b73-4020-adf8-fbf3007812de)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
