### ISSUE TITLE
[Feature Request]:  Display Empty state if not found

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

check this out,

### Use Case

if user try to find particular item by search and not found than display empty state of not found

### Benefits

it enhance the user experience

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/3ed53336-cf4d-40d4-8254-7bd1118a36df)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  , I am assigning this task to you. Kindly complete within 3 days and also add 30 sec demo video. Good luck!
