### ISSUE TITLE
[New Tool]: Add runaway tool

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

It is an accessible platform for artists and developers to explore and experiment with various generative AI models.

### Use Case

It is used to explore and experiment with various generative AI models

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM  , I am assigning this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
