### ISSUE TITLE
[New Tool]: Add stability AI tool

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Writesonic is an AI-powered content automation platform where you can fill in your inputs to generate unlimited content and save time & effort in the process.

### Use Case

It is used for content automation using AI.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM  , I am assigning this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!

**Comment by chaanakyaaM** [comment]
sure

**Comment by chaanakyaaM** [comment]
a small doubt, should i add the tool in products.json file?

**Comment by chaanakyaaM** [comment]
a small doubt, should i add the tools in product.json file??
