### ISSUE TITLE
[New Tool]: Add perplexity AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Perplexity is a free AI-powered answer engine that provides accurate, trusted, and real-time answers to any question.

### Use Case

It helps users search naturally for information.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM  , I am assigning this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
