### ISSUE TITLE
Add find logic for the sidebar 

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#12]
#Description
Add find the logic for the item present in the website.  use sidebar content

#screenshot
![imgae](https://github.com/HimanshuNarware/Devlabs/assets/83147410/47baf6d2-afde-4368-a252-505232703a96)

**Comment by Deka-KEAN** [comment]
Hi @HimanshuNarware the logic for sidebar is written in Navbar.js
Also Sidebar is opening on clicking Search button

![image](https://github.com/HimanshuNarware/Devlabs/assets/64767881/12fc3f9c-1615-4a92-8598-30c1303f1e65)
![image](https://github.com/HimanshuNarware/Devlabs/assets/64767881/c72fbc0f-7ae6-4d28-8b14-3fa63cddc9c6)

**Comment by HimanshuNarware** [comment]
@Deka-KEAN Assigned you
