### ISSUE TITLE
[Bug]:  Heading of contact us page and ethical hacking page  is hiding with navbar 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#1203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The heading of both the pages is overlapping with the heading i want to fix that 

### Expected behavior

The heading my not be overlap with the navbar and must comes below the Navbar 

### Add ScreenShots

![Screenshot 2024-06-29 194321](https://github.com/HimanshuNarware/Devlabs/assets/118350936/9b239c48-36ce-4b79-b98c-fe77affc2bf8)
![Screenshot 2024-06-29 194230](https://github.com/HimanshuNarware/Devlabs/assets/118350936/ae4a029a-a02e-468f-9aa6-835f7e3548f2)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211, I am assigning this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
