### ISSUE TITLE
[Bug]: No way to close the Rate Our Website window.

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no way to close the Rate Our Website window.It can be closed only by reloading the website.

### Expected behavior

I can make changes by adding a cross icon which on click closes this window.

### Add ScreenShots

![Screenshot (560)](https://github.com/HimanshuNarware/Devlabs/assets/143121854/16e305ae-8b33-4cda-9e8f-536567ed58b4)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Someone already working on it.
