### ISSUE TITLE
[Bug]: text not visible

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As the background color is too dark and the button on hover for about section makes it disappear also the rate us page emoji is not visible in dark mode 

### Expected behavior

It should be visible

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/142779809/eab2b66e-8d71-4287-953a-6422dc5c37bc

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck !
