### ISSUE TITLE
[New Tool]: Want to Add Material Ui In Frontend Tools

### ISSUE THREAD

**Issue by nishant0708** [HimanshuNarware/Devlabs#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

React components for faster and easier web development. Build your own design system, or start with Material Design.

### Use Case

It will save user time and he will not have to look about this tool somewhere else

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/101548649/7bc0619f-20c6-40c0-8d9d-05a7dbbfc422)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @nishant0708 @panwar8279 this tool already exist in our database
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/11b32358-346a-4234-899d-9419fe302584)

**Comment by nishant0708** [comment]
Oo sorry for that I will close this issue thanks
