### ISSUE TITLE
[New Tool]: Add Listly - Web Scraping

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Listly is a user-friendly web scraping tool designed to help you extract data from websites efficiently.

### Use Case

1. Recruiters: Searching for job candidates.
2. Sales Representatives: Conducting prospecting workflows.
3. Marketers: Collecting product and pricing information from eCommerce sites.
4. Sports Statisticians: Gathering data for game outcome predictions.
5. Real Estate Agents: Tracking property prices and listings.
6. SEO Experts: Tracking search engine results.
7. PR Agents: Monitoring brand reputation.

### Benefits

1. Ease of Use: Listly does not require any coding skills. You can scrape data with just a few clicks.
2. Data Export: Export scraped data to Excel, CSV, JSON, or integrate with Google Sheets.
3. Automation: Automate tasks like mouse clicks, scrolling, and saving data.
4. Advanced Scraping: Extract data from iFrames, hyperlinks, and more.
5. Scheduling & Notifications: Schedule daily extractions and receive email notifications.
6. Customization: Use custom proxy servers and adjust scraping speed.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AsmitaMishra24** [comment]
@panwar8279, please assign me this issue

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24,  I am assigning this task to you. Kindly complete this Task within 2 days and also add 30sec demo video. Good Luck!
