### ISSUE TITLE
[New Tool]: Add lucid chart

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Lucid chart is a web based diagramming application that allows users to create visual diagrams.

### Use Case

This helps users to visually solve complex problems by creating the architecture diagrams , flowcharts etc.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/be7014bd-908a-40b7-a4ab-7c213c06fcba)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I am assigning this task to you. Kindly complete this task within 3 days and also add 30 sec demo video. Good Luck!
