### ISSUE TITLE
[New Tool]: Add Sublime text(code editor)

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Sublime Text is a sophisticated cross-platform text editor for code, markup and prose. It offers line-by-line staging, commit editing and unmatched performance.

### Use Case

Code editors are indispensable tools for developers. They provide a number of useful features that allow programmers to write code faster and easier, such as syntax highlighting, automatic indentation, error-checking, and code snippets.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/bcf2e918-bdbf-4271-92d5-38c9d4437d28)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@chaanakyaaM , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
