### ISSUE TITLE
[New Tool]: Adding the TYPESCRIPT tool in Frontend Framework

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

TypeScript code converts to JavaScript, which runs anywhere JavaScript runs: In a browser, on Node.js or Deno and in your apps.
It is most widely used for developing the dynamic web applications.

### Use Case

TypeScript understands JavaScript and uses type inference to give you great tooling without additional code.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/142833275/844d54e9-e284-4a4d-a316-64b2a99da50c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I am assigning this task to you. Kindly complete this task within 3second days and also add 30 sec demo video. Good Luck!
