### ISSUE TITLE
[New Tool]:  SQL Server

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Microsoft SQL Server is a relational database management system. As a database server that stores and retrieves data as requested by other software applications on the same computer or a remote computer using the client-server model. Microsoft provides APIs to access SQL Server over the internet as a web service.

### Use Case

Structured query language (SQL) is a programming language for storing and processing information in a relational database.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/142833275/4fe725d0-468c-4ace-ad71-cef8d6090107)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 can you assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
