### ISSUE TITLE
[Feature Request]:  Add `UI` Page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

we can add `ui` page
when user click on `ui design` they will redirected to `/ui` route

### Use Case

it will help user to find particular ui

### Benefits

improve user experience

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/176a1044-f6f3-48fa-a4be-11ed135e2f91)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!

**Comment by dhruv8433** [comment]
Thank you @panwar8279 :)
