### ISSUE TITLE
[Feature Request]:  Add Toast Message when user submit review

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

we can add toast message when user submit review

### Use Case

so user can understand that their review has been submitted

### Benefits

help in improve user experience

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/148b2f70-4fb6-4af5-bed1-10b292fd69c1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
