### ISSUE TITLE
[Bug]: Scroll to top button got hide in footer

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,
scroll to top button got hide in footer

### Expected behavior

it should be visible

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/27fdb5d1-aebb-4a75-8ed7-43162dcbd216)

in footer that button got hide

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/8e349289-8bb8-42da-b610-13de64057ec2)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Completed
