### ISSUE TITLE
Many Cards Image Not Showing

### ISSUE THREAD

**Issue by Mayank77maruti** [HimanshuNarware/Devlabs#128]
**Describe the bug**
Images of many cards are not visible on the website. Images those are the previews of the links mentioned were not showing instead a text was showing up.

**Screenshots**
![issuegithub2](https://github.com/HimanshuNarware/Devlabs/assets/125661248/6a78abad-68bd-48bc-981c-3256afbb75fb)

Example  Fill x { [x] }  into  bracket

- [1] I have checked the existing issues *
- [1] I have read the Contributing Guidelines *
- [1] I have starred the repository *
- [1] Working under Hacktomberfest/Hacksquad*
- [ ] Working under Slop 3.0 *

Sir I would like to Fix the Images Of the Cards , Please assign this task to me.

**Comment by HimanshuNarware** [comment]
@Mayank77maruti Assigned you
