### ISSUE TITLE
[New Tool]: Add Animetsu

### ISSUE THREAD

**Issue by jinx-vi-0** [HimanshuNarware/Devlabs#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Animetsu is a free Anime watching platform.

### Use Case

It provides a variety of animes both in sub and dub format.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jinx-vi-0 ,  I am assigning this task to you. Kindly complete this task within 3 days and also add 30sec demo video. Good Luck!

**Comment by jinx-vi-0** [comment]
hey @panwar8279, I have created a pr. Please check it.
