### ISSUE TITLE
Pagination Number Shows Negative Number When Clicked Previous After Page Number 1

### ISSUE THREAD

**Issue by Mayank77maruti** [HimanshuNarware/Devlabs#129]
Video Describing The Bug:

https://github.com/HimanshuNarware/Devlabs/assets/125661248/7f7e4b95-45e6-4ce3-a1bf-1caa2c52314e

Example  Fill x { [x] }  into  bracket

- [1] I have checked the existing issues *
- [1] I have read the Contributing Guidelines *
- [1] I have starred the repository *
- [1] Working under Hacktomberfest/Hacksquad*
- [1] Working under Slop 3.0 *
- 
Sir , please assign this task to me .

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  you also working   under slop 3.0

**Comment by Mayank77maruti** [comment]
No Sir I am not working under slop 3.0 , by mistake i checked it.

**Comment by Mayank77maruti** [comment]
Sir please do assign this task to me

**Comment by davidkrupa** [comment]
@Mayank77maruti please make sure you are working with the latest version of the code. I made a separate component for pagination and it is already merged. It can be found in src/Component/Pagination.js.

**Comment by Mayank77maruti** [comment]
Sir Please assign this task to me.

**Comment by Mayank77maruti** [comment]
Sir , please assign this task to me .

**Comment by Mayank77maruti** [comment]
Sir please assign this task to me , i am eager to complete this task
