### ISSUE TITLE
[Bug]: Update prouct.json 

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#1314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are many duplicate tools to remove

### Expected behavior

There should be no duplicate tools, having issues in implement sorting as it is based on keys, and keys can have unique values only.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@Kiran-pande-30 ,  I am assigning this task to you. Kindly complete this task within 3 days and also add 30sec demo video. Good Luck!
