### ISSUE TITLE
[Feature Request]: change the header effect

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a transition property in your CSS to achieve a smooth hover effect on a header element, such as `transition: all 0.3s ease;`. This will ensure a gradual change in the element's appearance, making the hover effect appear smoother and more visually appealing.

https://github.com/HimanshuNarware/Devlabs/assets/95361125/6b6434ca-c8f3-48b3-9842-fdf05311db6d

make it smooth like in video 

assign this issue to me!

### Use Case

When visitors move their mouse over the header, the color change happens gradually over 0.3 seconds, creating a smooth and pleasant transition.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I am assigning this task to you. Kindly complete this task within 3 days and also add 30sec demo video. Good Luck!
