### ISSUE TITLE
[New Tool]: Adding Gemini

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

An AI tool

### Use Case

An AI tool

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @Unnimaya6122004 @panwar8279 Gemini Tool is already in our database
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/f8bfb548-1a33-4f91-9ce1-0424948c516d)
