### ISSUE TITLE
[New Tool]: HiAnim

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

free anime streaming website which you can watch English Subbed and Dubbed Anime online with No Account and Daily update.

### Use Case

free anime streaming website which you can watch English Subbed and Dubbed Anime online with No Account and Daily update.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @Unnimaya6122004 @panwar8279 HiAnime is already there in database
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/f164aaf8-f814-463e-8bd9-5ce0fbd99419)
