### ISSUE TITLE
NOT responsive at all 

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/d3532c63-3a20-4e3c-821d-4ad328764f18)

### Expected behavior

It should be responsive for all sizes and fit the screen well uniformally

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
