### ISSUE TITLE
[New Tool]: Image color picker

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#1334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/ad392725-3f03-455e-a3f8-79ee724ab7dd)

### Use Case

Used to pick color from image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
