### ISSUE TITLE
[New Tool]: ADD FIGMA Collaboration Tools

### ISSUE THREAD

**Issue by kartikmehta18** [HimanshuNarware/Devlabs#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

figma is a collabrative platform in which we can make ppt in a team or also made graphic designing

### Use Case

colllobrotive platform we can work in team

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/125860170/054cce3f-1f97-4bb7-872c-bb4e1cb37dea)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kartikmehta18 , I am assigning this task to you. Kindly complete within 2 days and also add 30sed demo video. Good luck

**Comment by kartikmehta18** [comment]
https://github.com/HimanshuNarware/Devlabs/pull/1419 plz review
