### ISSUE TITLE
[Bug]: Email validation

### ISSUE THREAD

**Issue by Tanishashrivas** [HimanshuNarware/Devlabs#1346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The email is not validated whether it even exists or not.  Even if u write a@b it is considering it as right.

### Expected behavior

To add email validation so that it will display the user "Please enter a valid email" when they enter a wrong one.

### Add ScreenShots

![Screenshot (315)](https://github.com/HimanshuNarware/Devlabs/assets/114223066/f62628c6-10a8-4c17-8890-dd0efe8227c3)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Tanishashrivas ,  I am assigning this task to you. Kindly complete this within 3 days, and also add a 30-second demo video. Good Luck!
