### ISSUE TITLE
[Bug]: Distorted styling of footer elements

### ISSUE THREAD

**Issue by Tanishashrivas** [HimanshuNarware/Devlabs#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The styling effect of footer elements is distorted. Refer to the video please:

https://github.com/HimanshuNarware/Devlabs/assets/114223066/75d7fd01-3cbd-4b8d-8c30-dee715dc162e

### Expected behavior

To correct the styling of the footer elements

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Tanishashrivas ,  I am assigning this task to you. Kindly complete this within 3 days, and also add a 30-second demo video. Good Luck!
