### ISSUE TITLE
[Bug]: Improper Spacing in footer

### ISSUE THREAD

**Issue by Tanishashrivas** [HimanshuNarware/Devlabs#1348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The spacing between footer logo and content is not sufficient. Please refer to the ss

### Expected behavior

To align and correct the spacing of the logo and elements

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114223066/0c8ef47b-8d69-4265-ae12-25b056dffb61)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Tanishashrivas ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
