### ISSUE TITLE
[New Tool]: Add Research AI

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

1. Research AI - Helps you write marketing content, blog articles, website copies, ecommerce product descriptions and more 10x faster.
2. AI Copywriter, Content Writing Assistant, Marketing Tool.
3. Research AI is AI-powered copywriting software that helps you to write copy that sells. It produces original and plagiarism-free content for your business. All you have to do is choose a tool and describe what you are writing, and our software will do the rest. 
4. With Research AI’s chrome extension, you can write social media posts, brainstorm ideas for your blog articles, personalized emails, and more.
5. Whether you are writing product copies on your Shopify store or blog articles on your WordPress/Medium page, you can generate amazing content without leaving your workspace.

### Use Case

Explore real-world examples of how AI extensions are currently being used in academic research. This includes applications in literature review, data analysis, experiment planning, and more.

### Benefits

1. Time savings
2. Accurate data processing
3. Streamlined workflows.

### Add ScreenShots

![Screenshot 2024-07-05 154531](https://github.com/HimanshuNarware/Devlabs/assets/146121869/c90a6b18-1a28-43c4-b6f4-a5d3a3217360)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  I am assigning this task to you. Kindly complete this within 3days, and also add a 30-second demo video. Good Luck!
