### ISSUE TITLE
[New Tool]: Add Engage AI

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Engage AI is an AI-powered conversational copilot designed to help you quickly and easily attract prospects on LinkedIn. Using advanced machine learning technology, it creates customized comments tailored to your needs, helping you win conversions faster with every added touchpoint. 

### Use Case

1. LinkedIn Engagement:
 LinkedIn Training Service Provider: Engage AI helps LinkedIn power users break the ice and start conversations with prospects who are usually unresponsive to calls, messages, and emails. Craft meaningful comments and content that stand out on LinkedIn.
2. Business Development Manager: Customize tones to sound like you and add the human touch. Stand out with non-generic comments that resonate with your target audience.
3. Business Owner: Increase LinkedIn profile visits from your prospects by being among the first 10 to comment on posts. 
4. Inside Sales:
 Optimize your LinkedIn profile for visibility and reach with keyword-rich content. Grow your thought leadership by sharing insightful posts, articles, and event descriptions.
5. Marketing:
 End writer’s block with Engage AI’s personalized content generation. Share content that makes a lasting impact and evokes genuine responses from potential customers.

### Benefits

1. Improved User Experience: Engage AI will tailor content, making it relevant and engaging for each visitor.
2. Enhanced Customer Support: Chatbots will provide 24/7 assistance, resolving queries promptly.
3. Better SEO Rankings: AI-driven optimization will boost organic traffic.
4. Efficient Content Generation: Automated content creation saves time and ensures quality.
5. Data-Driven Insights: Analyzing user behavior helps us make informed decisions.

### Add ScreenShots

![Screenshot 2024-07-05 155643](https://github.com/HimanshuNarware/Devlabs/assets/146121869/3ef72e4c-4dcd-4c7f-9ade-cd7bdb118fbf)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
