### ISSUE TITLE
[New Tool]: Add Cohere AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 Cohere is focused on generative AI for the enterprise, building technology that businesses can use to deploy chatbots, search engines, copywriting, summarization, and other AI-driven products.

### Use Case

It enables developers to create conversational interfaces with ease, leveraging advanced natural language understanding capabilities.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/b717ee07-3aa7-4b7f-b5de-6c8478c5936b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I am assigning this task to you. Kindly complete this within 3 days, and also add a 30-second demo video. Good Luck!
