### ISSUE TITLE
[New Tool]: Add Deep AI 

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

DeepAI is a user-friendly platform providing state-of-the-art AI tools & APIs that unlock and enhance creativity across industries, widely democratizing access to AI technologies for both developers and non-tech users.

### Use Case

Deep AI offers various features to generate images, videos and characters using text prompts and art styles. 

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/352ddd40-f8e2-460f-bf7f-403cf1770b80)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I am assigning this task to you. Kindly complete this within 4 days, and also add a 30-second demo video. Good Luck!
