### ISSUE TITLE
[New Tool]: Add Anthropic

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Anthropic is an AI safety and research company behind the powerful Claude 3 model family.

### Use Case

It helps developers to deploy AI to business critical use cases, with very low hallucination rates and very high accuracy over long documents.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/fdcaae1a-8a79-42be-b10e-768b00d91eba)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I am assigning this task to you. Kindly complete this within 3 days, and also add a 30-second demo video. Good Luck!
