### ISSUE TITLE
[New Tool]: Add Mistral AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Mistral offers open and portable Gen AI models for multilingual, code generation, maths, and advanced reasoning capabilities.

### Use Case

Mistral AI offers several LLMs ,Each has their own unique set of strengths and abilities.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/7835b51c-2cb6-4202-9206-f04e10938308)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!

**Comment by chaanakyaaM** [comment]
Would you reopen this Issue ?
