### ISSUE TITLE
[New Tool]: Add Fiverr

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Fiverr is an online marketplace for freelance services, which provides freelance Oppurtunites to beginners or professionals in their field.

### Use Case

Fiverr helps students to earn money by levering their skills.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/738bee7f-61de-4336-a83a-16427d2d88e3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
