### ISSUE TITLE
[Feature Request]: Add Codolio in Coding Platforms

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. Auto-Grading & Feedback: Codio’s powerful auto-grading capabilities save valuable time while providing learners with rich, instant feedback.
2. Online IDE: Codio includes a fully-featured instant IDE for all students, complete with debugger tools, dyslexic font capabilities, and more.
3. Learner & Behavior Insights: Unlock previously inaccessible learner behavior insights with actionable, research-based visualizations and learner analytics.
4. Curriculum Authoring: Create your own course content and auto-graded assessments using existing materials or directly within the IDE.
5. Plagiarism Detection: Detect plagiarism and code similarity to identify potential cases of cheating among class members.
6. Codio Coach (AI Learning Assistant): A groundbreaking AI learning assistant designed to help students get unstuck faster without compromising academic integrity.
7. JupyterLab & Notebook Integration: Seamlessly assign JupyterLabs and Notebooks using nbGrader.
8. AI-Ready Infrastructure: Provide a seamless experience for students to explore programming and AI intersections with real-world applications.
9. Virtual Machines: Spin up Linux and Windows virtual machines directly in Codio for specific software use.
10. Code Playback: Review a student’s code playback as it was written, even across multiple files.
11. Collaborative Coding: Assign group and pair programming assignments with collaboration features.
12. LMS Integration: Seamlessly integrate Codio with existing Learning Management Systems.

### Use Case

1. Track
2. analyze
3. share
4. Build your all-in-one coding portfolio with Codolio

### Add ScreenShots

![Screenshot 2024-07-06 005608](https://github.com/HimanshuNarware/Devlabs/assets/146121869/633095cd-8813-4515-80d6-a0154d6a4b08)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
