### ISSUE TITLE
[New Tool]:  Bulk Image Resize 📷

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Bulk image resize tool to help resize multiple images at once...

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/bab0a764-56fb-42c6-880a-c548b1117403)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!

**Comment by Utsavladia** [comment]
Sure 
@panwar8279 
There is some error related to FAQ compoent in the latest branch I have fixed that too...
