### ISSUE TITLE
[Feature Request]: Add Project Gutenberg

### ISSUE THREAD

**Issue by arunimaChintu** [HimanshuNarware/Devlabs#1359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Project Gutenberg offers over 60,000 free eBooks, including classic literature, to download and read online

### Use Case

Project Gutenberg offers over 60,000 free eBooks, including classic literature, to download and read online

### Benefits

Project Gutenberg offers over 60,000 free eBooks, including classic literature, to download and read online

### Add ScreenShots

Project Gutenberg offers over 60,000 free eBooks, including classic literature, to download and read online

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @arunimaChintu , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
