### ISSUE TITLE
[New Tool]: Add a new page Backend Tools on the sidebar.

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I can add a new feature as Backend-tools page on the sidebar.

### Use Case

Its use will be that the users can get to learn about both backend as well as frontend tools from this same platform.

### Benefits

Kindly assign me this issue so that I can start working on it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @meetarora10 ,  I am assigning this task to you. Kindly complete this within 2 days, and also add a 30-second demo video. Good Luck!
