### ISSUE TITLE
Backend For Website

### ISSUE THREAD

**Issue by vihar-s1** [HimanshuNarware/Devlabs#139]
**A backend to decouple frontend and database**
A backend to store the tools and open source project links more freely. Can also be extended to an API.

Checklist

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Hacktomberfest/Hacksquad*
- [x] Working under Slop 3.0 *

**Comment by vihar-s1** [comment]
I would like to work on this.

I would first upload the backend code to the project. Then once the backend is deployed, then I would configure frontend to fetch data.

**Comment by HimanshuNarware** [comment]
@vihar-s1 ok,
