### ISSUE TITLE
[New Tool]: Llama AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Llama AI is the fastest Token Generation Model with Language Processing Units. Able to work on Open Source Models: Gemma-7b-lt, Llama3-70b-8192, Llama3-8b-8192, Mixtral-8x7b-32768.

### Use Case

This is a open source AI model developed by Meta, so students can train it with their own data and use it freely.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/fb6a4f95-6edf-46df-ada7-5892f24c1860)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
