### ISSUE TITLE
[New Tool]:  Add Lovo AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Lovo is a AI model which generates advanced AI voices.

### Use Case

Lovo lets you generate advanced AI voices for any use case.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/3b7e2513-0200-432c-8440-869d42e299c2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
