### ISSUE TITLE
[New Tool]: Goose AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

GooseAI provides a fully managed NLP-as-a-Service, offering various GPT-based models with high customization and speed.

### Use Case

This AI helps to generate text with GPT based model with high speed.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/1f57e144-82af-48ff-bdf4-7729890cbaf5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 3 days and also add 30sec demo video. Good luck!
