### ISSUE TITLE
[New Tool]: Add learn git branching

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Learn Git branching is a website which teaches you git and git commands in visual form like a game.

### Use Case

This website helps you to learn git and git commands very easily.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/77149e65-2dd6-4a69-9968-a7b6d6896b33)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 3 days and also add 30sec demo video. Good luck!
