### ISSUE TITLE
[New Tool]:  add freelancer

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Freelancer is a platform which connects people who  what to do freelancing with people who wanna hire freelancer.

### Use Case

This helps students or professionals to earn money, improve their skills, make connections.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/d0b7c890-f5b1-4c7f-92f2-34f220d2d128)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
