### ISSUE TITLE
[New Tool]:  Add synthesia 

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Synthesia is an Nvidia-backed AI video creation platform.

### Use Case

This ai helps you to create professional videos with AI avatars and voiceovers in 130 languages.

### Benefits

It creates :
- videos
- AI avatars
- voice overs.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/9f51c639-cc24-4a92-934b-e64417c50435)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
