### ISSUE TITLE
Add hover effect on the footer social icons

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#14]

**Comment by akssshh** [comment]
Hey @HimanshuNarware Can you assign this to me?

**Comment by Surajit0573** [comment]
Hi @HimanshuNarware, this is my first PR, so I didn't know about getting assigned before raised any PR. Sorry for the inconvenience!

**Comment by Jagdeep30** [comment]
Can you assign it to me?
