### ISSUE TITLE
[Feature Request]: Add workflows to Check for duplicates in 'product.json' on PR

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This pull request introduces a new GitHub Actions workflow to automatically check for duplicate entries in product.json whenever a pull request (PR) is created or updated. This ensures that no duplicate tools, based on the link property, are merged into the main codebase.

### Use Case

1. Ensures the integrity of product.json by automatically preventing duplicates from being merged.
2. Maintains a clean and unique list of tools.
3. Reduces manual review effort by automating duplicate detection.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
