### ISSUE TITLE
[New Tool]: hackerrank coding platform

### ISSUE THREAD

**Issue by kartikmehta18** [HimanshuNarware/Devlabs#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

HackerRank is the market-leading coding test and interview solution for hiring developers. Start hiring at the pace of innovation!

### Use Case

helps companies develop the strongest tech teams around. We help candidates sharpen their tech skills and pursue job opportunities.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/125860170/eca527b1-4412-49d2-90a2-df1d706e8ace)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kartikmehta18 , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
