### ISSUE TITLE
[New Tool]: Adding Geeksforgeeks in coding platforms

### ISSUE THREAD

**Issue by poseidonsanket** [HimanshuNarware/Devlabs#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Geeksforgeeks is a coding platform.

### Use Case

We can read articles and solve various data structures and algorithms problems on geeksforgeeks 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by poseidonsanket** [comment]
@panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Hi @poseidonsanket , Please start working on it.

**Comment by Kiran-pande-30** [comment]
@panwar8279 @poseidonsanket GeeksForGeeks is already in our database. 
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/3a9d59df-8175-4812-9d83-8a14f31fdaf1)

**Comment by poseidonsanket** [comment]
@Kiran-pande-30 I am adding it in coding platforms page only
