### ISSUE TITLE
[Bug]: Fix UI of review

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#1432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The review page is not properly organized, and the feedback type is not clearly visible 

### Expected behavior

It should be clear and organised

### Add ScreenShots

![Screenshot 2024-07-08 130223](https://github.com/HimanshuNarware/Devlabs/assets/142779809/5f6e6df7-9580-43ae-adcf-a3b70ab525ec)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this issue to you. Kindly complete within 2 days and also add 30sec demo video. Good Luck!
