### ISSUE TITLE
[style]: Add hove animation

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#1434]
It would be great if we add the hover animation of the tools category as all the other buttons have as per the overall theme of the website

![Screenshot 2024-07-08 130139](https://github.com/HimanshuNarware/Devlabs/assets/142779809/f08e316a-1d22-4b53-a321-7b94dac1f5b1)

**Comment by shivrajmuley** [comment]
i would like to work on this project. Please assign it to me.
