### ISSUE TITLE
[Bug]: Bookmark text not visible

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The content inside the bookmark card is not properly visible 

### Expected behavior

It should be clearly visible

### Add ScreenShots

![Screenshot 2024-07-08 125943](https://github.com/HimanshuNarware/Devlabs/assets/142779809/a80e314d-ad6c-4b0b-b16a-6b4450db61a9)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @root-0101 , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
