### ISSUE TITLE
[New Tool]: Adding hackerearth in coding platforms

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#1438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 HackerEarth is an online coding platform used by organizations for technical skill assessments and remote video interviewing.

### Use Case

 HackerEarth is an online coding platform used by organizations for technical skill assessments and remote video interviewing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kartikmehta18** [comment]
bro i already create this issue before you

**Comment by ayush-848** [comment]
> bro i already create this issue before you

Oh, ok
Let me close
