### ISSUE TITLE
[New Tool]: Adding Copilot in extentions

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Trained on GPT-3, GitHub Copilot gives code suggestions, auto-completes code, and can even help write code when you provide a natural language comment.

### Use Case

Trained on GPT-3, GitHub Copilot gives code suggestions, auto-completes code, and can even help write code when you provide a natural language comment.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ayush-848 , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
