### ISSUE TITLE
[Feature Request]: Contact form reload after submit i will reset form and show message after submit form

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/Devlabs#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will show thank you we will connect soon message and reset form after submit.

### Use Case

Better user experince

### Benefits

User interaction 

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/126322584/e832e107-e9ce-4d8b-a082-067588dc4507)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@panwar8279 Please assign me this task !

Thank You !

**Comment by panwar8279** [comment]
Hi @zalabhavy , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
