### ISSUE TITLE
[Bug]: special cursor hide bihind theme button

### ISSUE THREAD

**Issue by kunalmaurya6** [HimanshuNarware/Devlabs#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

special cursor hide bihind theme button.

https://github.com/HimanshuNarware/Devlabs/assets/109097899/c7764c56-993a-4d2d-bbf4-9f4a82699006

### Expected behavior

special cursor show on button while hover on it.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kunalmaurya6 , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
