### ISSUE TITLE
[New Tool]:  Adding the .Net technology for Backend 

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Adding the .Net technology for Backend  is a powerful tool used for backend and to connect with most of the daatabases

### Use Case

Adding the .Net technology for Backend  is a powerful tool used for backend and to connect with most of the daatabases

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign this task ...

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
