### ISSUE TITLE
[New Tool]: Adding the Laravel technology for Backend

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Laravel is a free and open-source PHP-based web framework for building high-end web applications. It was created by Taylor Otwell and intended for the development of web applications 

### Use Case

Laravel is a free and open-source PHP-based web framework for building high-end web applications. It was created by Taylor Otwell and intended for the development of web applications 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
