### ISSUE TITLE
[New Tool]: Adding the Ruby on Rails technology for Backend

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Ruby on Rails is a server-side web application framework written in Ruby under the MIT License. Rails is a model–view–controller framework, providing default structures for a database, a web service, and web pages.

### Use Case

Ruby on Rails is a server-side web application framework written in Ruby under the MIT License. Rails is a model–view–controller framework, providing default structures for a database, a web service, and web pages.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!

**Comment by Maheshwari-Love** [comment]
@panwar8279 please the PR's
