### ISSUE TITLE
[New Tool]: Coding platform

### ISSUE THREAD

**Issue by Tanishashrivas** [HimanshuNarware/Devlabs#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Add coding ninjas platform to the coding platform section

### Use Case

Allows users to solve problems, contests and prepare for interviews

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Tanishashrivas , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
