### ISSUE TITLE
[Bug]: Bookmark page distorted

### ISSUE THREAD

**Issue by Tanishashrivas** [HimanshuNarware/Devlabs#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer of the bookmark page is shifted to the left and the page is distorted

https://github.com/HimanshuNarware/Devlabs/assets/114223066/7bc100d8-9cfc-41e3-84f3-ba25764108cd

### Expected behavior

To fix the alignment of the page and correct the whole page's  ui

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Tanishashrivas , I have assigned this task to you. Kindly complete within 2 days and also add 30sec demo video. Good luck!
