### ISSUE TITLE
[Bug]: Contacts page distorted

### ISSUE THREAD

**Issue by UtkarshBirla28** [HimanshuNarware/Devlabs#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Page distortiion on contacts page

### Expected behavior

They should be properly aligned 

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/96072228/ac1e437d-2073-43f6-aa05-5750aca2be58

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Tanishashrivas** [comment]
@panwar8279 Can you please assign this issue to @UtkarshBirla28
