### ISSUE TITLE
Colour of profile button is not matching with the theme of the project in about us section

### ISSUE THREAD

**Issue by Devrishi-Dutta** [HimanshuNarware/Devlabs#148]
Colour of the profile should be pruple instead of green as in home page.

<img width="944" alt="Screenshot 2023-11-03 191131" src="https://github.com/HimanshuNarware/Devlabs/assets/97834009/beeed73c-a298-42d5-b239-f1ba12f7d819">

**Comment by Devrishi-Dutta** [comment]
@HimanshuNarware assign me this issue if it is valid.

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta  also check the light theme issue with the images

**Comment by Devrishi-Dutta** [comment]
ok

**Comment by Devrishi-Dutta** [comment]
@HimanshuNarware the image issue is a little complicated for me as I cannot override the style for images as->
 .darkmode-layer, .darkmode-toggle {
  z-index: 500;
}
is used and if I remove it then the  entire light mode is getting disturbed.
So can you raise a separate issue for this ?

**Comment by Devrishi-Dutta** [comment]
I can correct the colour of profile button in this issue.

**Comment by HimanshuNarware** [comment]
> I can correct the colour of profile button in this issue.

ok
