### ISSUE TITLE
[New Tool]: Mamba Ui  in Frontend Tool

### ISSUE THREAD

**Issue by kartikmehta18** [HimanshuNarware/Devlabs#1490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Mamba UI is a free, open-source collection of UI components
and templates based on Tailwind CSS.

### Use Case

Mamba UI is a toolkit for developers and designers to make creating interfaces easier. We have some of the most popularly used components to help you get started. Everything is modular and customizable to fit your brand. From blogs to portfolios to online stores, you can quickly create a variety of layouts that look great on any screen.

### Benefits

it is Fully compatible with multiple languages rect ,next,HTML,angular etc

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/125860170/b49d9393-dcb0-4fa9-b6fc-b3bdd0a8cf28)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kartikmehta18 ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

**Comment by kartikmehta18** [comment]
> Hi @kartikmehta18 , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

https://github.com/HimanshuNarware/Devlabs/pull/1647 plz review

**Comment by kartikmehta18** [comment]
https://github.com/HimanshuNarware/Devlabs/pull/2026 @panwar8279  plz review
