### ISSUE TITLE
[New Tool]: ADD Github Co-pilot in Extensions

### ISSUE THREAD

**Issue by kartikmehta18** [HimanshuNarware/Devlabs#1495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

The world’s most widely adopted AI developer tool.Proven to increase developer productivity and accelerate the pace of software development

### Use Case

Proven to increase developer productivity and accelerate the pace of software development
![image](https://github.com/HimanshuNarware/Devlabs/assets/125860170/f2a109a5-43f5-437a-bb79-b84c2956d69c)

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/125860170/ba904162-4156-4af0-8d70-c727e63e880c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Already Exist.
