### ISSUE TITLE
[New Tool]: Add Mobile Simulator - Responsive Testing Tool Extension

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Smartphone and tablet simulator on computer with several models to test mobile responsive websites.

Very realistic desktop smartphone and tablet simulator with multiple devices and resolutions to test your mobile site.

### Use Case

55 devices are available for responsive testing
📱19 recent and old Android & Google smartphone models including the Galaxy S22
📱23 recent and old Apple smartphone models including iPhone 15 (PRO & MAX)
💻 5 tablet models
⌚️ And 8 special devices such as the Apple Watch, a Self-Service Terminal or a Macbook
Some devices are only available in the premium version

Main characteristics
🎬 Very easily create video captures in WEBM, GIF or MP4 format.
📸 It is also possible to take a screenshot of the smartphone in transparent PNG to insert it in an email, presentation slides, etc.
🌚 Night mode available (see screenshots)

🏷 Non-intrusive advertising is displayed in the free version
This ad may be hidden in the premium version

### Add ScreenShots

![Screenshot 2024-07-09 180847](https://github.com/HimanshuNarware/Devlabs/assets/146121869/f181fb5f-56b7-4124-84bd-f437c5a8a9fa)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
