### ISSUE TITLE
Add contributor page on the  website

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#15]

**Comment by Devrishi-Dutta** [comment]
I want to contribute to this issue. Can you give more details about the issue ?

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta  assigned you

**Comment by Devrishi-Dutta** [comment]
Is it ok ?@HimanshuNarware 
<img width="461" alt="Screenshot 2023-10-01 161707" src="https://github.com/HimanshuNarware/Devlabs/assets/97834009/17e1159f-6a97-4fe3-82db-e51d6e0a5510">

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta share video of the change

**Comment by Devrishi-Dutta** [comment]
Uploading React App - Google Chrome 2023-10-02 10-19-06.mp4…

**Comment by Devrishi-Dutta** [comment]
@HimanshuNarware 
https://github.com/HimanshuNarware/Devlabs/assets/97834009/62166057-34d9-47eb-a861-216f50fea3f3

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta  It effecting the search bar

**Comment by Devrishi-Dutta** [comment]
Is it ok now? @HimanshuNarware 




https://github.com/HimanshuNarware/Devlabs/assets/97834009/5cde97c3-2bc8-464b-a654-bae70913cb7c

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta  Add contributor section in About us page, fetch the data of the contributor of the Devlabs from GitHub and show in the about us page

**Comment by Devrishi-Dutta** [comment]
Ok I will try. I haven't done this before so it might take some time.

**Comment by HimanshuNarware** [comment]
> Ok I will try. I haven't done this before so it might take some time.

ok

**Comment by Devrishi-Dutta** [comment]
@HimanshuNarware  can I make a pr now?




https://github.com/HimanshuNarware/Devlabs/assets/97834009/d6501cb0-c14b-419b-9cfb-731382a3f0e7

**Comment by HimanshuNarware** [comment]
![idea](https://github.com/HimanshuNarware/Devlabs/assets/83147410/736a12d1-64ef-44d9-bd9d-6f019819b821)
 
@Devrishi-Dutta  the contributor section look like that

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta if you facing some difficulties will building this you can reach out to me
https://www.linkedin.com/in/himanshunarware/

**Comment by Devrishi-Dutta** [comment]
@HimanshuNarware I used the home page theme. Is it ok?

https://github.com/HimanshuNarware/Devlabs/assets/97834009/1952eaeb-ca04-49e7-b655-457eba0ea910

**Comment by HimanshuNarware** [comment]
@Devrishi-Dutta  nice, now raise a pr
