### ISSUE TITLE
[New Tool]: Add Dropin

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

DropIn is a software that utilizes AI technology to assist with homework.

### Use Case

We get it—the midnight deadlines, the daunting assignments. DropIn, crafted by students who've experienced it all, is ready to ease those late-night study sessions when those struggles hit. Join thousands of students today and find out why we are the #1 study partner.

### Add ScreenShots

![Screenshot 2024-07-09 181815](https://github.com/HimanshuNarware/Devlabs/assets/146121869/6e106a8d-e002-47db-bc4d-154d9ac77b81)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
