### ISSUE TITLE
[Feature Request]: adding actual colour hovering effect on social icons

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

at present when hovering over social icons its remain in same colour . I want to make its actual colour when we hover .

### Use Case

it will looks good to the users .

### Benefits

it will have good visual effect to the user as you can see it is looking good in the demo video i have linked 

### Add ScreenShots

before :  

https://github.com/HimanshuNarware/Devlabs/assets/159682348/365e87d0-ae09-4c84-b819-481ac7500722

Want to make like this : 

https://github.com/HimanshuNarware/Devlabs/assets/159682348/7e696772-7719-45bd-a807-fa52805ba971

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@HimanshuNarware @panwar8279 please assign me this issue under gssoc labels . I am sure users will like this feature in the site .

**Comment by panwar8279** [comment]
Hi @ANKeshri ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

**Comment by ANKeshri** [comment]
> Hi @ANKeshri , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

@panwar8279 sure thank you

**Comment by ANKeshri** [comment]
@panwar8279 someone has done
