### ISSUE TITLE
[Documentation Update]: Add .md files to main readme

### ISSUE THREAD

**Issue by ananyag309** [HimanshuNarware/Devlabs#1511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add and link code of conduct, contributing.md, learn.md to main readme file

### Suggested Change

A clear and informative README can attract more users and collaborators while also helping them understand the project quickly and effectively.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ananyag309 ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
