### ISSUE TITLE
[New Tool]: SpringBoot for the Backend Tools

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

SpringBoot for the Backend Tools
Spring Boot is an open-source Java framework used for programming standalone, production-grade Spring-based applications with minimal effort. 

![image](https://github.com/HimanshuNarware/Devlabs/assets/142833275/bf3c49c4-379d-487e-82dd-043222fdacc7)

### Use Case

Spring Boot is an open-source Java framework used for programming standalone, production-grade Spring-based applications with minimal effort. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
