### ISSUE TITLE
[New Tool]: Adding Apache Server for Backend

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

The Apache HTTP Server is a free and open-source cross-platform web server software, released under the terms of Apache License 2.0. 

### Use Case

It is developed and maintained by a community of developers under the auspices of the Apache Software Foundation

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/142833275/2d9a63c1-06b4-415f-b9f5-993bc251ef1f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

**Comment by Maheshwari-Love** [comment]
@panwar8279 I don't know why i am getting deployment error....how can i handle this...
