### ISSUE TITLE
[New Tool]: Adding Firebase for Backend

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Firebase is a set of backend cloud computing services and application development platforms provided by Google. It hosts databases, services, authentication, and integration for a variety of applications,

### Use Case

Run your app with confidence and deliver the best experience for your users

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/142833275/3fa60fca-cfa0-4264-bcc7-36726c6fb54d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love ,  i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
