### ISSUE TITLE
Add Icons to Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#1521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Footer to make our website to look Attractive 

![IMG_20240710_124243](https://github.com/HimanshuNarware/Devlabs/assets/161804629/1e0f7391-44eb-4fb1-a1c7-ca2777457a7c)

### Use Case

It will Enhance User Experience 
Can you assign me this issue under GSSOC'24 @panwar8279 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@sailaja-adapa , Add 30sec demo video of issue.

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @panwar8279
