### ISSUE TITLE
[Feature Request]: Add new Rate Us page.

### ISSUE THREAD

**Issue by zalabhavy** [HimanshuNarware/Devlabs#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of Rate Us page.

### Use Case

User feedback

### Benefits

Improvement

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@panwar8279 Please assign me this task !

Thank You !

**Comment by panwar8279** [comment]
Hi @zalabhavy , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
