### ISSUE TITLE
Correct name Devlaps to Devlabs

### ISSUE THREAD

**Issue by amanr-dev** [HimanshuNarware/Devlabs#1541]
The project name in the Footer copyright section is **Devlaps** and should be **Devlabs**.

## screenshot:-
![Screenshot 2024-07-10 164115](https://github.com/HimanshuNarware/Devlabs/assets/124811276/77ee4101-a01a-4019-b489-3f779f31ef64)

**Comment by panwar8279** [comment]
Hi @amanr-dev , i have assigned this task to you. Please complete within 2 days and also add a 30-second demo video. Good Luck!
