### ISSUE TITLE
[New Feature]: Add CNCF 

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

CNCF is the open source, vendor-neutral hub of cloud native computing, hosting projects like Kubernetes and Prometheus to make cloud native universal and sustainable.

### Use Case

Companies are realizing that they need to be a software company, even if they are not in the software business. For example, Airbnb is revolutionizing the hospitality industry and more traditional hotels are struggling to compete. Cloud native allows IT and software to move faster. Adopting cloud native technologies and practices enables companies to create software in-house, allows business people to closely partner with IT people, keep up with competitors and deliver better services to their customers. CNCF technologies enable cloud portability without vendor lock-in.

### Add ScreenShots

![Screenshot 2024-07-11 003754](https://github.com/HimanshuNarware/Devlabs/assets/146121869/69200512-c389-4e8e-bf18-62e5f84d0944)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
