### ISSUE TITLE
[Feature Request]: Add MLH Fellowship

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A fully remote, 12-week internship alternative where participants earn a stipend and learn to collaborate on real open source projects with peers and engineers from top companies.

### Use Case

Major League Hacking (MLH) is the official student hackathon league. Each year, we power over 300 weekend-long invention competitions that inspire innovation, cultivate communities and teach computer science skills to more than 500,000 developers around the world. MLH is an engaged and passionate maker community, consisting of the next generation of technology leaders and entrepreneurs.

### Add ScreenShots

![Screenshot 2024-07-11 003828](https://github.com/HimanshuNarware/Devlabs/assets/146121869/9c892423-f700-4b03-a427-7c426c48a52b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
