### ISSUE TITLE
[New Tool]: GfG coading plateform

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

want to add gfg website in coding plateform .

### Use Case

users will know a popular coding plateform geeks for geeks .

### Benefits

users will know a popular coding plateform geeks for geeks .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

**Comment by ANKeshri** [comment]
@panwar8279 someone has added
