### ISSUE TITLE
[New Tool]: coding ninjas coding plateform 

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

want to add a new coding plateform of coding ninjas

### Use Case

user will know a new coding plateform

### Benefits

user will know a new coding plateform

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!

**Comment by ANKeshri** [comment]
@panwar8279 someone has already addes so i am closing this sissue
