### ISSUE TITLE
[Feature Request]: Add KodeKloud Platform

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

KodeKloud’s purpose is to help you build DevOps domain expertise, literacy, and Cloud comprehension simultaneously. Be it Kubernetes, AWS, Azure, or among any of hundreds of applications, we can arm you with the knowledge to grow.

### Use Case

Tailor your DevOps and Cloud skill development with custom learning paths to align your learning to your career goals. With Skills sandboxes, you can learn by doing and hone your growing DevOps and Cloud skills, risk-free, in secure environments. Then take your skills from learned to certified with our practice tests and certification preparations in both DevOps and Cloud fields.

### Add ScreenShots

![Screenshot 2024-07-11 005222](https://github.com/HimanshuNarware/Devlabs/assets/146121869/cd59af97-363b-47fe-bba2-b489f41d992a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
