### ISSUE TITLE
[New Tool]:Codeforces coding plateform 

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

want to add a new coding plateform which is most popular ie codeforces

### Use Case

user will get to knw about and practise in new coding plateform ie cdeforces .

### Benefits

user will get to knw about and practise in new coding plateform ie cdeforces .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
