### ISSUE TITLE
[New Tool]: Adding topcoder in coding platform

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I want to add topcoder which is a coding platform

### Use Case

It will add to the coding platforms so that users get variety of coding platforms
users can give weekly contests on it

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
