### ISSUE TITLE
[New Tool]: Adding hackerearth in coding platforms

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I want to add hackerearth in coding platform

### Use Case

Users can practise coding

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera ,i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
