### ISSUE TITLE
[New Tool]: Add spline

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Spine is a 3d website building tool.

### Use Case

It helps to create modern 3d websites easily.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/8409b3c5-75fa-4ba5-a506-9f0d9b4c354f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
