### ISSUE TITLE
[New Tool]: Add logo AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

LogoAI is a AI powered logo generator, which creates logos with creative and profressional design.

### Use Case

It helps to generate logos using AI.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/bb88ab8d-d3db-4d19-b067-9c29b6ab611a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
