### ISSUE TITLE
[New Tool]: Add zapier

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Zapier provides workflows that allow different web applications to be used in the same workflow. Their products focus on automating recurring tasks, such as lead management. 

### Use Case

This is used to automate tasks and provides workflows.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/ce93b60e-6256-42ed-8c6d-11ed4c095ab6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
