### ISSUE TITLE
[New Tool]: Add bubble

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Bubble is full-stack no code app builder.

### Use Case

This helps people to build their own apps easily without using/learning coding and tech.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/b8e2b6a6-3b00-4ae6-9403-62eaffffe8d9)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
