### ISSUE TITLE
[New Tool]: Add AISEO

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

AISEO is a search engine optimization tool for making the website SEO friendly, which is powered by AI.

### Use Case

This helps to make the website SEO friendly using AI.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/131477601/7a4a1b8c-ca43-4d90-b4e7-625dc310f03c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , i have assigned this task to you. Please complete within 2 days and also add a 30-second demo video. Good Luck!
