### ISSUE TITLE
[Feature Request]: Making a profile part in the navbar

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Thee profile will contain user name, email, book marked items

### Use Case

Thee profile will contain user name, email, book marked items

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ayush-848 , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
