### ISSUE TITLE
bug: Replit GhostWriter card is not showing

### ISSUE THREAD

**Issue by Lymah123** [HimanshuNarware/Devlabs#162]
**Describe the bug**
The Replit GhostWriter card is not showing on the Devlab app

**Expected behavior**
I expected a display logo of the app

**Screenshots**

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [ ] Working under Hacktomberfest/Hacksquad*
- [x
![Screenshot (1348)](https://github.com/HimanshuNarware/Devlabs/assets/109049037/0552e6c6-e85f-4fbb-a96a-70ea51b4ffb4)
] Working under Slop 3.0 *

**Comment by Lymah123** [comment]
Hi @HimanshuNarware , can I work on the issue?

**Comment by HimanshuNarware** [comment]
@Lymah123  are you working under slop 3.0 ?
