### ISSUE TITLE
Add feature in section in readme

### ISSUE THREAD

**Issue by ananyag309** [HimanshuNarware/Devlabs#1635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add feature in section in readme, which highlights that this project is part of the open source program - gssoc, which will make it more impressive.

### Suggested Change

Something like this
![readmee](https://github.com/user-attachments/assets/e7c8bda4-8605-4777-b758-6e5c2464bafd)

### Rationale

please assign this issue to me under gssoc

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ananyag309 , i have assigned this task to you. Please complete within 3 days and also add a 30-second demo video. Good Luck!
