### ISSUE TITLE
[New Tool]: add new collabration tool Notion

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Notion: An all-in-one workspace for notes, tasks, databases, and collaboration.

### Use Case

Notion: An all-in-one workspace for notes, tasks, databases, and collaboration.

### Benefits

Notion: An all-in-one workspace for notes, tasks, databases, and collaboration.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
@ANKeshri @panwar8279 "Notion is already present in out database" 
![image](https://github.com/user-attachments/assets/758c230f-05cf-43f1-a21c-58f328bcc06e)

**Comment by ANKeshri** [comment]
> @ANKeshri @panwar8279 "Notion is already present in out database" ![image](https://private-user-images.githubusercontent.com/105718863/349492188-758c230f-05cf-43f1-a21c-58f328bcc06e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMTk3NzIsIm5iZiI6MTcyMTIxOTQ3MiwicGF0aCI6Ii8xMDU3MTg4NjMvMzQ5NDkyMTg4LTc1OGMyMzBmLTA1Y2YtNDNmMS1hMjFjLTU4ZjMyOGJjYzA2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxMjMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWJkNjlkNmM1OTU2NGFjNDFmNDE2MWI0MzEwOTU4YmRhNzMwMTBmZDYxMjM4NTg2NzZmMzBjOTk2MmUxMWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQSNch_I-Q_ypM_ul3e24DfLygLnJAJqUq72XAm93SE)

It is not present in collaboration tool

**Comment by panwar8279** [comment]
Hi @ANKeshri , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
