### ISSUE TITLE
[New Tool]: add new collaboration tool Basecamp:

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Basecamp: A project management and team collaboration tool that organizes projects, teams, and communication in one place.

### Use Case

Basecamp: A project management and team collaboration tool that organizes projects, teams, and communication in one place.

### Benefits

Basecamp: A project management and team collaboration tool that organizes projects, teams, and communication in one place.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
