### ISSUE TITLE
[New Tool]: Add Microsoft Power Automate in Productivity Tools

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 A service for automating workflows between apps and services.

### Use Case

Automating workflows between Microsoft and third-party apps.

### Benefits

Powerful automation, extensive integrations, and customizable workflows.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@panwar8279 I want to work on this issue , please assign it to me

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
