### ISSUE TITLE
[New Tool]:  Adding new tool IFTTT in productivity tool

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A service that allows users to create chains of conditional statements (applets) for automating tasks.

### Use Case

Creating conditional automations between apps and devices.

### Benefits

Simple applets for automation, supports a wide range of services, and user-friendly setup.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@panwar8279 I want to work on this issue , please assign it to me

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
