### ISSUE TITLE
[New Tool]: add new course platform "Khan Academy"

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Khan Academy: A non-profit educational organization providing free, high-quality educational content and resources for all ages.

### Use Case

Khan Academy: A non-profit educational organization providing free, high-quality educational content and resources for all ages.

### Benefits

Khan Academy: A non-profit educational organization providing free, high-quality educational content and resources for all ages.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
