### ISSUE TITLE
[New Tool]: Add new productivity tool calendly 

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A scheduling tool to streamline meeting bookings.

### Use Case

Scheduling meetings without the back-and-forth emails.

### Benefits

Easy scheduling, integrations with calendars, and customizable booking links.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maana-Ajmera** [comment]
@panwar8279 I want to work on this issue , please assign it to me

**Comment by Kiran-pande-30** [comment]
@panwar8279 @Maana-Ajmera calendly is already present in the database.
![image](https://github.com/user-attachments/assets/3f500fc9-a0c7-493d-a119-ac1f8c19d92d)

**Comment by Maana-Ajmera** [comment]
> @panwar8279 @Maana-Ajmera calendly is already present in the database. ![image](https://private-user-images.githubusercontent.com/105718863/349493077-3f500fc9-a0c7-493d-a119-ac1f8c19d92d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjczOTgsIm5iZiI6MTcyMTIyNzA5OCwicGF0aCI6Ii8xMDU3MTg4NjMvMzQ5NDkzMDc3LTNmNTAwZmM5LWEwYzctNDkzZC1hMTE5LWFjMWY4YzE5ZDkyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxNDM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDc3ZGMxMTdlNTViNDM4Mjg4NmVjNzNiNjljZmQzNGViZDQwYzhlMjNjYjhiYmQzNzRjNjUzMTQzZGZkMTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JmcZo7xfzsU7_9m8Y1UvCKYvdP0IkXajzauXdR-1jyU)

@Kiran-pande-30 @panwar8279  yes, it's there on the home page but it's not there specifically in the "Productivity Tools" section which is present in the menu , I want to add it there for easy access to users according to the category they want to select .

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
