### ISSUE TITLE
Improve the Readme file for backend

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#167]
**Is your feature request related to a problem? Please describe.**
Improve the Readme file for backend

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under DwoC*

**Comment by Shivam250702** [comment]
@HimanshuNarware  Kindly assign this issue

**Comment by UncleWeeds** [comment]
@HimanshuNarware I am a participant in DWOC, I would like to work on this issue
