### ISSUE TITLE
[New Tool]: ADD ERASER IN Collaboration Tools

### ISSUE THREAD

**Issue by kartikmehta18** [HimanshuNarware/Devlabs#1670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Documents & diagrams for engineering teams
All-in-one markdown editor, collaborative canvas, and diagram-as-code builder

### Use Case

![image](https://github.com/user-attachments/assets/c5d85f44-141f-4d16-994a-c1941e62c1af)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b9f2eeaa-ee65-46d0-80f3-89f6bdf340b2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kartikmehta18 , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!

**Comment by kartikmehta18** [comment]
> Hi @kartikmehta18 , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!

https://github.com/HimanshuNarware/Devlabs/pull/2027 plz review
