### ISSUE TITLE
Dark theme is not working effectively on About section

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#168]
**Describe the bug**
The Dark theme is not working properly with About section

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] I am working under DWoC'  23

**Comment by itzabhinavarya** [comment]
@HimanshuNarware  Kindly Assign

**Comment by HimanshuNarware** [comment]
@itzabhinavarya  Dwoc'23 not started yet, Dwoc tag issues only for the organization varification, but you can still work on those issue ,but you are not get any points  for PRs

**Comment by itzabhinavarya** [comment]
@HimanshuNarware But i have registered for KwoC'23. Can i still register for DWoC'23 ? If yes ,. Kindly provide me the registration form link.

**Comment by HimanshuNarware** [comment]
@HimanshuNarware yes you can, simply just go on their website  and signup as contributor.

**Comment by itzabhinavarya** [comment]
Kindly Assign me those task when the DWoC'23 started. As i have requested
first on the issue for assign. So assign the task to me by priority wise.

Thanks for guidance.

**Comment by brewcoder6113** [comment]
kindly assign

**Comment by git-akhi3** [comment]
Please assign me this issue for gssoc'24

**Comment by HimanshuNarware** [comment]
@git-akhi3  assigned you

**Comment by git-akhi3** [comment]
hey i have created a pull request , kindly review and let me know if any changes are required

**Comment by HimanshuNarware** [comment]
@git-akhi3  I already review the PR also suggested some changes
