### ISSUE TITLE
[New Tool]: JSON Formatter Extension

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Makes JSON easy to read. Open source.

The original JSON Formatter, now with optional dark mode 🌚

Auto-formats JSON when you load it in a browser tab.

### Use Case

- Fast, even on very long JSON pages
- Dark mode
- Syntax highlighting
- Collapsible trees, with indent guides

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2064822d-2355-4779-94c7-24bbfe1b1f56)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by Kiran-pande-30** [comment]
Hello @Maheshwari-Love @panwar8279 this tool is already present in database
![image](https://github.com/user-attachments/assets/fc04b404-cf53-4622-8901-3bb051bb5b55)
