### ISSUE TITLE
[New Tool]:  Detailed SEO exetension

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Get SEO insights at the click of a button to any website you're currently on. Built by full-time SEO's for daily analysis.

Get SEO-related insights at the click of a button to any website you're currently on.

### Use Case

Pull back their title tag, meta description, meta robots tag and much more.

Save hours of time looking through the source code of this page with our SEO analysis extension.

### Add ScreenShots

![Uploading image.png…]()

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
