### ISSUE TITLE
Improve the UI of the About Section

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#169]
**Is your feature request related to a problem? Please describe.**
Improve the UI of the About section, the dark theme is causing issues with about section

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under DWoC '23*
- [ ] Working under Slop 3.0 *

**Comment by itzabhinavarya** [comment]
@HimanshuNarware Kindly Assign

**Comment by HimanshuNarware** [comment]
@itzabhinavarya Dwoc'23 not started yet, Dwoc tag issues only for the organization varification, but you can still work on those issue ,but you are not get any points for PRs

**Comment by Shivam250702** [comment]
@HimanshuNarware  Kindly assign this issue to me

**Comment by HimanshuNarware** [comment]
you can work under Kwoc'23

**Comment by mendacium-a11y** [comment]
Hey! I'd like to take this up if still availabke

**Comment by ayann07** [comment]
I would like to work on this under KWOC

**Comment by vaishnavi192** [comment]
@HimanshuNarware I would like to work on this issue under DWOC'24. Can you tell more details what exact changes do you want? plz assign me this

**Comment by vaishnavi192** [comment]
@HimanshuNarware I will start working on it soon. thanks

**Comment by rahulpoonia29** [comment]
@HimanshuNarware I would like to work on this issue. I can both improve the UI and fix the issues of images with the light mode. Can you kindly assign this to me under GSsoC'

**Comment by rahulpoonia29** [comment]
I am referring to this issue https://github.com/HimanshuNarware/Devlabs/issues/157
