### ISSUE TITLE
[New Tool]: Adding ProofHub for collaboration tools

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Proofhub gives users a range of features, which help them bolster collaboration among their team.

### Use Case

ProofHub is a work management tool that offers a comprehensive suite of collaboration and project management functions

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a0c825b8-44a2-470c-bede-1f826b94f609)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
