### ISSUE TITLE
Add Testimonial section for Website

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#170]
**Is your feature request related to a problem? Please describe.**
Add Testimonial section for Website

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under DWoC '23*
- [ ] Working under Slop 3.0 *

**Comment by itzabhinavarya** [comment]
@HimanshuNarware  Sir, Kindlt assign this issue to me.

**Comment by HimanshuNarware** [comment]
@itzabhinavarya Dwoc'23 not started yet, Dwoc tag issues only for the organization varification, but you can still work on those issue ,but you are not get any points for PRs

**Comment by ayann07** [comment]
I would like to work on this under KWOC.

**Comment by Mayank77maruti** [comment]
Hi @HimanshuNarware , please you assign this issue to me.
