### ISSUE TITLE
[Feature Request]: Display empty state image if item not found

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

check this out

### Use Case

for bettrer user experience

### Benefits

help user to easy and smooth experience

### Add ScreenShots

![image](https://github.com/user-attachments/assets/234175f6-f54e-4ae3-9e50-b988559ebe09)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
