### ISSUE TITLE
[Bug]: Make home page responsive

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,

### Expected behavior

home page must be responsive in mobile devices

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e36abe22-0fc3-4943-97f5-151308b4f104)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
