### ISSUE TITLE
[New Tool]: Add Invision

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

InVision Freehand is a tool for ideating, planning, executing, and tracking projects with your team. It feels like you’re holding a marker and making ideas happen on a digital canvas.

### Use Case

It is used for ideating, planning, executing, and tracking projects with your team.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/dd82d326-e9f2-4bc4-b798-fbc0b215119c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
