### ISSUE TITLE
[New Tool]: Add UXpin

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

UXPin lets you design UI with code-backed components and export production-ready code. You can also use AI Component Creator with ChatGPT to generate layouts ,forms and more.

### Use Case

It used to design UI with code-backed components using AI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d15f5b84-27d3-48b7-8fc5-9e67437b07c7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I am assigning this task to you. Kindly complete this within 2 days and also add 30sec demo video. Good Luck!
