### ISSUE TITLE
[New Tool]: Add Miro

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Miro is a collaborative online platform that helps teams think and create together, from brainstorming to execution. It offers six core capabilities, such as diagramming, workshops and more

### Use Case

It is a collaborative platform used for teams to think and create together.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/12b47fff-09d5-407f-933e-d4427287e7bc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30 sec. Good luck!
