### ISSUE TITLE
[New Tool]: Add Dora

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Dora is a 3d animated websites designer which is powered by AI.

### Use Case

It helps you to Publish stunning 3D animated websites without writing a line of code. Generate landing pages and design inspiration with Dora AI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fe7d94dc-f2c9-4890-9a96-022047d04d62)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30 sec. Good luck!
