### ISSUE TITLE
[New Tool]: Add sketch

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Sketch provides all the tools to help you create — from early wireframes, to flexible design systems. Powerful vector editing. An infinite Canvas. Intuitive, life-like prototyping and more.

### Use Case

Sketch helps you to design, collaborate, prototype and handoff any project.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/13e03f40-322e-46c6-9511-7c0f8bc48be6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30 sec. Good luck!
