### ISSUE TITLE
[New Tool]: Add 10web

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

10Web.io helps you create, host, and optimize your website with AI. Generate content and images, sell online, and get support from Google Cloud and WordPress experts.

### Use Case

10web is used to create, host and do more stuff using AI.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/65f70e5e-b580-44c5-a96d-1562d177cebc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30 sec. Good luck!
