### ISSUE TITLE
[New Tool]: Add Vidnoz

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Vidnoz is the top free AI video generator platform, helping create videos with AI avatars, do face swaps, etc. Start making videos with Vidnoz AI tools now.

### Use Case

Vidnoz is used to generate Free AI videos , Avatars etc ,for free.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c6e66d65-6a20-4492-a47b-974e2f858ac2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30 sec. Good luck!
