### ISSUE TITLE
[New Tool]: Add claude AI

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Claude is a next generation AI assistant built for work and trained to be safe, accurate, and secure.

### Use Case

Claude helps as an AI assistant built for work and trained.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ec5c240d-9bb1-4fd2-b090-da4af85c8ad1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30 sec. Good luck!
