### ISSUE TITLE
Inital local setup error due to static image file location

### ISSUE THREAD

**Issue by itzabhinavarya** [HimanshuNarware/Devlabs#174]
**Describe the bug**
When i initially setup the project i face this issue.
After identifying the issue, I got to know that it is happening cuz of static image file location. 
Even though Using an Icon svg in file is not a good idea, So for the icons i have installed a package "react-icons", which gives us almost every icon.
<img width="960" alt="image" src="https://github.com/HimanshuNarware/Devlabs/assets/95561280/60602c4f-1599-49d1-81e8-427bf624455f">

**Expected behavior**
1. No issue poped up initially when we setup the project locally.
2. Icons should be used from some icon provider package not from static file location.

**Screenshots**
<img width="960" alt="image" src="https://github.com/HimanshuNarware/Devlabs/assets/95561280/8d5c60d5-988d-40a9-b856-34abbcc49237">

<img width="960" alt="image" src="https://github.com/HimanshuNarware/Devlabs/assets/95561280/a865b34c-a2d7-4484-ab53-5f0bc7fe7837">

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under DWoC '23*
- [ ] Working under Slop 3.0 *

**Comment by itzabhinavarya** [comment]
@HimanshuNarware Assign this to me.

**Comment by HimanshuNarware** [comment]
@itzabhinavarya dont raise PR before getting assigned

**Comment by itzabhinavarya** [comment]
@HimanshuNarware Got it.
