### ISSUE TITLE
Responsive Issue: Tablet Navbar

### ISSUE THREAD

**Issue by sudip57** [HimanshuNarware/Devlabs#178]
**Describe the bug**
In the tablet mode, the navbar breaks and the search bar comes into the next line.

**Expected behavior**
I want to make it responsive even on tablet mode.

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/79646606/991549b8-52d7-4cb6-a4e9-d2948ef99e34)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Slop 3.0 *

**Comment by HimanshuNarware** [comment]
@sudip57 slop 3.0 end now ,but you can work under Kwoc'23. but first you need to do registration on kwoc official website

**Comment by S2codes** [comment]
Can you please assign me this issue
