### ISSUE TITLE
[BUG]Make website responsive

### ISSUE THREAD

**Issue by OgaDavid** [HimanshuNarware/Devlabs#18]
The website is not responsive on mobile and tablet devices. I'd love to fix this issue for Hacktoberfest. please  assign it to me @HimanshuNarware 

https://github.com/HimanshuNarware/Devlabs/assets/104001201/f1cf2c21-7522-4296-b3e4-fd95a9b87b15

**Comment by theavitw** [comment]
Hey, @OgaDavid 
I want to try it out.
Kindly assign me this issue.

**Comment by HimanshuNarware** [comment]
@OgaDavid  you can work on this issue

**Comment by OgaDavid** [comment]
Ok, i'll work on it. Thank you

**Comment by OgaDavid** [comment]
I think i've messed up my branch locally. i didn't pull the changes before i started fixing the navbar and now that i have pushed, i can't make a pull request 😭 it's just messed up

**Comment by sakshipatil4403** [comment]
@HimanshuNarware pls assign me this issue

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware pls assign me this issue

@sakshipatil4403  you can work on the hover effect of the icons present in footer section

**Comment by sakshipatil4403** [comment]
@HimanshuNarware i made the changes ...do check it

**Comment by Shivam250702** [comment]
@HimanshuNarware  Can i Work on this issue?
