### ISSUE TITLE
Add Text2SQL AI

### ISSUE THREAD

**Issue by ananyag309** [HimanshuNarware/Devlabs#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Text2SQL AI -  - Converts natural language queries into SQL queries.

### Use Case

please @panwar8279 ma'am assign this issue to me under gssoc

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ananyag309 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
