### ISSUE TITLE
Add tinkercard 

### ISSUE THREAD

**Issue by ananyag309** [HimanshuNarware/Devlabs#1817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Tinkercad - An app for 3D design, electronics, and coding.

### Suggested Change

tinkercard is a very proficient platform for eee 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ananyag309 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
