### ISSUE TITLE
Free Online Course Section 

### ISSUE THREAD

**Issue by manzil-infinity180** [HimanshuNarware/Devlabs#183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

** Add screenshot 
<img width="1510" alt="Screenshot 2023-12-10 at 10 32 21 PM" src="https://github.com/HimanshuNarware/Devlabs/assets/119070053/81d9fc56-b69b-4cb0-b5d0-95148560cef2">

SOME LINKS THAT SHOULD BE THE PART OF WEBSITE 
Biggest one - aiplex.lol
CourseClub.com
FreeCourseSite.com
GigaCourse.com
https://t.me/Pluralsight_Courses

I know its promotion of privacy but i think so it can be there on website

Checklist
Example  Fill x { [x] }  into  bracket

- [ ] I have checked the existing issues *
- [ ] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [ ] Working under Kwoc*
- [ ] Working under Dwoc*
- [ ] Working under Swoc*

**Comment by HimanshuNarware** [comment]
@manzil-infinity180  assigned you

**Comment by cpratik1307** [comment]
I will carry out the work that you assign me for GSSoC.
