### ISSUE TITLE
[New Tool]: Adding Upwork in remote jobs

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A large freelancing platform for various professional services.

### Use Case

Ideal for freelancers seeking diverse projects across different fields like tech, design, and writing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
