### ISSUE TITLE
[New Tool]: Adding Remote OK in remote jobs section

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A job board aggregating remote work opportunities from various sources.

### Use Case

Great for job seekers wanting a centralized place to find remote jobs across industries.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
