### ISSUE TITLE
[New Tool]: Adding Webpack

### ISSUE THREAD

**Issue by Maana-Ajmera** [HimanshuNarware/Devlabs#1847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

We can add webpack in frontend tools , A module bundler for JavaScript applications.

### Use Case

Essential for bundling JavaScript files, assets, and dependencies into optimized bundles.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Maana-Ajmera , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
