### ISSUE TITLE
Create Bookmark Notification

### ISSUE THREAD

**Issue by anand-harsh** [HimanshuNarware/Devlabs#185]
**Describe the bug**
 Whenever a bookmark is added user don't get to know that whether it is added or not without going to bookmarks page.

**Expected behavior**
When user clicks Add Bookmark button then a popup showing "Repository Bookmarked" comes

**Screenshots**

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Kwoc*
- [x] Working under Dwoc*
- [x] Working under Swoc*

**Comment by HimanshuNarware** [comment]
@anand-harsh  assigned you
