### ISSUE TITLE
[Bug]: There is some blank space on the right side of the webpage in mobile-view.

### ISSUE THREAD

**Issue by vishanurag** [HimanshuNarware/Devlabs#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- There is some blank space on the right side of the webpage in mobile-view.
- It does not looks responsive.

### Expected behavior

- There should not be any blank space on right side of the webpage.

### Add ScreenShots

![Screenshot 2024-07-16 173339](https://github.com/user-attachments/assets/39454f8c-04de-4378-94f4-5833d701c54f)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by vishanurag** [comment]
@panwar8279 Please assign this issue to me under GSSoC'24

**Comment by vishanurag** [comment]
@panwar8279 Please assign this issue to me under GSSoC'24

**Comment by panwar8279** [comment]
Hi @vishanurag , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!

**Comment by vishanurag** [comment]
Sure!
