### ISSUE TITLE
[New Tool]: google tech dev guide

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#1852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

The Google Tech Dev Guide is a free resource offering tools, videos, and exercises to help developers improve their coding skills and prepare for technical interviews. It includes coding challenges, algorithmic puzzles, and tips from Google engineers to enhance problem-solving abilities and technical knowledge.

### Use Case

The Google Tech Dev Guide can be used by developers to practice and refine their coding skills in preparation for job interviews or competitive programming. It's also valuable for students looking to enhance their understanding of algorithms and data structures.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b6f3611f-e324-4f47-9603-f7372e399a57)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
