### ISSUE TITLE
Categorise the projects on bookmark page

### ISSUE THREAD

**Issue by anand-harsh** [HimanshuNarware/Devlabs#187]
**Describe the bug**
Whenever the project is added on bookmark then all are mixed and tought to separate it according to their categories.

**Expected behavior**
When project is added in bookmark it get listed to its own category.

**Screenshots**

**This is Screenshot before solving the issue**

![image](https://github.com/HimanshuNarware/Devlabs/assets/94885893/79f3008b-2c2b-48d1-8c88-79ddcdd380da)

**This is Screenshot after solving the issue**

![image](https://github.com/HimanshuNarware/Devlabs/assets/94885893/07085bc6-fff1-45b3-ace2-c8c587109e05)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Kwoc*
- [x] Working under Dwoc*
- [x] Working under Swoc*

**Comment by HimanshuNarware** [comment]
@anand-harsh  this is not looking good ,try different UI

**Comment by anand-harsh** [comment]
> @anand-harsh this is not looking good ,try different UI

Yes this will not look the same
It will be displayed as



Title

Projects under that topic

**Comment by anand-harsh** [comment]
Alignment issue as I have not done css part yet

**Comment by HimanshuNarware** [comment]
@anand-harsh ok

**Comment by anand-harsh** [comment]
> @anand-harsh ok

Can you please assign me this issue

**Comment by HimanshuNarware** [comment]
@anand-harsh  can you explain how you resolve this  problem
