### ISSUE TITLE
[New Tool]: Add pyTorch

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

PyTorch is a machine learning library based on the Torch library, used for applications such as computer vision and natural language processing,

### Use Case

PyTorch is a machine learning library based on the Torch library, used for applications such as computer vision and natural language processing,

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 , I am assigning this task to you. Kindly complete this within 2 day and also add a 30 sec demo video. Good luck!
