### ISSUE TITLE
[New Tool]: Add Code Signal

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#1892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

CodeSignal is a coding practice platform that offers coding challenges, assessments, and interview preparation material.

### Use Case

CodeSignal is a coding practice platform that offers coding challenges, assessments, and interview preparation material.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 , I am assigning this task to you. Kindly complete this within 2 day and also add a 30 sec demo video. Good luck!
