### ISSUE TITLE
[Bug]: My Profile link on the navbar is not visible properly .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#1895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My Profile link on the navbar is not visible properly and is flowing out of the screen .

### Expected behavior

I can make the changes to fix this issue , kindly assign this to me .

### Add ScreenShots

![Screenshot (764)](https://github.com/user-attachments/assets/adec47d1-13ce-4d2c-bafd-6170b0398869)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@panwar8279 kindly assign me this issue .

**Comment by panwar8279** [comment]
Hi @meetarora10 ,  Please work with updated code and also add a 30 sec demo video. Good luck!
