### ISSUE TITLE
In Dark mode Active Navbar item not visible

### ISSUE THREAD

**Issue by S2codes** [HimanshuNarware/Devlabs#191]
**Describe the bug**
In Dark mode, the active Navbar item is not visible. When I click on a NavItem to go to another page, the active NavItem becomes blue, which is not visible in Dark mode. However, if I click on any other element, it becomes black again.

**Expected behavior**
In Dark mode, the active Navbar item is not visible, and the blue color of NavItem is also not visible. It should be a different color that is clearly visible.

**Screenshots**
![Screenshot 2023-12-23 155448](https://github.com/HimanshuNarware/Devlabs/assets/81303389/564f1dc0-641d-4204-8091-2b7e9ab62c95)

Example  Fill x { [x] }  into  bracket

- [ ] I have checked the existing issues *
- [ ] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [ ] Working under Kwoc*
- [ ] Working under Dwoc*
- [ ] Working under Swoc*

**Comment by HimanshuNarware** [comment]
@S2codes assigned you

**Comment by HimanshuNarware** [comment]
@S2codes  someone is already working on this issue.
