### ISSUE TITLE
Feature ✨: Add scroll to top button with progress button on all pages

### ISSUE THREAD

**Issue by TheNikhilRaj** [HimanshuNarware/Devlabs#1919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @HimanshuNarware  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar scroll to top button present on the website.

### Use Case

it help user to use perfectly!

### Benefits

@HimanshuNarware  ,Could you please assign me this issue under gssoc'24 ?

GSSOC'24

### Add ScreenShots

![343755959-404f8025-9ca5-4dbc-b660-cac20005d1c3](https://github.com/user-attachments/assets/54a1eea0-626a-48b0-b24a-44946263413f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Scroll to top button is already exiting, could you please clarify it?

**Comment by TheNikhilRaj** [comment]
> Scroll to top button is already exiting, could you please clarify it?

@panwar8279 this is scroll to top progress button.

**Comment by panwar8279** [comment]
@TheNikhilRaj , Start working on it
