### ISSUE TITLE
Adding scroll-reveal to improve the UI || Work under KWoC 

### ISSUE THREAD

**Issue by sambitsingha** [HimanshuNarware/Devlabs#192]
The scroll reveal , if added will load the elements one affter the other. It can be customised according to time-delay and directions according the UI.

I would like to work on it for KWoC 2023 :)

**Comment by sambitsingha** [comment]
@HimanshuNarware The project name is `Devlabs`. But in the website it is `Devlaps`. 
Should I correct this minor change too ?

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware The project name is `Devlabs`. But in the website it is `Devlaps`.
> 
> Should I correct this minor change too ? Or is that already correct ??

No
