### ISSUE TITLE
[Feature Request]: Add Dark and Light mode theme option.

### ISSUE THREAD

**Issue by kou95shik** [HimanshuNarware/Devlabs#1924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add the feature in nav bar that can switch dark mode to light mode and vice versa.

### Use Case

It will help for user in night.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Light mode and dark mode is already exist.
