### ISSUE TITLE
Fix: Button of error page

### ISSUE THREAD

**Issue by AaadityaG** [HimanshuNarware/Devlabs#193]
**Describe the bug**
The button on 404 page is not sticky 

**Expected behavior**
It must be sticky to page

**Screenshots**

https://github.com/HimanshuNarware/Devlabs/assets/114663382/79f3d45c-217c-41d5-baba-4d073c35d8f8

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Kwoc*
- [ ] Working under Dwoc*
- [ ] Working under Swoc*

**Comment by Harikaran1729** [comment]
Hello. I would like to work on this issue... I am participating in DWoC and this contribution would help me with that and help me learn and explore more in frontend.. Please assign the task to me..

**Comment by rahulpoonia29** [comment]
@HimanshuNarware I would like to work on this issue. Can you assign it to me under GSsoC'
