### ISSUE TITLE
[Bug]:  Contact Form Responsive

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,
contact form is not responsive

### Expected behavior

it should be visible propr in responsive screen

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5aff9085-4741-428c-ae76-e614de43d0eb)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!

**Comment by dhruv8433** [comment]
Thank you @panwar8279
