### ISSUE TITLE
[Bug]: Footer Not Responsive title goes out of body

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,
footer heading goes out of bound

### Expected behavior

it should be visible proper

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d1767d33-9f90-4b0a-8474-e2767b231b04)

![image](https://github.com/user-attachments/assets/6ced81be-8c04-4be4-a2cc-859c3111b2b5)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!

**Comment by dhruv8433** [comment]
Thank you @panwar8279 

please check this https://github.com/HimanshuNarware/Devlabs/pull/1917 you might forgot to add level 
please add
