### ISSUE TITLE
[New Tool]: Flock

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Flock: A messaging and collaboration tool that includes team messaging, video conferencing, and productivity tools.

### Use Case

Flock: A messaging and collaboration tool that includes team messaging, video conferencing, and productivity tools.

### Benefits

Flock: A messaging and collaboration tool that includes team messaging, video conferencing, and productivity tools.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Hi @ANKeshri , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
