### ISSUE TITLE
[New Tool]: Ryver

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Ryver: A collaboration platform that integrates team communication with task management and workflow automation.

### Use Case

Ryver: A collaboration platform that integrates team communication with task management and workflow automation.

### Benefits

Ryver: A collaboration platform that integrates team communication with task management and workflow automation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ANKeshri** [comment]
@panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Hi @ANKeshri ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
