### ISSUE TITLE
[New Tool]: nTask

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

nTask: A project management tool that helps teams plan, collaborate, and track their work with features like task assignments, meeting management, and risk tracking

### Use Case

nTask: A project management tool that helps teams plan, collaborate, and track their work with features like task assignments, meeting management, and risk tracking

### Benefits

nTask: A project management tool that helps teams plan, collaborate, and track their work with features like task assignments, meeting management, and risk tracking

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
