### ISSUE TITLE
[New Tool]: Zoho Connect: 

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Zoho Connect: A team collaboration software that brings people, resources, and apps together on a single platform to create a connected workplace.

### Use Case

Zoho Connect: A team collaboration software that brings people, resources, and apps together on a single platform to create a connected workplace.

### Benefits

Zoho Connect: A team collaboration software that brings people, resources, and apps together on a single platform to create a connected workplace.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
