### ISSUE TITLE
[New Tool]:  adding Glip

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Glip: A messaging and collaboration tool by RingCentral that offers team messaging, task management, file sharing, and video conferencing in one place.

### Use Case

Glip: A messaging and collaboration tool by RingCentral that offers team messaging, task management, file sharing, and video conferencing in one place.

### Benefits

Glip: A messaging and collaboration tool by RingCentral that offers team messaging, task management, file sharing, and video conferencing in one place.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri, I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
