### ISSUE TITLE
[New Tool]: adding course plateform LearnWorlds

### ISSUE THREAD

**Issue by ANKeshri** [HimanshuNarware/Devlabs#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

LearnWorlds: A platform for creating, selling, and marketing online courses with interactive features.

### Use Case

LearnWorlds: A platform for creating, selling, and marketing online courses with interactive features.

### Benefits

LearnWorlds: A platform for creating, selling, and marketing online courses with interactive features.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ANKeshri ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
