### ISSUE TITLE
[New Tool]: Add Tabnine tool

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#1958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Tabnine coding assistant can do more than just code generation using AI. It can write code faster than you and even predict the next lines in your codebase.

### Use Case

The tool is beneficial for those who want to save time on coding or beginners in software development

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Chandu6702 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
