### ISSUE TITLE
Remove Dark Mode

### ISSUE THREAD

**Issue by amanr-dev** [HimanshuNarware/Devlabs#198]
Images do not appear correctly in Dark Mode.

Screenshots:
![Screenshot 2024-02-12 163431](https://github.com/HimanshuNarware/Devlabs/assets/124811276/ba206be6-738a-4c47-8b56-88fd304c7b32)
![Screenshot 2024-02-12 163424](https://github.com/HimanshuNarware/Devlabs/assets/124811276/ed9d85d9-7a5e-4d42-b5e1-7249c69d6cb1)

**Comment by HimanshuNarware** [comment]
@amanr-dev  dont remove try to resolve the bug

**Comment by brewcoder6113** [comment]
please assign me this issue under DWOC'23

**Comment by Gokilp** [comment]
assign  to me

**Comment by amanr-dev** [comment]
> assign to me

Go for it
