### ISSUE TITLE
[New Tool]: Want to add a progress bar on the top of the navbar .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#1982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I want to add a progress bar on the top of the navbar .

### Use Case

This progress bar progresses as the page scrolls up and down which makes the page look more attractive .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @meetarora10 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!

**Comment by meetarora10** [comment]
@panwar8279 my merged PRs from this repo are not shown in leaderboard but few hours ago everything was fine .
