### ISSUE TITLE
[Bug]: Responsive Faq's Page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

we can make faqs page respnosive

### Expected behavior

it should be open properly in responsive devices

### Add ScreenShots

![image](https://github.com/user-attachments/assets/38520d39-1c28-4213-bc97-4424bfa991a1)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!

**Comment by dhruv8433** [comment]
Thank you @panwar8279
