### ISSUE TITLE
[Bug]:  Make About us responsive

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#1985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

about us is not responsive

### Expected behavior

it should be proper open in responsive devices
but currently content goes out of body

### Add ScreenShots

![image](https://github.com/user-attachments/assets/3deaea5e-c7ab-4679-afb7-a0a4f5be9af8)

![image](https://github.com/user-attachments/assets/9b6ccbf0-95c4-40d5-a7cd-efd2c1c6c2e1)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
