### ISSUE TITLE
[Feature request]Add infinite scroller with a progress bar at the top

### ISSUE THREAD

**Issue by ayushshukla011** [HimanshuNarware/Devlabs#20]
![Screenshot 2023-10-01 183334](https://github.com/HimanshuNarware/Devlabs/assets/116294361/8d1a1c4d-4f15-4123-9571-81632dd0c0ab)
instead of pagination we can use a infinite loading and can use a progress bar on top to show scrolling length.

**Comment by Jagdeep30** [comment]
I can do that. You can assign it to me.

**Comment by HimanshuNarware** [comment]
> I can do that. You can assign it to me.

@Jagdeep30  This issue is already assigned to @ayushshukla011 but  if you want to work you can work on the social icon present on the devlabs,  Add a suitable hover effect on the icons.
