### ISSUE TITLE
[Feature Request]:  fixing css of faq in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [HimanshuNarware/Devlabs#2005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

fixing css in moile

### Use Case

making website responsive 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/bd12e0ed-2d1c-4252-afdc-304367cbb9b7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhairyagothi , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!

**Comment by dhairyagothi** [comment]
@panwar8279 please merge PR #2048 so that i can start working on this issue
