### ISSUE TITLE
[New Tool]: AZMovies

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Features a large library of movies available for free streaming in high quality, with a focus on providing the latest releases and classics.It features a large library of movies available for free high-quality streaming

### Use Case

A film lover can stream the latest releases and classic movies in high quality for free, ensuring access to both current hits and timeless favorites.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ef997d55-9b50-4447-8cc5-f0de40f796bc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
