### ISSUE TITLE
[New Tool]: Movie4u

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Offers free streaming of movies and TV shows with a clean interface and the ability to sort by genre, release year, and IMDB rating.

### Use Case

A user can easily find and stream movies and TV shows by sorting through a clean interface based on genre, release year, and IMDB rating.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/10c8a7df-c89f-4356-964f-fd64fe55003c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
