### ISSUE TITLE
[New Tool]: watch-free

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Provides access to a broad range of movies and TV shows for free, with options to search by title, genre, and release year.It provides free access to a broad range of movies and TV shows

### Use Case

A viewer can quickly locate and stream a wide variety of movies and TV shows for free by searching through options like title, genre, and release year.various

### Add ScreenShots

![image](https://github.com/user-attachments/assets/211276f7-2f2c-4653-bb55-d64fc2684714)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
