### ISSUE TITLE
[New Tool]: GoMovies

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A popular site for free movie and TV show streaming, featuring an easy-to-navigate layout and a diverse range of genres and categories.

### Use Case

A viewer can quickly find and stream a diverse selection of movies and TV shows for free, thanks to the site’s easy-to-navigate layout and wide range of genres and categories.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/aeda94b2-4496-4e7c-bb46-0bcd79aee94c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
