### ISSUE TITLE
[New Tool]: SolarMovie

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Offers free streaming of a wide variety of movies and TV shows, with high-quality video and minimal ads, allowing users to filter by genre and country.

### Use Case

A user can enjoy high-quality video streaming of a diverse selection of movies and TV shows for free, with minimal ads and the ability to filter by genre and country.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ce57ce13-9210-4500-96ec-6ac93180f9a5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@heli0707 , Start working on it.
