### ISSUE TITLE
[Feature Request]:  Providing notification system

### ISSUE THREAD

**Issue by DevGajjar28** [HimanshuNarware/Devlabs#2028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

offering to add a notification at contact us page. After filling a form details and submit user get to  know that there message was sent successfully.

### Use Case

providing user acknowledgement that there message was sent to admin/owner.

### Add ScreenShots

![Screenshot 2024-06-30 161309](https://github.com/user-attachments/assets/1c98bcfb-4127-4681-a845-6bff9a5c37a6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @DevGajjar28 , I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!
