### ISSUE TITLE
In readme.md 

### ISSUE THREAD

**Issue by Aditijainnn** [HimanshuNarware/Devlabs#2037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In readme.md adding contributors section and adding markdowns

### Use Case

It will make readme more cool

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@Aditijainnn , Please start working on it.

**Comment by Aditijainnn** [comment]
> @Aditijainnn , Please start working on it.

Its done
