### ISSUE TITLE
[New Tool]: add FutureLearn

### ISSUE THREAD

**Issue by ImmidiSivani** [HimanshuNarware/Devlabs#2044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

FutureLearn provide courses for many cs concepts.

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ImmidiSivani ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
