### ISSUE TITLE
[Bug]: Remove Bookmark

### ISSUE THREAD

**Issue by komal-agarwal5** [HimanshuNarware/Devlabs#2051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The remove bookmark function is not working

https://github.com/user-attachments/assets/ff5d2389-7d30-4a1a-b824-eb587ba6ca3d

### Expected behavior

It should have gotten removed
I want to fix this

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @komal-agarwal5 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
