### ISSUE TITLE
[New Tool]: Add Muzli

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Your daily dose of design with industry news, tools, and inspiration - all in one place.

Muzli takes the center stage as it replaces your default tab and becomes your simple and beautiful design oriented home page. 

### Use Case

Loved by hundreds of thousands designers worldwide, Muzli is the leading go-to browser extension for creative professionals.
Once installed, Muzli becomes your visual hub for the latest and most cutting-edge Design, UI, UX, and interactive content. It serves daily content from all major design and inspiration sources that ensures you will never miss the next big thing. 
Plus, our hand-picked, professionally curated "Muzli Picks" journal ensures you're treated to the crème de la crème of design inspiration.

### Add ScreenShots

![Screenshot 2024-07-22 013235](https://github.com/user-attachments/assets/f018c5a1-5ca2-41f5-826a-32b9c12b4270)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
