### ISSUE TITLE
[New Tool]: Add Site Palette

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Site Palette generates a color palette from any website, allowing designers to use it as a reference in their work.

### Use Case

As a designer or frontend developer, you know how important it is to have a tool that helps you quickly and easily generate beautiful color schemes for your projects. With our extension, you can do just that - simply visit any website and start building your palette. We've made it incredibly easy to use, and our seamless user experience means you can focus on creating without any distractions. Whether you're designing a website, creating graphics, or working on a new branding project, our extension is the perfect tool to help you get the job done. Give it a try today – we can't wait to see what you create with it!

### Add ScreenShots

![Screenshot 2024-07-22 013536](https://github.com/user-attachments/assets/3344872e-4a04-40eb-babc-300eb4cd698e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
HI @AsmitaMishra24 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
