### ISSUE TITLE
[New Tool]: Add Savee

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Save images from any site straight into your boards on savee.it

### Use Case

Allows you to save any image from any website straight into your Savee boards.

### Add ScreenShots

![Screenshot 2024-07-22 014028](https://github.com/user-attachments/assets/c3dc0055-3cfd-4102-9307-acf1fe357312)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
