### ISSUE TITLE
[New Tool]: Add "Frontend Mentor"

### ISSUE THREAD

**Issue by Ajita369** [HimanshuNarware/Devlabs#2063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A platform offering real-world front-end challenges for developers to improve their skills and showcase their work.

### Use Case

This is useful resource for developers.

### Benefits

Developers can enhance their skills . 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/294d2d57-add7-4dcb-9be2-a9723a1849a6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
it is already present in the database
