### ISSUE TITLE
[New Tool] : Add Ghostery Extension

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Ghostery is a sophisticated ad-blocking extension designed to remove ads that distract or interrupt you while you're viewing specific website content. 

I am participating in GSSOC'24
@HimanshuNarware, could you please assign me this issue

### Use Case

Ghostery is a free and open-source privacy and security-related browser extension and mobile browser application. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sreevidya-16 , I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!

**Comment by sreevidya-16** [comment]
@panwar8279, view this PR
