### ISSUE TITLE
[New Tool]: StayFocused Extension

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

StayFocusd is a productivity extension for Google Chrome that helps you stay focused on work by restricting your time on time-wasting websites.

### Use Case

StayFocusd is a useful Chrome extension that monitors how much time you've spent on specific sites and gives you the option to block 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sreevidya-16 , I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!

**Comment by sreevidya-16** [comment]
@panwar8279, view this PR
