### ISSUE TITLE
[New Tool]: Add HBO Max 

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Features a variety of movies, including HBO originals and other popular titles.

### Use Case

Features a variety of movies, including HBO originals and other popular titles.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@sreevidya-16 , Please start working on it.
