### ISSUE TITLE
To Add new tool elitmus

### ISSUE THREAD

**Issue by Abhishek0732** [HimanshuNarware/Devlabs#207]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- {[ ]} I have checked the existing issues *
- {[ ]} I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [ ] Working under Kwoc*
- [ ] Working under Dwoc*
- [ ] Working under Swoc*

**Comment by HimanshuNarware** [comment]
@Abhishek0732  explain the applications of the tool

**Comment by Abhishek0732** [comment]
Elitmus is the job portal website and it also conduct the pH test through which the many company hire the student.
You can check the given link: https://www.elitmus.com/users/5340861/dashboard

**Comment by Abhishek0732** [comment]
@HimanshuNarware this pr is not showing on my leaderboard please check it
