### ISSUE TITLE
[New Tool]: Add Glassdoor 

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Glassdoor is an online community for jobs and careers that helps people find and share information about companies and jobs

### Use Case

Glassdoor is an online community for jobs and careers that helps people find and share information about companies and jobs

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sreevidya-16 ,  I am assigning this task to you. Kindly complete this within 3 days and also add a 30 sec demo video. Good luck!

**Comment by sreevidya-16** [comment]
@panwar8279 sure
