### ISSUE TITLE
[Bug]: Heading of the main landing page is not visible due to black color .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The heading on the main landing page is not visible .

### Expected behavior

I can make changes in the CSS to fix this issue .

### Add ScreenShots

![Screenshot (806)](https://github.com/user-attachments/assets/bc648a03-57de-4348-9077-8eaac6f1f618)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@panwar8279 consider this issue .

**Comment by panwar8279** [comment]
Already done.
