### ISSUE TITLE
[Bug]: Backend tools page is not loading .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#2073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Contents of the backend tools page are not loading and only the footer is coming .

### Expected behavior

I can make the required changes to fix this issue .

### Add ScreenShots

https://github.com/user-attachments/assets/3639b8d6-5d64-4494-8e8f-8d7e934e5e7c

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@panwar8279 kindly consider this issue .

**Comment by meetarora10** [comment]
@panwar8279 please have a look .

**Comment by panwar8279** [comment]
Hi @meetarora10 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
