### ISSUE TITLE
[New Tool]: adding Udacity

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Provides "nanodegree" programs and courses focused on tech skills, including programming, data science, and AI.

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Already added.
