### ISSUE TITLE
[New Tool]: add Resumonk

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Helps create beautiful resumes and cover letters with various templates. 

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Already added
