### ISSUE TITLE
BUG: Search result doesn't get reset

### ISSUE THREAD

**Issue by AshutoshDash1999** [HimanshuNarware/Devlabs#208]
**Describe the bug**
When you search something, there is no way you can reset the search result. I have to refresh the page to reset the results.

**Expected behavior**
Search result should be reset after route change or when there is blank search.

**Screenshots**

https://github.com/HimanshuNarware/Devlabs/assets/46455250/c91dc5a1-c7dd-4fa8-9b78-626f0000a989

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under GSSOC*

**Comment by HimanshuNarware** [comment]
@AshutoshDash1999 assigned you

**Comment by Ech0Cipher** [comment]
Hey @HimanshuNarware i would like work on this issue can you assign me.

**Comment by HimanshuNarware** [comment]
@Ech0Cipher its already assigned you can work on another issue,

**Comment by AshutoshDash1999** [comment]
@HimanshuNarware will it be a good idea to add a reset button besides input field? currently I have implemented that when blank input is searched the data gets reset.

**Comment by HimanshuNarware** [comment]
@AshutoshDash1999 shared a video of your changes

**Comment by AshutoshDash1999** [comment]
@HimanshuNarware please check the changes

when an empty input is searched then searched data resets

https://github.com/HimanshuNarware/Devlabs/assets/46455250/d06e7858-be4b-4ad4-8a53-6655673cbc34

**Comment by aswinikalyan30** [comment]
Hey the video you just added doesn't match the expected behaviour of resetting it - and it would be great if you have a cross maybe to clear the input along with the input

**Comment by AshutoshDash1999** [comment]
> it would be great if you have a cross maybe to clear the input along with the input

yeah that will work too. @HimanshuNarware shall I implement this?

**Comment by HimanshuNarware** [comment]
ok

**Comment by AshutoshDash1999** [comment]
https://github.com/HimanshuNarware/Devlabs/assets/46455250/4b7cccc1-7408-4f36-a292-455dea509ac0

@HimanshuNarware does this look good?

**Comment by HimanshuNarware** [comment]
> 19-28-44.mp4 
> @HimanshuNarware does this look good?

Yep, Nice work

**Comment by AshutoshDash1999** [comment]
thanks will raise the PR then

**Comment by AshutoshDash1999** [comment]
@HimanshuNarware Please review the PR: https://github.com/HimanshuNarware/Devlabs/pull/284
