### ISSUE TITLE
Search box not working properly

### ISSUE THREAD

**Issue by kumar1397** [HimanshuNarware/Devlabs#209]
**Describe the bug**
When you are in another route other than home page, searching for any tools neither redirect you to the home page to show the result. After that on clicking the home button, it shows the result.

**Expected behavior**
On searching tools in any route, it should redirect to the home page and show the result.

**Screenshots**

https://github.com/HimanshuNarware/Devlabs/assets/122858524/c256db1e-a8a5-42da-926e-fb4f630f55a3

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under GSSoC*

**Comment by HimanshuNarware** [comment]
@kumar1397  someone is already working on this issue
