### ISSUE TITLE
[Bug]: Remove Duplicate Tools

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Removing duplicate tools from the database.

### Expected behavior

There should not be any duplicate tools in the database.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
