### ISSUE TITLE
[UI] The X logo on the footer should look better

### ISSUE THREAD

**Issue by AmitBiswas1402** [HimanshuNarware/Devlabs#210]
The logo looks like this before 

![image](https://github.com/HimanshuNarware/Devlabs/assets/115923314/9583ec01-6980-425b-be72-74ed810a6a48)

Now looking better

![image](https://github.com/HimanshuNarware/Devlabs/assets/115923314/76252305-0f20-4bb2-9e4d-e2b3c1c006a9)

**Comment by HimanshuNarware** [comment]
@AmitBiswas1402  don't raise PR before getting assigned

**Comment by AmitBiswas1402** [comment]
Do I have to wait until I get assigned?
Okay can you assign the issue to me now?

**Comment by HimanshuNarware** [comment]
@AmitBiswas1402  try to add relative icons ,

**Comment by AmitBiswas1402** [comment]
You mean black coured icon?

**Comment by Manav173** [comment]
Currently, the icons displayed in the footer, particularly the logo, seem to lack coherence in terms of color scheme. To create a more visually appealing and unified look, I propose monochrome all the footer icons, including the logo.
I would be really thankful if you assign me this issue as a part of GSSoC @HimanshuNarware .
