### ISSUE TITLE
[New Tool]: add ResumeNerd

### ISSUE THREAD

**Issue by ImmidiSivani** [HimanshuNarware/Devlabs#2104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Website to create resumes and get career advice

### Use Case

new resume addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ImmidiSivani ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
