### ISSUE TITLE
[New Tool]: Svelte

### ISSUE THREAD

**Issue by SOMNATH0904** [HimanshuNarware/Devlabs#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Svelte is a modern JavaScript framework for building user interfaces that stands out by shifting much of the work traditionally done in the browser to a compile step during the build process. Unlike frameworks such as React or Vue, which use a virtual DOM, Svelte compiles components into highly optimized imperative code that directly manipulates the DOM. This approach results in smaller, faster applications with significantly improved performance. By eliminating the virtual DOM and focusing on compiling to minimal JavaScript, Svelte offers a more efficient way to create dynamic web applications.

### Use Case

Some Use Cases are :
1. Single Page Applications (SPAs): Building fast and interactive web apps with minimal JavaScript.
2. Static Site Generation (SSG): Creating static websites with optimized performance.
3. Progressive Web Apps (PWAs): Developing web apps with offline capabilities and native-like experiences.
4. Component Libraries: Designing reusable UI components for various projects.
5. Dashboards and Data Visualization: Crafting performant and dynamic data-driven interfaces.
6. Embedded Widgets: Embedding interactive widgets into existing web pages or applications.
7. Small to Medium Projects: Ideal for projects where performance and simplicity are critical.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SOMNATH0904** [comment]
###Add Screenshot
<img width="197" alt="svelte" src="https://github.com/user-attachments/assets/75e22ff6-6441-4fc7-a9e9-066c5ccac768">

**Comment by panwar8279** [comment]
Already added.
