### ISSUE TITLE
Lacking dark mode in navbar

### ISSUE THREAD

**Issue by Sudhan22z265** [HimanshuNarware/Devlabs#213]
**Is your feature request related to a problem? Please describe.**
Users are experiencing discomfort due to the absence of a dark mode option in the navbar. 

**Describe the solution you'd like**
Implement a dark mode feature in the navbar to enhance user experience and provide visual relief, especially during low-light conditions.

**Describe alternatives you've considered**
1. Adding a toggle switch in the navbar to enable/disable dark mode.
2. Automatically switching to dark mode based on system settings or user preferences.
3. Providing a settings option where users can customize their preferred theme, including dark mode for the navbar.

**Additional context**
Consider providing customizable options for dark mode, such as different shades of dark backgrounds or accent colors, to cater to varying user preferences. Additionally, ensure that text and icons are appropriately contrasted for readability in dark mode.

### Please assign this to me. I am gssoc'24 contributor.

**Comment by devbeda** [comment]
I'm eager to contribute to your open-source project and would appreciate it if you could assign me the repository.
