### ISSUE TITLE
[Bug]: Backend tools link is not present in the footer .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Backend tools link is not present in the footer . Links to all the other pages such as AI,ethical hacking,frontend tools etc is present but not Backend Tools page.

### Expected behavior

I can add Backend Tools links in the footer , which on click opens the Backend tools page .

### Add ScreenShots

![Screenshot (819)](https://github.com/user-attachments/assets/f5bd5e3a-d188-4a57-b34c-13233cd8da2a)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@panwar8279 kindly consider this issue .

**Comment by panwar8279** [comment]
No need to add.
