### ISSUE TITLE
[New Tool]: Adding Sidekick

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Sidekick makes the Internet distraction-free. It speeds up your workflow and protects against attention killers

### Use Case

Sidekick makes the Internet distraction-free. It speeds up your workflow and protects against attention killers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Already added.
