### ISSUE TITLE
[New Tool]: PBS KIDS

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#2140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Educational games and videos from Curious George, Wild Kratts and other PBS KIDS shows!

### Use Case

![image](https://github.com/user-attachments/assets/b7cfbdf2-daba-4dc0-a37d-c954e364f1a0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Already added.
