### ISSUE TITLE
[New Tool]: Adding MIT OpenSource

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#2141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

MIT OpenCourseWare is an online publication of materials from over 2,500 MIT courses, freely sharing knowledge with learners and educators around the world.

### Use Case

it is the best plateform for learning

### Add ScreenShots

![image](https://github.com/user-attachments/assets/faf4526a-0081-403a-b722-cbd4bc7466a5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Already added.
