### ISSUE TITLE
Adding Testimonials

### ISSUE THREAD

**Issue by sharmi4590** [HimanshuNarware/Devlabs#2144]
Adding testimonials stating there experience with the project and all would make the website more interseting and enhance user experience . I would like to work on it and I will make sure to match it with your theme.

This is my previous work.
![Screenshot (457)](https://github.com/user-attachments/assets/94c9fd45-49e0-48b8-8674-769d8cdf22d3)
![Screenshot (458)](https://github.com/user-attachments/assets/7d6ea5fb-e8dc-4e59-a8bf-238f0ac8681a)
![Screenshot (459)](https://github.com/user-attachments/assets/3fae6120-c6b6-49f2-b95c-80a5819049bc)

**Comment by panwar8279** [comment]
Hi @sharmi4590 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
