### ISSUE TITLE
[Bug]: text not visible in booked card

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#2146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text is not visible in dark/light mode for booked card

### Expected behavior

It should be clearly visible

### Add ScreenShots

![Screenshot 2024-07-25 021407](https://github.com/user-attachments/assets/4f45ac88-483b-433c-b4b1-a1c4f5b5a2c7)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @root-0101 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
