### ISSUE TITLE
[New Tool]: Adding GitHub

### ISSUE THREAD

**Issue by thevijayshankersharma** [HimanshuNarware/Devlabs#2147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers.

### Use Case

You can host and review code, manage projects, and build software alongside millions of other developers.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @thevijayshankersharma ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
