### ISSUE TITLE
[New Tool]: Adding WordPress

### ISSUE THREAD

**Issue by thevijayshankersharma** [HimanshuNarware/Devlabs#2148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

WordPress is a free and open-source content management system (CMS) that powers millions of websites and blogs.

### Use Case

WordPress is a free and open-source content management system (CMS) that powers millions of websites and blogs.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @thevijayshankersharma ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
