### ISSUE TITLE
[New Tool]: Adding Jira

### ISSUE THREAD

**Issue by thevijayshankersharma** [HimanshuNarware/Devlabs#2149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Jira is a proprietary issue tracking product developed by Atlassian that allows bug tracking, issue tracking, and project management functions.

### Use Case

Jira is a proprietary issue tracking product developed by Atlassian that allows bug tracking, issue tracking, and project management functions.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @thevijayshankersharma ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
