### ISSUE TITLE
UI Enhancement + Responsive Fixes

### ISSUE THREAD

**Issue by aayushwrld** [HimanshuNarware/Devlabs#215]
**Describe the bug**

**Multiples Updates -**
- Navbar when clicked leaves yellow/blue colour in light/dark modes unless the user clicks somewhere else.
- In responsive, the website footer gets overlapped by the custom scrollbar.

**Expected behaviour**

- The colour should be retained to normal the original colour.
- The scrollbar should not overlap and should look cleaner.

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/142794224/f51d1529-5325-41db-a456-7cd3f687eba6)
<br/>
![image](https://github.com/HimanshuNarware/Devlabs/assets/142794224/6b6a4734-27e7-4832-9b4e-45e32a42a281)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [ ] Working under Kwoc*
- [ ] Working under Dwoc*
- [ ] Working under Swoc*

**Comment by aayushwrld** [comment]
Hey @HimanshuNarware! Would be great if you can assign me the issue so I can start working on it.

**Comment by aayushwrld** [comment]
Thank you @HimanshuNarware can you please label it under GSSOC'24?

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
