### ISSUE TITLE
[New Tool]: Adding Shopify

### ISSUE THREAD

**Issue by thevijayshankersharma** [HimanshuNarware/Devlabs#2150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Shopify is a commerce platform that allows anyone to set up an online store and sell their products. It powers over 1,700,000 businesses worldwide.

### Use Case

Shopify is a commerce platform that allows anyone to set up an online store and sell their products. It powers over 1,700,000 businesses worldwide.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @thevijayshankersharma ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
