### ISSUE TITLE
[New Tool]: Enhancv 

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Provides templates and customization options to highlight your strengths.

![image](https://github.com/user-attachments/assets/c67b102c-c62d-4bf5-8718-8016d7b37a15)

### Use Case

Enhancv provides templates and customization options to highlight your strengths by tailoring sections like skills, achievements, and personal projects. It helps you create a unique, visually appealing resume that emphasizes your unique qualifications and experiences.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
