### ISSUE TITLE
[New Tool]: added Resume-Now

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

![image](https://github.com/user-attachments/assets/18269caf-d47d-4286-b16f-f23aca91f94f)

An easy-to-use resume builder with tips and templates.

### Use Case

MyPerfectResume is an easy-to-use resume builder that offers templates and expert tips to guide you through creating a professional resume. It simplifies the process, making it accessible even for those with little experience in resume writing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
