### ISSUE TITLE
[New Tool]: Added Hloom

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

![image](https://github.com/user-attachments/assets/4d710f55-18f9-48d9-90fd-dd8fe9627334)

Provides free resume templates in various styles and formats.

### Use Case

Hloom offers a wide range of free resume templates in various styles and formats, suitable for different industries and job levels. This allows job seekers to choose a template that best fits their profession and personal brand, making it easier to create a polished and professional-looking resume.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
