### ISSUE TITLE
[New Tool]: Added CakeResume

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

![image](https://github.com/user-attachments/assets/624d9250-f196-4833-b7a1-195dfc9a8cd9)

A resume builder with a drag-and-drop interface and customization options.

### Use Case

CakeResume provides a drag-and-drop interface and extensive customization options, enabling users to easily add, rearrange, and format sections. This makes it ideal for creating unique and visually appealing resumes tailored to specific job applications or personal branding.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
