### ISSUE TITLE
[New Tool]: Standard Resume

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

![image](https://github.com/user-attachments/assets/05637f85-1c37-493f-97a7-79a32885590c)
A simple and clean resume builder with easy sharing options.

### Use Case

Standard Resume offers a simple and clean resume builder with easy sharing options, allowing users to quickly create a professional-looking resume. It provides a link to share your resume online or download it in multiple formats, making it convenient for job applications and networking.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
