### ISSUE TITLE
[New Tool]: Added ResumUP

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

![Uploading image.png…]()
Offers creative resume templates and visualization options.

### Use Case

Offers creative resume templates and visualization options.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
