### ISSUE TITLE
[New Tool]: Add Git

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I want to add git 
Git is different from GitHub 
So I want to add Git, to make students know about git commands

@HimanshuNarware, could you please assign me this issue under GSSOC'24

### Use Case

Knowledge on git commands is necessary

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sreevidya-16** [comment]
@HimanshuNarware, could you please assign me this issue under GSSOC'24

**Comment by panwar8279** [comment]
@sreevidya-16 , start working on it.

**Comment by sreevidya-16** [comment]
@panwar8279, please merge this PR

**Comment by sreevidya-16** [comment]
@panwar8279, may I please know any update on this PR ? 
It's been 3 days...so kindly have a look into this PR @panwar8279 mam

**Comment by sreevidya-16** [comment]
@panwar8279, view the raised PR and let me know if any changes are required, or else kindly merge it mam
