### ISSUE TITLE
[New Tool]: Add Visual Studio Code

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I want to add VS Code 

### Use Case

VS code has many extensions, that make students to understand and learn the code easily.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

@HimanshuNarware, could you please assign me this issue

**Comment by sreevidya-16** [comment]
@HimanshuNarware, could you please assign me this issue under GSSOC'24

**Comment by panwar8279** [comment]
Hi @sreevidya-16 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
