### ISSUE TITLE
[New Tool]: Add knowledge hut

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#2160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

https://www.knowledgehut.com/blog/web-development/software-engineer-tools

### Use Case

https://www.knowledgehut.com/blog/web-development/software-engineer-tools

### Add ScreenShots

![image](https://github.com/user-attachments/assets/68bcf1dc-6fef-4b37-9d03-867d837a2c17)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
