### ISSUE TITLE
[New Tool]: Add Code Triage

### ISSUE THREAD

**Issue by Ajita369** [HimanshuNarware/Devlabs#2161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A site that helps you find open-source projects to contribute to by delivering issues directly to your inbox.

### Use Case

This tool is useful resource for developers . 

### Benefits

This will help people find open source projects to collaborate on.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1fd4b12f-5d82-41d9-bea2-832114bbc169)
![image](https://github.com/user-attachments/assets/4e70242f-9ea0-4d16-bfa5-7b79f178ae61)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ajita369 ,  I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
