### ISSUE TITLE
[New Tool]: Codepen

### ISSUE THREAD

**Issue by divyansh-2005** [HimanshuNarware/Devlabs#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

CodePen is a social development environment. At its heart, it allows you to write code in the browser, and see the results of it as you build. A useful and liberating online code editor for developers of any skill, and particularly empowering for people learning to code. We focus primarily on front-end languages like HTML, CSS, JavaScript, and preprocessing syntaxes that turn into those things.

### Use Case

Unlike traditional text editor software, CodePen provides a browser-based, SAAS solution for front-end web designers. For new developers, it also acts as an amazing learning tool so you can catch your mistakes early in an interactive environment

### Benefits

CodePen Features
Code Development.
Code Editing.
Debugging.
Deployment Management.
For Developers.
Graphical User Interface.
Website Development.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f7470a61-5f01-49e2-9269-eb499bfd5a89)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @divyansh-2005 , I have assigned this task to you. Kindly complete within 2 days and also add a demo video of 30sec. Good luck!
