### ISSUE TITLE
Changing the navbar 

### ISSUE THREAD

**Issue by BagchiShreya** [HimanshuNarware/Devlabs#217]
**Is your feature request related to a problem? Please describe.**

The navbar seems to have a positional problem among the elements. It is a bit difficult as a 3rd party user to not be able to see the search in the middle having a large portion to itself and instead have the lesser needed options in the middle.

**Describe the solution you'd like**

I would like to bring the search bar in the middle, make it large and move the elements in the middle to the right hand side. This would be a better layout for the users to find what they need.

** Add screenshot 

![navbar](https://github.com/HimanshuNarware/Devlabs/assets/106909868/d54891aa-cbe0-41d3-8131-d15ac61765f7)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by BagchiShreya** [comment]
Hi @HimanshuNarware 
I would like to work on this issue. Hope you assign this issue to me

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@HimanshuNarware Sir, I would really like to work on this issue, so please assign it to me.

**Comment by HimanshuNarware** [comment]
@cpratik1307  but first show demo

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by cpratik1307** [comment]
> @cpratik1307 but first show demo

Absolutely, sir, I will provide you with a demo as soon as possible.
I am grateful that @HimanshuNarware Sir gave me this opportunity.

**Comment by Mohammad-Qamar** [comment]
I would like to work on this issue. Hope you assign this issue to me 
Thankyou

**Comment by drick-infinity** [comment]
As  I learned MERN stack development I easily created nresponsive navbar can you assign this issue to me I make a better ui for navbar

**Comment by pahuja-sahil** [comment]
hi @HimanshuNarware . I would like to work on this issue under GSSoC'24. I heave already built a blogging website whose github link is given below.
link - https://github.com/pahuja-sahil/Online-Blogging-System
I can made responsive navbar efficiently and easily matching the color pallete of you site. Hence i kindly ask you to assign this issue to me.
Thank you.

**Comment by Yuvraj960** [comment]
@HimanshuNarware Please assign this issue to me under GSSoC24

**Comment by sakshi261203** [comment]
Hi Himanshu Narware , Could you please assign this task to me...
