### ISSUE TITLE
[Bug]: CSS of Contribbbution Page in mobile view 

### ISSUE THREAD

**Issue by dhairyagothi** [HimanshuNarware/Devlabs#2171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CSS of contributor page is not responsive

### Expected behavior

making contributions page responsive

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dhairyagothi** [comment]
@panwar8279 please assign

**Comment by dhairyagothi** [comment]
@panwar8279 please assigne me

**Comment by panwar8279** [comment]
Hi @dhairyagothi , Start working on it.
