### ISSUE TITLE
[New Tool]: add BigThink

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Courses and lessons from top thinkers and doers in various fields.

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AmruthaPariprolu , Please raise single issue for adding multiple tools. It's time consuming to assign issue one by one.  I am assigning  this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
