### ISSUE TITLE
Adding shadows to the buttons on hover.

### ISSUE THREAD

**Issue by Rakshit-gen** [HimanshuNarware/Devlabs#219]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when the buttons don't have shadows on hovering over them.

**Describe the solution you'd like**
Buttons hover when we move the cursor on them.

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Suvam3456** [comment]
Please assign me this issue @HimanshuNarware under GSSOC'24

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me @HimanshuNarware
