### ISSUE TITLE
Feat: Show a message for empty search result

### ISSUE THREAD

**Issue by AshutoshDash1999** [HimanshuNarware/Devlabs#220]
**Is your feature request related to a problem? Please describe.**
Currently, there is no message, in case user searches for something and it is not present.

**Describe the solution you'd like**
Show a message in case of empty search result like, "There's nothing to show"

**Add screenshot**
![screenshot of app without any message for empty results](https://github.com/HimanshuNarware/Devlabs/assets/46455250/1de08031-c3ee-4b03-871d-4c70f47a94ec)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by ayushnegi007** [comment]
hi @HimanshuNarware  please assign me this issue

**Comment by AshutoshDash1999** [comment]
@HimanshuNarware please review this PR

https://github.com/HimanshuNarware/Devlabs/pull/286
