### ISSUE TITLE
[New Tool]:  Add Code.org Studio

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [HimanshuNarware/Devlabs#2208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

N/A

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ishitamukherjee2004 ,  I am assigning  this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
