### ISSUE TITLE
[New Tool]:  Add Class Central

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [HimanshuNarware/Devlabs#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Course of c programming

### Use Case

Course of c programming

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Tool already present in the database.
