### ISSUE TITLE
Backend Functionality Enhancement with Signup/Login Functionality

### ISSUE THREAD

**Issue by rikhiltaneja** [HimanshuNarware/Devlabs#222]
**Is your feature request related to a problem? Please describe.**
Currently, the project lacks a proper backend server which will restrict the development of many new features in the future. Also, some pre-defined features of the project like Bookmarks, etc. are not functional because of the lack of proper server and Database setup. Other than this, users of the website will not be able to personalise their user experience without the functionality of basic authentication (signup/login).

**Describe the solution you'd like**
To solve the issue described above, the backend server should be properly developed making it completely ready for API calls from the frontend part of the website.

The project currently does not have a backend server and a connect DB. So, I will setup both the things and make them ready to be connect with the frontend part of this project. I will also **deploy the server** to make it production ready. 
Other than the basic setup, I will also develop the **complete login/signup** functionality (backend). It will include all necessary things like **schema**(s), **validation** files + **middlewares**, **error handling**, **JWTs**, **profile customization**, etc.

_{By basic backend setup I mean, necessary things like Express App, Mongoose & MongoDB, Custom Error Class, Error Handling Middlewars, etc. will be developed}_

## Tech libraries/frameworks which I will use to accomplish the above mentioned task(s):
- ExpressJS
- NodeJS
- JWT
- MongoDB
- Mongoose
- Vercel

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/142862928/3a92e19e-34ea-4a8a-b8c3-b307cf907283)
To make features like these actually functional, proper backend functionality is necessary.

@HimanshuNarware Please assign me this issue (under GSSOC'24). I will do my best to accomplish all the tasks mentioned above.
Looking forward to a positive response! 🙂

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under GSSOC'24

**Comment by HimanshuNarware** [comment]
@rikhiltaneja  someone is already working on this issue.

**Comment by rikhiltaneja** [comment]
@HimanshuNarware I can't find any other issue related to this. Can you please specify the issue which is tackling this?

**Comment by rikhiltaneja** [comment]
Thanks for assigning this issue to me @HimanshuNarware.
I will make sure that I give my best to solve the issue. 😄 

Please assign the GSSOC label as well to this issue.
