### ISSUE TITLE
[New Tool]:  Add Pangians for Remote Jobs

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#2227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Before the world separated into countries and continents, there was only one world, PANGEA and we believe every human being is a Pangian, a global citizen of that world.

### Use Case

For finding remote jobs

### Add ScreenShots

![image](https://github.com/user-attachments/assets/efda154a-11d2-4a62-b78a-e28eaacdc8a3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 can you assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love ,  I am assigning  this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
