### ISSUE TITLE
[New Tool]: Addign "jobspresso" Remote Jobs

### ISSUE THREAD

**Issue by Maheshwari-Love** [HimanshuNarware/Devlabs#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Jobspresso is the easiest way to find high-quality remote jobs in tech, marketing, customer support and more. 100% of our jobs are hand-picked, manually reviewed and expertly curated.

### Use Case

for remote jobs 

### Add ScreenShots

![Uploading image.png…]()

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Maheshwari-Love** [comment]
@panwar8279 can you assign me this task

**Comment by panwar8279** [comment]
Hi @Maheshwari-Love , I am assigning  this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
