### ISSUE TITLE
[New Tool]: Adding celestial

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Celestial is an Open world Space survival game playing on a Spherical world of roughly 700km2

### Use Case

Celestial is an Open world Space survival game playing on a Spherical world of roughly 700km2

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 ,  I am assigning  this task to you. Kindly complete within 2 days and also add 30 sec demo video. Good luck!
