### ISSUE TITLE
[New Tool]: Adding OpSo

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

OpSo provides information about various open-source programs like GSoC, Summer of Bitcoin, etc.

### Use Case

OpSo provides information about various open-source programs like GSoC, Summer of Bitcoin, etc.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
