### ISSUE TITLE
[New Tool]: Adding SatNOGS-Visualization-Tool	

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

to show information from satellites and ground stations using the SatNOGS database and API.

### Use Case

to show information from satellites and ground stations using the SatNOGS database and API.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
