### ISSUE TITLE
[New Tool]: Adding Obtainium

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Get Android app updates straight from the source.

### Use Case

Get Android app updates straight from the source.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
