### ISSUE TITLE
[Feature Request]: Page scroll to top at pagination

### ISSUE THREAD

**Issue by DevGajjar28** [HimanshuNarware/Devlabs#2247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

so currently we do change pages and show the content of next page but it do not scroll to top of content to show all data from the top.

### Use Case

If user click on next page than it scroll to top and show all the content from the start.

### Benefits

It enhance the user experience, user can explore all the content of page.

### Add ScreenShots

https://drive.google.com/file/d/1twCw-hOI05tvuR57H7A-g7H5Ai6S4wRu/view?usp=sharing

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @DevGajjar28 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
