### ISSUE TITLE
Add icons in navbar

### ISSUE THREAD

**Issue by mansi1309** [HimanshuNarware/Devlabs#225]
**Is your feature request related to a problem? Please describe.**
I would like to add new feature in navbar.

**Describe the solution you'd like**
I would like to add icons in navbar heading such as home, bookmark, open source, about us.

Please assign this issue to me.

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/133951716/c1459deb-231d-40fd-b375-4af8011644e0)

Checklist
Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc'24

**Comment by motuncoded** [comment]
Helo, I am currently a GSSOC contributor, kindly assign the code to me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me

**Comment by devbeda** [comment]
I'm eager to contribute to your open-source project and would appreciate it if you could assign me the repository.

**Comment by abhinavashish15** [comment]
I want to work on this. @HimanshuNarware kindly assign it to me.

**Comment by BagchiShreya** [comment]
Hi @HimanshuNarware I am eager to work on this issue and enhance the website. It would be great if you assign me this issue.

**Comment by singhpratibha98** [comment]
Upon using the platform, I noticed that while the navbar effectively navigates users, the addition of icons can significantly improve visual appeal and user experience. With my background in front-end development  I am eager to take on this task and contribute to making the platform more intuitive and aesthetically pleasing. I kindly request your consideration in assigning me this task.

**Comment by paramveer-bit** [comment]
Kindly assign this to me under GSSOC'24

**Comment by Dilpreet0501** [comment]
Hello @HimanshuNarware , I would like to add icons in Navbar.
Kindly assign this issue to me under GSSoC'24, I'll do my best!

![Screenshot 2024-05-12 032047](https://github.com/HimanshuNarware/Devlabs/assets/100590445/9f335902-eb5f-45ea-bb0c-b6c8d0c3f7aa)

Checklist
Example Fill x { [x] } into bracket

[ ] I have checked the existing issues *
[ ]  I have read the Contributing Guidelines *
[ ]  I have starred the repository *
 [ ]  Working under Gssoc'24

**Comment by Ayusha-a07** [comment]
i want to contribute on this project.could you please assign me this under GSSoC'24.

**Comment by maniranjan2023** [comment]
Kindly assign this to me under GSSOC'24
