### ISSUE TITLE
UI Fixing in Card Layout

### ISSUE THREAD

**Issue by Che140401** [HimanshuNarware/Devlabs#226]
**Describe the bug**
The bug is the inconsistency in button placement within cards. Some buttons appear at the top of the card, while others appear at the bottom, resulting in a lack of standardization and potentially confusing user experience.

![Card Layout Fix](https://github.com/HimanshuNarware/Devlabs/assets/109230049/890f5ece-effa-4154-a9c4-fac1c5c888b0)

**Expected behavior**
I expected all buttons within the cards to be consistently positioned either at the  bottom, ensuring a uniform layout and user experience across the interface.

**Screenshots**
Here is the solution,
![Screenshot 2024-05-11 085214](https://github.com/HimanshuNarware/Devlabs/assets/109230049/e3a6f68f-dd95-4eba-86d6-25e372f04bb7)

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Che140401** [comment]
@HimanshuNarware 

Please assign issue me i would do asap,

Regards,
Name:Chetan Karande,
Experience:1.4 years in front-end.

**Comment by Archita112** [comment]
@HimanshuNarware, sir please do assign me the issue. I have worked with react earlier and would definetely fix this issue.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributer. I would like to work on this issue. so, I kindly request you to assign this to me.

**Comment by krishna-singha** [comment]
Please assign to me as I have already worked with react.js so I can resolve this issue.
