### ISSUE TITLE
[New Tool]: Add random

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#2260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 RANDOM.ORG offers true random numbers to anyone on the Internet. The randomness comes from atmospheric noise, which for many purposes is better than the pseudo-random number algorithms typically used in computer programs.

### Use Case

 RANDOM.ORG offers true random numbers to anyone on the Internet. The randomness comes from atmospheric noise, which for many purposes is better than the pseudo-random number algorithms typically used in computer programs.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a0d83a3e-68ea-4dc4-bd7a-49b8d29cc7c6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@chaanakyaaM ,  if you want to add multiple tools so raised only single issue and add multiple tools in that. Assigning issue one by one is time consuming.

**Comment by chaanakyaaM** [comment]
okay
