### ISSUE TITLE
[New Tool]: Adding Winstall

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 A web app for browsing Windows Package Manager apps, and create a batch-installation command using an intuitive interface. 

### Use Case

 A web app for browsing Windows Package Manager apps, and create a batch-installation command using an intuitive interface. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@Unnimaya6122004 , if you want to add multiple tools so raised only single issue and add multiple tools in that. Assigning issues one by one is time consuming.

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
