### ISSUE TITLE
[New Tool]: Adding Keyviz

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 Keyviz is a free and open-source software to visualize your ⌨️ keystrokes in real time!

### Use Case

 Keyviz is a free and open-source software to visualize your ⌨️ keystrokes in real time!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
