### ISSUE TITLE
[New Tool]: Adding Uni App

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Apply for the first time to college or transfer to finish your degree .
With Uni App, you can manage the whole college application
process.

### Use Case

Apply for the first time to college or transfer to finish your degree .
With Uni App, you can manage the whole college application
process.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!

**Comment by Unnimaya6122004** [comment]
Sir does this deserve level 2 label
