### ISSUE TITLE
[New Tool]: Adding ElectrifAi

### ISSUE THREAD

**Issue by Unnimaya6122004** [HimanshuNarware/Devlabs#2287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 our focus is on solving the business problem for the C-Suite. 

### Use Case

 our focus is on solving the business problem for the C-Suite. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Unnimaya6122004 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
