### ISSUE TITLE
[Feature Request]:  Add hover effect on social media Icons

### ISSUE THREAD

**Issue by Harshsaini001** [HimanshuNarware/Devlabs#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhance user interaction and improve the visual appeal of social media icons by implementing a hover effect that provides a dynamic and engaging user experience.

### Use Case

Enhance user engagement and improve the visual appeal of social media icons by implementing smooth hover effects such as scaling, color changes, or shadows. This leads to increased interaction with social media links and a more polished, modern website design.

### Add ScreenShots

![Screenshot 2024-07-27 101700](https://github.com/user-attachments/assets/160bd685-2821-49f1-989e-ee6082c89c32)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Harshsaini001** [comment]
Hey @HimanshuNarware , I want to resolve this issue . Please assign me this issue under GSSOC and add GSSOC labels.

**Comment by panwar8279** [comment]
Hi @Harshsaini001 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
