### ISSUE TITLE
Fix Mobile View of Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to fix Mobile View of Footer
Can you assign me this issue under GSSOC'24 @panwar8279

### Use Case

![IMG_20240727_122457](https://github.com/user-attachments/assets/382e2a67-951b-4cee-8c77-f9852935e86c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , i am assigning this task to you.  kindly complete within 2 days. Good luck!
