### ISSUE TITLE
[New Tool]: Add Pencil Project 

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

An open-source tool for creating wireframes and prototypes.

![image](https://github.com/user-attachments/assets/8fc57fd5-2566-4943-94dd-8fabdc744d48)

### Use Case

Create wireframes and prototypes for web and mobile interfaces; supports exporting to various formats.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
