### ISSUE TITLE
Search on key press

### ISSUE THREAD

**Issue by siddxharth1** [HimanshuNarware/Devlabs#230]
I would like to add a search feature. User will get the result when he type they don't have to click the search button every time and we can add advance feature like debouncing which will reduce the fetch api calls. By this we can improve the user experience
can you assign this issue to me

**Comment by Mr-mahato** [comment]
I'm interested in working on the open issue regarding the the search functionality when a user keypress on the search input. I have experience with Node.js, Express, MongoDB, and JWT token handling , react , which aligns well with the project's requirements.

I've reviewed the issue's description and requirements and feel confident that I can deliver a robust and secure authentication solution. I understand the need for proper error handling and am ready to address those aspects.

To solve this issue:
1) i will do simple check there that if the user input key is present in the data that i have fetched from the backend is present then i will render that data only and if not then all the datas will be shown to the user screen.

**Comment by siddxharth1** [comment]
@Mr-mahato I have already raise this issue and asked him to assign this task to me. You may work on another problem.
