### ISSUE TITLE
[New Tool]: Add Lunacy

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A free design software with built-in assets and features, similar to Sketch but available for Windows.

![image](https://github.com/user-attachments/assets/94150e10-1e77-4c68-8284-8f029b27e6a9)

### Use Case

Design UI/UX with built-in assets, and collaborate on Windows; offers similar features to Sketch.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
