### ISSUE TITLE
[New Tool]: Add Penpot 

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

An open-source design and prototyping platform for cross-functional teams.

![image](https://github.com/user-attachments/assets/44f89cab-b0d3-4d0a-82f8-d7bc427480b1)

### Use Case

Design and prototype collaboratively in the browser, supporting designers and developers with open-source flexibility.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
