### ISSUE TITLE
[New Tool]: Add Origami Studio

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 A free design tool created by Facebook for designing interactive interfaces.
 
 
![image](https://github.com/user-attachments/assets/65fa5d06-7853-418b-af3b-d3e3592a5f50)

### Use Case

Design interactive interfaces and prototypes with complex animations; ideal for high-fidelity prototypes.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
