### ISSUE TITLE
[New Tool]: Add Mockplus

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A design and prototyping tool with a free version, suitable for UI/UX designers.

![image](https://github.com/user-attachments/assets/fc80d808-5efa-4da4-b594-b9b3c8308567)

### Use Case

Rapidly design and prototype UI/UX interfaces; offers a wide range of pre-designed components.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
