### ISSUE TITLE
[New Tool]: Add Marvel

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A design, prototyping, and collaboration tool with a free plan.

![image](https://github.com/user-attachments/assets/233287c8-7d22-42f0-a84a-48a0bb851020)

### Use Case

Design and prototype interfaces, and collaborate with teams; supports real-time feedback and iteration.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
@heli0707 , if you want to add multiple tools so you have to raised single issue and add multiple tools in that. Assigning multiple tools one by one is time consuming.

**Comment by heli0707** [comment]
Okay

**Comment by heli0707** [comment]
I raised a single issue and added multiple tools to that. can I create PR for each tool?Sent from Mail for Windows From: Pratigya PanwarSent: 28 July 2024 05:45To: HimanshuNarware/DevlabsCc: Heli Detroja; MentionSubject: Re: [HimanshuNarware/Devlabs] [New Tool]: Add Marvel (Issue ***@***.*** , if you want to add multiple tools so you have to raised single issue and add multiple tools in that. Assigning multiple tools one by one is time consuming.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by panwar8279** [comment]
Hi @heli0707 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
