### ISSUE TITLE
[New Tool]: Add Axure RP

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A wireframing, prototyping, and documentation software with a free version.

![image](https://github.com/user-attachments/assets/cfef45a7-f51e-423c-94c8-34797898cf16)

### Use Case

Wireframe and prototype complex interfaces, with detailed documentation and flow diagrams.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
