### ISSUE TITLE
[New Tool]: Add Balsamiq

### ISSUE THREAD

**Issue by heli0707** [HimanshuNarware/Devlabs#2308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A low-fidelity wireframing tool with a free trial, great for quick mockups.

![image](https://github.com/user-attachments/assets/b6ddaedd-690f-4728-8713-37f871e0c2f9)

### Use Case

Quickly create low-fidelity wireframes for brainstorming and planning; ideal for initial design stages.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @heli0707 , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
