### ISSUE TITLE
Adding respective icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [HimanshuNarware/Devlabs#231]
Could you plz assign me this issue under GSSOC'24

Is your feature request related to a problem? Please describe.

The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.

Describe the solution you'd like

I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

** Add screenshot 
![Screenshot 2024-05-11 080754](https://github.com/HimanshuNarware/Devlabs/assets/115486960/7c82eee5-11ae-46c2-bf21-4896bc958790)

Checklist
Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [ x] Working under Gssoc'24

**Comment by BagchiShreya** [comment]
Hi @HimanshuNarware I would like to work on this issue. It would be great if you allow me to work on this issue and assign it to me.

**Comment by KartikeySingh05** [comment]
hi @HimanshuNarware i would like to work on this issue please allow me to work on this issue.

**Comment by HimanshuNarware** [comment]
@harshmishra19   already someone is working on this issue.
