### ISSUE TITLE
[New Tool]: Add Eden Ai

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [HimanshuNarware/Devlabs#2321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A variety of AI APIs, including those for text-to-speech, language detection, sentiment analysis, face recognition, question answering, data anonymization, and other technologies, are available on Eden AI's platform.

### Use Case

The Eden AI platform offers a variety of technologies, including text-to-speech, language detection, sentiment analysis, face recognition, question answering, and data anonymization.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
@panwar8279 Please assign me this issue

**Comment by panwar8279** [comment]
Hi @Vaibhav-kesarwani , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
