### ISSUE TITLE
[New Tool]: Add intelli j idea

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [HimanshuNarware/Devlabs#2327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

The Leading Java and Kotlin IDE

### Use Case

The Leading Java and Kotlin IDE

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @DharshiBalasubramaniyam , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
