### ISSUE TITLE
Modify contributors card

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#2329]
As the contributor's image layout is not well designed, it should be as per the founder card

![Screenshot 2024-07-27 180601](https://github.com/user-attachments/assets/d19c9bd5-ac58-4b42-857c-cf8a2c320eb1)

![Screenshot 2024-07-27 180524](https://github.com/user-attachments/assets/f458906a-406d-405f-b68d-e00fda5b7573)

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete this task within 2 days and also add 30 sec demo video. Good Luck!
