### ISSUE TITLE
[New Tool]: Add Aceternity UI

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [HimanshuNarware/Devlabs#2338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Acernity UI can be employed in various contexts to improve user experience and streamline workflows. In healthcare management systems, it can manage patient records, ensuring easy access to medical history, test results, and treatment plans, while also facilitating seamless appointment scheduling and providing healthcare professionals with dashboards to display key metrics such as patient statistics, appointment trends, and treatment outcomes. In e-commerce platforms, Acernity UI can create a visually appealing product catalog, allowing users to filter, search, and compare products effortlessly. It can also enhance the checkout process, making it more intuitive and user-friendly.

### Use Case

1. Easy to use
2. Easy to Customize 
3. Make the inbuilt functions
4. Have many UI components
5. Direct copy & past Component are present

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
@panwar8279 Please assign this issue to me

**Comment by Vaibhav-kesarwani** [comment]
@panwar8279 Please assign this issue to me

**Comment by panwar8279** [comment]
Hi @Vaibhav-kesarwani , i am assigning this task to you.  kindly complete within 2 days. Good luck!
