### ISSUE TITLE
Improve the UI of Review Page form

### ISSUE THREAD

**Issue by Monika-1082005** [HimanshuNarware/Devlabs#234]
**Is your feature request related to a problem? Please describe.**
The problem is that currently existing review page form Ui is not good from users perspective and it doesn't resonate a website for devs considering the color scheme. I wish to improve that.

**Describe the solution you'd like**
The overall color scheme of the form could be improved a lot for both light and dark mode.

**Add screenshot** 
![image](https://github.com/HimanshuNarware/Devlabs/assets/134940879/011768bd-58ed-417e-a325-a4143c23c8b7)
![image](https://github.com/HimanshuNarware/Devlabs/assets/134940879/8a701e5b-4f21-4a76-bbff-3a71467d5431)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by HimanshuNarware** [comment]
@Monika-1082005  also do one thing if you can also find the bug in the logic of the review section, it's not working

**Comment by Monika-1082005** [comment]
> @Monika-1082005 also do one thing if you can also find the bug in the logic of the review section, it's not working

Sure! Will definitely try to solve that👍🏻
