### ISSUE TITLE
[New Tool]: Add BitBucket

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A Git repository management solution designed for professional teams. It integrates with Jira, a popular issue and project tracking tool.

@HimanshuNarware, @panwar8279, assign me this issue under GSSOC'24

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sreevidya-16** [comment]
@panwar8279, could you please assign me this issue under GSSOC'24

**Comment by panwar8279** [comment]
Hi @sreevidya-16 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
