### ISSUE TITLE
[New Tool]: Add Sublime Text

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A sophisticated text editor for code, markup, and prose. It's known for its speed and customizable features.

@panwar8279, @HimanshuNarware, assign me this Issue

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sreevidya-16 , i am assigning this task to you.  kindly complete within 2 days. Good luck!

**Comment by sreevidya-16** [comment]
@panwar8279, view this PR and let me know if you require any changes 
Otherwise, kindly merge into main
