### ISSUE TITLE
[New Tool]: Add Eclipse

### ISSUE THREAD

**Issue by sreevidya-16** [HimanshuNarware/Devlabs#2344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

An open-source IDE primarily used for Java development, but can be extended to support other languages via plugins.

I want to add eclipse to coding section.

@HimanshuNarware, @panwar8279, assign me this issue under GSSOC'24

### Use Case

An open-source IDE primarily used for Java development, but can be extended to support other languages via plugins.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sreevidya-16** [comment]
@panwar8279, could you please assign me this issue under GSSOC'24

**Comment by panwar8279** [comment]
Hi @sreevidya-16 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
