### ISSUE TITLE
Sidebar overlaps the the book marks added at first position of each row

### ISSUE THREAD

**Issue by Jithendranath8** [HimanshuNarware/Devlabs#235]
<img width="1433" alt="Screenshot 2024-05-11 at 4 51 27 PM" src="https://github.com/HimanshuNarware/Devlabs/assets/145124590/e875c790-08f3-4ee8-96c5-9b114af3c569">

Bookmarks positioned at the start of each row are obscured by the sidebar, hampering user navigation. This overlap diminishes both usability and aesthetic appeal. Adjusting the sidebar's placement can swiftly resolve this issue, enhancing the interface's functionality and visual coherence.

**Comment by Jithendranath8** [comment]
Please assign this issue , I can solve this

**Comment by HimanshuNarware** [comment]
@Jithendranath8  show me demo video

**Comment by Jithendranath8** [comment]
Sure @HimanshuNarware , here is it .

https://github.com/HimanshuNarware/Devlabs/assets/145124590/1b5f8bf2-a40a-450e-9b22-f956d994f70c

**Comment by HimanshuNarware** [comment]
@Jithendranath8 first show me demo

**Comment by Jithendranath8** [comment]
> @Jithendranath8 first show me demo

I didn’t get it . U mean after solving its demo video ?
