### ISSUE TITLE
[UI] Improving the footer UI

### ISSUE THREAD

**Issue by TanyaSingh103** [HimanshuNarware/Devlabs#236]
Problem:
The current UI design is slightly inconsistent in alignment and colors
![image](https://github.com/HimanshuNarware/Devlabs/assets/140062413/8f6ab46b-3155-43c8-bba5-45fd28efb4e0)
![image](https://github.com/HimanshuNarware/Devlabs/assets/140062413/765ec9ac-25de-4db4-94c0-6cda491a8520)

there are two different shades in the background if observed closely and the overall look is not very appealing

Solution:
I's like to improve the overall arrangement of the footer's components and make the background color consistent to make it more visually appealing. 

Kindly assign this issue to me.

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Priyantar-Jonak** [comment]
I would really love to work on the footer section to make it as convenient and aesthetically pleasing as possible.

I would request you to kindly consider to assign this issue to me.

I have-
checked the existing issues
read the Contributing Guidelines 
starred the repository
started working under GSSOC'24

**Comment by Raksha-Vats** [comment]
@HimanshuNarware please assign this issue to me under GSSOC 24
