### ISSUE TITLE
[Feature Request]: Want To Add New Frontend Tool Three.js 

### ISSUE THREAD

**Issue by nishant0708** [HimanshuNarware/Devlabs#2385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to Add new Tool Three.js

### Use Case

It Will be Good For User If He Could get all information in one place

### Add ScreenShots

![image](https://github.com/user-attachments/assets/22ba3732-fcd0-4fc0-be71-53825e08a73e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @nishant0708 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
