### ISSUE TITLE
Adding a contact us page

### ISSUE THREAD

**Issue by Manishar55** [HimanshuNarware/Devlabs#239]
Hii @HimanshuNarware, I want  to add a  contact us page in the nav bar
Adding a contact us page  makes it easy for visitors to reach out to you. People might have questions, feedback, or want to connect, and having a clear way to do that can improve their experience on your site.

![Screenshot 2024-05-11 231944](https://github.com/HimanshuNarware/Devlabs/assets/154615478/fa340fa9-ea07-4ea3-ba21-ae57b6d2ff4c)

kindly assign this issue to me under gssoc24, I will do my best!

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by Dilpreet0501** [comment]
Hello @HimanshuNarware , I would like to add contact us page in navbar as well as I would like to like it to the contact us mentioned in the footer.
kindly assign this issue to me under gssoc24, I will do my best!
![Screenshot 2024-05-12 032047](https://github.com/HimanshuNarware/Devlabs/assets/100590445/4eebc214-988c-4be3-8509-75fb438f8fb1)
![Screenshot 2024-05-12 031934](https://github.com/HimanshuNarware/Devlabs/assets/100590445/4552708f-958d-4b7d-9d78-82a3635ab124)

Checklist
Example Fill x { [x] } into bracket

 

- [ ] I have checked the existing issues *
- [ ] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [ ] Working under Gssoc'24*

**Comment by HimanshuNarware** [comment]
@Manishar55  share  a demo

**Comment by Manishar55** [comment]
> @Manishar55 share a demo

Sure @HimanshuNarware  Sir
![Screenshot 2024-05-12 144302](https://github.com/HimanshuNarware/Devlabs/assets/154615478/13e771ab-aca6-4ac3-bcd5-1bb71a9c77ea)

Like this I will add a contact us page in navbar
![Screenshot 2024-05-12 144914](https://github.com/HimanshuNarware/Devlabs/assets/154615478/26a68646-fced-45f0-92a5-0933b027065e)

This is a demo of contact us page, but i will definitely change the color and font style accordingly
Please assign this task to me

**Comment by shendgeshraddha** [comment]
![Screenshot 2024-05-12 203021](https://github.com/HimanshuNarware/Devlabs/assets/129361612/816ce939-6e28-4b58-ad66-25b72714c019)
Could you please assign me this issue??

**Comment by AnitSarkar123** [comment]
i also want to work on that issue
my screenshort
![contact us page](https://github.com/HimanshuNarware/Devlabs/assets/135215478/15a6f3bf-5d02-4f8e-813f-fbdf59b6beac)
also implement the faciality to automatically sent message to the owner's email when the user is submitted the message 
and the page is responsive

**Comment by AnitSarkar123** [comment]
i also change the colour to match the website colour ...please give it level 3 because i impliment responsiveness as well as email receiving funtionallity

**Comment by drick-infinity** [comment]
can you assign this issue to me
![Screenshot (41)](https://github.com/HimanshuNarware/Devlabs/assets/116994649/837c22bd-80f9-4e18-8682-c38c2003a68f)
![Screenshot (39)](https://github.com/HimanshuNarware/Devlabs/assets/116994649/eac452ee-5e3f-439c-8b94-b704accbe355)

**Comment by shwetamishra4** [comment]
Hello.. @HimanshuNarware please assign issue #239 to me , I can add CONTACT US Page to this website, I will also add CONTACT US option in the website wherever it is needed.

**Comment by Raksha-Vats** [comment]
hello..@HimanshuNarware please assign this issue to me , I can add the contact us page as well the option in the home page , i already made a lot of websites and have some experience in this .

**Comment by Dilpreet0501** [comment]
Hello @HimanshuNarware , kindly assign this issue to me , I can add contact us page like the following two formats.

1.
![Screenshot 2024-05-15 154016](https://github.com/HimanshuNarware/Devlabs/assets/100590445/966e7edb-ef70-4325-9ee1-85da92c17dd3)


2. 
![Screenshot 2024-05-15 154206](https://github.com/HimanshuNarware/Devlabs/assets/100590445/1ada5d86-c4c1-4f82-8064-531a480a0bb2)

Kindly assign me this issue  under GSSoC'24 and inform me in which format you want me to build a contact page

**Comment by Yuvraj960** [comment]
@HimanshuNarware Please assign this issue to me, I will also attach the backend to it or I can attach the your mail so that every response you get in the contact form, that response is just forwarded to your mail in some formatted form

**Comment by sakshi261203** [comment]
Hi Himanshu Narware, Could you please assign this task to me..
As here are some samples:
![Screenshot (6908)](https://github.com/HimanshuNarware/Devlabs/assets/163162219/f531c5e5-1590-48a6-b279-f655863448ef)

**Comment by yash28goyal** [comment]
Please assign this issue to me as I can add interactive and good user experience contact us page to this project
![Screenshot 2024-05-31 092337](https://github.com/HimanshuNarware/Devlabs/assets/123368055/a551db84-bbcc-4635-a9da-54a9fe4d0c94)
![Screenshot 2024-05-31 092355](https://github.com/HimanshuNarware/Devlabs/assets/123368055/70b035e9-9850-48b9-86ee-0bb76133a136)
![Screenshot 2024-05-31 092407](https://github.com/HimanshuNarware/Devlabs/assets/123368055/9b07881b-a26b-48b7-93b1-b2137688bc51)

**Comment by panwar8279** [comment]
Hi @Manishar55 , , I am assigning this task to you. Kindly complete this task within 3 days. Good Luck!
