### ISSUE TITLE
add hover effect on  the sidebar

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#24]

**Comment by Subhashini014** [comment]
could you please assign me this issue.

**Comment by irfan2577** [comment]
Can I work on this? 
Also please elaborate on the request or add some images if possible.

Thank you

**Comment by HimanshuNarware** [comment]
@irfan2577 
![img](https://github.com/HimanshuNarware/Devlabs/assets/83147410/591b5d4e-8c46-4a69-b608-90c942121e4f)

**Comment by irfan2577** [comment]
Thanks for sharing @HimanshuNarware 
Please assign this to me.

**Comment by HimanshuNarware** [comment]
@irfan2577  assigned you

**Comment by IrfanSalim** [comment]
![image](https://github.com/HimanshuNarware/Devlabs/assets/109443065/23683d26-4539-4be3-bb59-cf6842a84e80)
would this be enough or can I also add a color change on hover to match the theme?

**Comment by HimanshuNarware** [comment]
@IrfanSalim  nice , now raise  a PR
