### ISSUE TITLE
[New Tool]: To add framer in /front-end-tools

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#2406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

It helps to create smooth and advanced animations easily 

### Use Case

It helps to create smooth and advanced animations easily 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush-848** [comment]
@panwar8279 please assign this issue to me

**Comment by panwar8279** [comment]
Hi @ayush-848 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
