### ISSUE TITLE
Signup/Login Functional Forms + Bookmarks (linked with user account instead of Local Storage)  (Frontend)

### ISSUE THREAD

**Issue by rikhiltaneja** [HimanshuNarware/Devlabs#241]
## **Is your feature request related to a problem? Please describe.**
Currently, there is **no signup/login functionality implemented in the frontend** of the project. It is very important to personalise the experience of users on any website and signup/login will be a great step in that direction. Implementing this in the frontend side will also make feature of Bookmarks linked with a user account instead of Local Storage leading the users to access bookmarks on all devices/browsers on which they use the website.

## **Describe the solution you'd like**
I have **developed the functionality of Signup/Login and Bookmarks in the backend side** (as assigned by you in #222 ). PR for the same: #240 
Now, using that functionality, I will implement **interactive and beautiful** Login/Signup _(matching with the theme and color-scheme of the website)_ forms so that users feel tempted to login and use the website to the fullest potentional. Also, I will change the functionality of **Bookmarks from Local Storage to linking directly with User Account** in MongoDB. After this, users will be able to **access there bookmarks on any device/browser**.

## Screenshots of Login/Signup forms from my previous projects:

![image](https://github.com/HimanshuNarware/Devlabs/assets/142862928/38a1e592-04f0-4c42-94ee-51e9bfd767b5)

![image](https://github.com/HimanshuNarware/Devlabs/assets/142862928/f7ef018f-543a-4b6e-b031-69186eeba703)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

@HimanshuNarware Please assign this issue to me. I will give my best to accomplish everything mentioned above. 
Looking forward to a positive response. 😄

**Comment by HimanshuNarware** [comment]
@rikhiltaneja  assigned you

**Comment by rikhiltaneja** [comment]
Thanks for the opportunity! 😄 @HimanshuNarware

**Comment by Sid-80** [comment]
@HimanshuNarware I am willing to work on this issue!
