### ISSUE TITLE
[Bug]: Image is overflowing the screen in the contributor section .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Image of contributor is flowing out of the box .

### Expected behavior

I can make changes so that image in not flowing out .

### Add ScreenShots

![Screenshot (885)](https://github.com/user-attachments/assets/b7894674-964f-4e35-9f7d-f8b7c1fdf78a)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@panwar8279 this issue is still there kindly assign this to me .

**Comment by meetarora10** [comment]
Hi @panwar8279 please assign this task to me .

**Comment by panwar8279** [comment]
Hi @meetarora10 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
