### ISSUE TITLE
[New Tool]: Add Devhints

### ISSUE THREAD

**Issue by Ajita369** [HimanshuNarware/Devlabs#2416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A collection of quick reference cheat sheets for a variety of programming languages and tools.

### Use Case

This is very helpful resource for developers. 

### Benefits

This is very helpful for beginner developers.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d3330436-25bb-4604-a7a1-1a3a19418deb)
![image](https://github.com/user-attachments/assets/0466c3f4-bed3-4f7a-afa2-e7b6a2cb29d4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ajita369 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
