### ISSUE TITLE
[Feature] : Bookmarked Book

### ISSUE THREAD

**Issue by sivaprasath2004** [HimanshuNarware/Devlabs#244]
**Is your feature request related to a problem? Please describe.**
- If the `Bookmark` button was clicked the `bookmark` added in the page,but doesn't mention the book already `booked`.

**Describe the solution you'd like**
If the book already booked then the button has showed `booked`.

** Add screenshot 
![Screenshot from 2024-05-12 09-25-27](https://github.com/HimanshuNarware/Devlabs/assets/121082414/23073a95-561e-4f38-ae46-3ec4fcef134b)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by kushalkumar1362** [comment]
I would like to work on this task. Could you please assign it to me, @sivaprasath2004 ?

**Comment by Nirvanjha2004** [comment]
@sivaprasath2004  Hey can u explain the issue in detail...?Thanks

**Comment by kushalkumar1362** [comment]
Please assign this task to me, as I have already solved it.
![image](https://github.com/HimanshuNarware/Devlabs/assets/140513098/2a46003c-2e8d-4756-bded-566020a57b3a)

**Comment by kushalkumar1362** [comment]
Please assign this task to me as I have already completed it.
@sivaprasath2004  @HimanshuNarware 
![image](https://github.com/HimanshuNarware/Devlabs/assets/140513098/28ebb696-5d5a-47a6-a162-4196a8a41414)
