### ISSUE TITLE
[Feature Request]: adding new tools

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Skillshare
MasterClass
ed2go
CreativeLive
Treehouse
Alison

### Use Case

Focuses on creative and professional skills with a project-based approach.
Courses from world-renowned experts across various fields, including arts, cooking, sports, and more.
Online courses for professional development and career training.
Live and on-demand courses in photography, art, design, music, and more.
Online coding courses and tracks for beginners.
Free courses in various fields including IT, business, health, and languages.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AmruthaPariprolu , i am assigning this task to you.  kindly complete within 2 days. Good luck!
