### ISSUE TITLE
[Feature Request]: add indeed

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Free resume builder with templates and customization options.

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AmruthaPariprolu , i am assigning this task to you.  kindly complete within 2 days. Good luck!
