### ISSUE TITLE
[Feature Request]:  Add User Authentication(LOGIN & SIGNUP PAGE)

### ISSUE THREAD

**Issue by arunimaChintu** [HimanshuNarware/Devlabs#2445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This will add a login and register page...

### Use Case

used for user authentication

### Add ScreenShots

<img width="1418" alt="Screenshot 2024-07-30 at 10 43 38 PM" src="https://github.com/user-attachments/assets/30a5384b-56fb-43b2-931a-d30b8e9c12f7">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
@HimanshuNarware Please assign me this issue...

**Comment by Kiran-pande-30** [comment]
@panwar8279 currently i am not working on the login authentication.

**Comment by panwar8279** [comment]
Hi @arunimaChintu ,i am assigning this task to you.  kindly complete within 2 days. Good luck!
