### ISSUE TITLE
[Feature Request]: Want to improve the UI of social media icons present on the contact page.

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#2446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The social media icons present on the contact page are very small in size , without proper spacing between them and no proper hover effects .

### Use Case

Assign this task to me and I can add all the above mentioned features and hence fix this issue .

### Add ScreenShots

![Screenshot (897)](https://github.com/user-attachments/assets/7224e967-44d5-42d3-8d4e-bfaf78076181)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by meetarora10** [comment]
@panwar8279 please have a look .

**Comment by panwar8279** [comment]
Hi @meetarora10 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
