### ISSUE TITLE
[Bug]: Contents of the Rate Us page are not loading when clicked from the footer .

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#2447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Only the footer is visible when rate us tab is clicked from the footer and no contents of rate us is visible .

### Expected behavior

I can make changes to load contents of the rate us page when clicked from the footer .

### Add ScreenShots

![Screenshot (898)](https://github.com/user-attachments/assets/e4c3f867-892d-4c05-b10b-0b2530888329)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @meetarora10 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
