### ISSUE TITLE
[Bug]: Fixing Pagination based on Search & Sort

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. Fixing pagination on the homepage when searching for tools not found in the database.
![image](https://github.com/user-attachments/assets/f0371f72-a76b-4695-8e83-1c65b40e6d8f)

### Expected behavior

The pagination should be with the number of result on the search bar.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
