### ISSUE TITLE
{FEATURE] Revert to home screen after Searching anything

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#245]
**Is your feature request related to a problem? Please describe.**

When i search anything then i am getting no option to see all cards again .

**Describe the solution you'd like**

I can solve it by the logic if search field is empty and user press enter in search field then shows all the cards again .

** Add screenshot 

https://github.com/HimanshuNarware/Devlabs/assets/118350936/9203119d-4f7a-444c-9b2b-760d31ad6f14

Checklist
Example  Fill x { [x] }  into  bracket

- [X ] I have checked the existing issues *
- [ X] I have read the Contributing Guidelines *
- [ X] I have starred the repository *
- [ X] Working under Gssoc'24

**Comment by kushalkumar1362** [comment]
I would like to work on this task. Could you please assign it to me, @sivaprasath2004?

**Comment by Ayushmaanagarwal1211** [comment]
Hii i want to work on this Kindly assign to me

**Comment by Nirvanjha2004** [comment]
Heyy @Chaitali-sonare  Can u assign me this issue.....I would love to work on this
