### ISSUE TITLE
[Bug]: Item not found still pagination displayed 

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#2450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,
the item not found still pagination displayed

### Expected behavior

it should be hide

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b5a213b7-4993-4618-8e0b-5b3ba2fe3fa8)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
