### ISSUE TITLE
[Bug]: Rate us is actually open in model but it also open another route 

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#2451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,
 Rate us is actually open in model but it also open another route 

### Expected behavior

it should be open in model not in another route

### Add ScreenShots

![image](https://github.com/user-attachments/assets/02b08562-f3a1-4fdb-bbdf-f21a1bb9a921)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
