### ISSUE TITLE
[Bug]:  sign in page css

### ISSUE THREAD

**Issue by dhairyagothi** [HimanshuNarware/Devlabs#2453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

css of sign in page is uneven 

### Expected behavior

width should be fixed

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c767a22b-391f-4434-b326-9ec9e95b24b6)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dhairyagothi** [comment]
@panwar8279 please assign me

**Comment by panwar8279** [comment]
Hi @dhairyagothi , i am assigning this task to you.  kindly complete within 2 days. Good luck!
