### ISSUE TITLE
[Feature Request]:  adding discord logo

### ISSUE THREAD

**Issue by jayanththalla** [HimanshuNarware/Devlabs#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer, the discord logo is not there 

### Use Case

adding discord logo

### Add ScreenShots

![image](https://github.com/user-attachments/assets/97676d0a-5029-4f2e-96ae-715aee2e153d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @jayanththalla ,i am assigning this task to you.  kindly complete within 2 days. Good luck!
