### ISSUE TITLE
Allignment of Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to Allign Footer Perfectly
Can you assign me this issue under GSSOC'24  @pan

### Use Case

![IMG_20240731_105130](https://github.com/user-attachments/assets/816273f8-5162-4110-a8e4-df740b31851d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @panwar8279

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @panwar8279

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , i am assigning this task to you.  kindly complete within 2 days. Good luck!
