### ISSUE TITLE
No proper Routing

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to set up the routing so that when user click on rate us on mobile screen it should head there 
Can you assign me this issue under GSSOC'24 @panwar8279 

### Use Case

https://github.com/user-attachments/assets/7a4acc38-be55-4d7d-b178-54294a1a859d

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @panwar8279

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , i am assigning this task to you.  kindly complete within 2 days. Good luck!
