### ISSUE TITLE
Enhancement of Rate Us Page 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to Enhance Rate us page so that it will make our website to look Attractive
Can you assign me this issue under GSSOC'24 @paanwa

### Use Case

![IMG_20240706_122058](https://github.com/user-attachments/assets/2d311999-dca1-4c66-91ab-976fc0623503)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @panwar8279

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , i am assigning this task to you.  kindly complete within 2 days. Good luck!
