### ISSUE TITLE
[Feature Request]: improve profile page

### ISSUE THREAD

**Issue by sau-mili** [HimanshuNarware/Devlabs#2472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the UI is very basic, and not responsive at all

### Use Case

to create profile

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sau-mili , i am assigning this task to you.  kindly complete within 2 days. Good luck!

**Comment by sau-mili** [comment]
I am getting this error while cloning, can you please help? 

error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 10 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
