### ISSUE TITLE
Add tags to the cards

### ISSUE THREAD

**Issue by Pratik2401** [HimanshuNarware/Devlabs#249]
**Is your feature request related to a problem? Please describe.**
Using tags will be more attractive and better than description

**Describe the solution you'd like**
We can add tags to each card by which we can use that for searching purpose also

** Add screenshot 
![WhatsApp Image 2024-05-12 at 16 20 49_432d28c1](https://github.com/HimanshuNarware/Devlabs/assets/105542579/d77226b0-e113-4c13-8c39-68d96da24dd6)
like these tags can be added it is an example of previous project

Checklist
Example  Fill x { [x] }  into  bracket

- [ ✓] I have checked the existing issues *
- [✓ ] I have read the Contributing Guidelines *
- [ ✓] I have starred the repository *
- [ ✓] Working under Gssoc'24

**Comment by HimanshuNarware** [comment]
@Pratik2401 show me demo  first

**Comment by Pratik2401** [comment]
![image](https://github.com/HimanshuNarware/Devlabs/assets/105542579/e3c366bd-ccd1-4875-8671-3ead60e6b856)
like these i can enhance the ui of that it will help in searching also so i think it is great addition

**Comment by sakshi261203** [comment]
Hi Himanshu Narware , Could you please assign this issue to me..

**Comment by panwar8279** [comment]
Hi @Pratik2401 , I am assigning this task to you. Kindly complete this task within 3 days. Good Luck!
