### ISSUE TITLE
[New Tool]: Add "InVision"

### ISSUE THREAD

**Issue by arunimaChintu** [HimanshuNarware/Devlabs#2490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A comprehensive digital product design platform offering tools for prototyping, collaboration, and workflow management. InVision’s free version makes it accessible to beginners while providing advanced features for professionals.

### Use Case

Use Case: Enhancing Team Collaboration in UI/UX Design with InVision

Project Overview:
A mid-sized tech company is working on a new mobile app and needs a tool to streamline their design process and improve collaboration between designers, developers, and stakeholders.

Challenges:

Fragmented Design Process: Designers were using different tools, leading to inconsistencies and miscommunication.
Lack of Real-Time Feedback: Feedback loops were slow, causing delays in the design iterations.
Difficulty in Prototyping: Creating interactive prototypes to showcase user flows was time-consuming and cumbersome.

### Benefits

Benefits:

Increased Efficiency: The centralized design repository and real-time collaboration tools reduced the time spent on managing design files and communication.
Improved Feedback Loop: Stakeholders could easily understand and interact with the prototypes, leading to more actionable feedback and quicker iterations.
Enhanced Prototyping: Interactive prototypes helped the team identify potential issues early in the design phase, saving time and resources in development.

### Add ScreenShots

<img width="1418" alt="Screenshot 2024-07-31 at 9 42 18 PM" src="https://github.com/user-attachments/assets/4812a42c-0c6b-4fd3-a3bc-0dc2fccdbeee">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
@panwar8279 Please assign me this issue

**Comment by panwar8279** [comment]
Hi @arunimaChintu , i am assigning this task to you.  kindly complete within 2 days. Good luck!
