### ISSUE TITLE
[New Tool]: Add Helperbird

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Helperbird is your all-in-one extension, designed to help everyone with personalized support to make web pages, apps, and PDFs more accessible and productive according to an individual's abilities, learning styles, and lifestyle.

### Use Case

Improve your reading, writing & accessibility. Including Immersive Reader, Summarize, Dyslexia support, Reading mode and more.

### Add ScreenShots

![Screenshot 2024-07-31 230429](https://github.com/user-attachments/assets/b7ac61e0-6de7-462e-8e33-a7e00cb28956)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
