### ISSUE TITLE
[New Tool]: Add Wiseone

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Wiseone is your ultimate AI tool to enhance your web searches and boost your reading productivity. ⚡️👨‍💻

Explore the web while ensuring a unique & efficient experience that allows you to save time, improve your productivity, and expand your knowledge.

### Use Case

⏱ Summarize: helps you read more efficiently without losing information by providing essential facts to remember.
💬 Ask Anything: you can ask any question on any web page you're reading and get relevant and sourced answers from top search engines to simplify any information.
🔎 Focus: allows you to understand complex concepts and words on any webpage to master 100% of your reading.
✅ Cross-check: helps you access factual & reliable sources reporting on the same topic to get diverse perspectives.
📰 Explore: provides news, academic sources, and videos from multiple sources to deepen your understanding of any subject

### Add ScreenShots

![Screenshot 2024-08-01 005725](https://github.com/user-attachments/assets/6a786df7-efdc-42e8-ba7b-bca978cb1af6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
