### ISSUE TITLE
[New Tool]: Add SciSpace

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Your AI research assistant for understanding scientific literature.

Your AI research assistant for discovering and analyzing scientific literature.

With SciSpace, you no longer have to open new tabs and Google unfamiliar concepts every time you come across one.

### Use Case

Just ask SciSpace for research-backed explanations or summaries for any text, maths, and tables in any research paper, technical blog post, or report you’re reading. You can also ask follow-up questions, and it will give you answers with citations.

### Add ScreenShots

![Screenshot 2024-08-01 005933](https://github.com/user-attachments/assets/1108b89c-6337-4d70-ba0e-c74774bf7c2c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
