### ISSUE TITLE
[New Tool]: Add Smart TOC

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Webpage outliner

Displays a table of contents for any website, making it easier to read and navigate long articles, documentations, and online books.

### Use Case

- Auto detects article and headings, with our smart algorithm
- Highlights current heading
- Click to jump to heading
- Expand/fold headings, or to specified level
- Floating panel, drag, resize, or dock to side
- Mouse hover while holding Alt/Option key to glance
- Copy to clipboard
- Clean user interface
- Only runs when you use it

### Add ScreenShots

![Screenshot 2024-08-01 010151](https://github.com/user-attachments/assets/2696cc4a-7cfe-4570-b598-34e1103ff22e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
