### ISSUE TITLE
[New Tool]: Add Postman Interceptor

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Capture requests from any website and send them to Postman Client.

### Use Case

Postman Interceptor helps you send requests which use browser cookies through the Postman app. 
It can also send headers which are normally restricted by Chrome but are critical for testing APIs. The Interceptor makes this process painless. Something that would have required a proxy earlier can now be achieved without any installation steps or extra configuration.

### Add ScreenShots

![Screenshot 2024-08-01 010359](https://github.com/user-attachments/assets/9a18c791-8084-428c-890d-6fc7ce50cac5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 ,i am assigning this task to you.  kindly complete within 2 days. Good luck!
