### ISSUE TITLE
[New Tool]: Add Talend API Tester

### ISSUE THREAD

**Issue by AsmitaMishra24** [HimanshuNarware/Devlabs#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Visually interact with REST, SOAP and HTTP APIs.

Welcome to Talend API Tester - Free Edition, formerly known as Restlet Client. Talend API Tester makes it easy to invoke, discover and test HTTP and REST APIs. 

### Use Case

  - Interact with REST or simple HTTP APIs through a visual and easy-to-use UI
  - View and search your call history. Edit and re-send requests from history.
  - Save and organize your requests into projects and services.
  - Build dynamic requests with custom variables, security and authentication.
  - Visualise and inspect responses of different format (JSON, XML, HTML, images...) using different views (raw, pretty, preview) 
  - Validate responses with assertions (status, headers, XML and JSON body, response time...)
  - Easily import your Postman Collections, Swagger / OAS / OpenAPI and HAR (HTTP Archive).

### Add ScreenShots

![Screenshot 2024-08-01 010559](https://github.com/user-attachments/assets/66bbbae8-fb33-4ef0-816a-f7b72cd9ea35)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AsmitaMishra24 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
