### ISSUE TITLE
[New Tool]: adding prompt based gen ai tools to build website

### ISSUE THREAD

**Issue by Khushalsarode** [HimanshuNarware/Devlabs#2499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I have searched and listed some tools for creating webpages/website based on prompt given by user.

### Use Case

- easy to make websites/pages for any needs

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Khushalsarode** [comment]
@panwar8279 let me know?

**Comment by panwar8279** [comment]
Hi @Khushalsarode , i am assigning this task to you.  kindly complete within 2 days. Good luck!
