### ISSUE TITLE
Prev and Next buttons in About-Us page

### ISSUE THREAD

**Issue by AtharvKasar04** [HimanshuNarware/Devlabs#250]
**Describe the bug**
The Previous button still works even if we are on the first page.
Same for next button which works even on the last page.

@HimanshuNarware Can you please assign this issue to me under GSSoC'24. 
Thank You!

**Expected behavior**
The previous button should be disabled if the user is on the 1st page and Vice-Versa for the Next button

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/108543702/a4fa8884-a56b-458b-8d44-7543ad33f9d5)
![image](https://github.com/HimanshuNarware/Devlabs/assets/108543702/9cb7d6c6-1576-422b-bcd1-972f05e9d790)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by AMISH-KHAN** [comment]
can I work on this?
