### ISSUE TITLE
[Feature Request]: Making updated in about and home page

### ISSUE THREAD

**Issue by Khushalsarode** [HimanshuNarware/Devlabs#2500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- home page tiles are larger making them in decent size by adjusting logo, contain and links buttons
- formatting and aligning the about page with content and here to making the grids decent normal view.

### Use Case

- will look like professional 
- we be easy to navigate and view

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Khushalsarode** [comment]
@panwar8279 let me know?
@HimanshuNarware

**Comment by panwar8279** [comment]
Hi @Khushalsarode , i am assigning this task to you.  kindly complete within 2 days. Good luck!
