### ISSUE TITLE
Apps in wrong section

### ISSUE THREAD

**Issue by Pratik2401** [HimanshuNarware/Devlabs#251]
**Describe the bug**
The tailwind css,daisyui,cssportal extra can be seen in movie sections,hacking section etc.

**Expected behavior**
The apps should be in there respective sections

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/105542579/59101223-b6e2-46d9-9fa1-3c9a09fcfbba)

Example  Fill x { [x] }  into  bracket

- [ ✓] I have checked the existing issues *
- [✓ ] I have read the Contributing Guidelines *
- [✓ ] I have starred the repository *
- [ ✓] Working under Gssoc'24

**Comment by SatyajitPatra06** [comment]
Hi @HimanshuNarware , I can fix this issue, pls assign this to me under GSSOC '24
