### ISSUE TITLE
Adding "Coursera" website

### ISSUE THREAD

**Issue by ujj654** [HimanshuNarware/Devlabs#252]
Most use full website "Coursera" is missing from your cart.
It provides many courses for free to the students.

![Screenshot 2024-05-12 174835](https://github.com/HimanshuNarware/Devlabs/assets/81877649/54de3270-4758-411b-8220-8e2601dacb69)

I want to add this website into your cart. So please assign me this Issue.  #GSSoc'24

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Ayusha-a07** [comment]
i want to contribute on this.please kindly assign me this task

**Comment by panwar8279** [comment]
@ujj654, what's the progress of work?

**Comment by ujj654** [comment]
Sorry for delay because my end sem exam ongoing but currently i am working on it
