### ISSUE TITLE
Code Review and Improvement Suggestions for Backend JS Files

### ISSUE THREAD

**Issue by moroii69** [HimanshuNarware/Devlabs#253]
**Describe the bug**
The bug descriptions for the respective files are missing.

**Expected behavior**
- **File Name: app.js** 
  - **Consolidate Middleware:** Instead of importing and using each middleware separately, we can chain them together to reduce redundant code.
  - **Use dotenv Directly:** Instead of requiring and invoking dotenv.config() separately, we can directly invoke it within the require statement.
  - **Minimize Route Definitions:** We can consolidate route definitions to make the code cleaner.

- **File Name: specialController.js** 
  - **Object Destructuring:** Instead of accessing properties directly from req.body, object destructuring is used to extract name, email, and review directly from req.body. This makes the code cleaner and more concise.
  - **Template Literal:** Template literals are used for generating the email body (generateEmailBody). This allows for more readable and maintainable HTML code within JavaScript strings.
  - **Error Handling:**
    - The try...catch block is used to catch any potential errors that may occur during the execution of the sendMail function. This ensures that any errors are gracefully handled, preventing the server from crashing.
    - The caught error is logged to the console for debugging purposes, providing insights into what went wrong.
    - The error response sent to the client is improved to provide a more informative error message ("Internal Server Error") in case of unexpected errors.
  - **Consistent Error Responses:**
    - In the case where required data (name, email, or review) is missing, a 400 Bad Request response is sent with a JSON object containing the success status set to false and an array of error messages (["Missing Data"]).
    - In the case of other errors, such as server-side errors during the email sending process, a 500 Internal Server Error response is sent with a similar JSON object containing the success status set to false and an array of error messages (["Internal Server Error"]).

- **File Name: openSourceController.js** 
  - **Validation:** Before proceeding to add a new project, validate the incoming request body to ensure it contains all the required fields.
  - **Error Handling:** Ensure robust error handling to catch and handle errors gracefully.
  - **Response Standardization:** Standardize the response format for consistency across different endpoints.
  - **Use of Async/Await:** Utilize async/await for asynchronous operations to improve code readability and maintainability.
  - **Code Structure:** Enhance code structure for better organization and readability.

**Screenshots**
N/A

Example Fill x { [x] } into bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by SandipGyawali** [comment]
@Ufraan hey i can work on everything that you mentioned. can i contribute to it. I am willing to do it. If yes then assign me with a label

**Comment by Ufraan** [comment]
> @Ufraan hey i can work on everything that you mentioned. can i contribute to it. I am willing to do it. If yes then assign me with a label
> 
> 

Isn't it the repository owner/admin who can assign issues?

**Comment by SandipGyawali** [comment]
@moroii69 yes, i guess
