### ISSUE TITLE
[Bug]:  Flickering issue on hovering over categories seciton 

### ISSUE THREAD

**Issue by haseebzaki-07** [HimanshuNarware/Devlabs#2534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is flickering issue when we hover on to the categories section under the main landing part of the site

### Expected behavior

It should not flicker instead maintain its height/width

### Add ScreenShots

![Screenshot 2024-08-02 003419](https://github.com/user-attachments/assets/880870d3-16e1-439c-8fb5-8d51ad034ced)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @haseebzaki-07 , i am assigning this task to you.  kindly complete within 2 days. Good luck!

**Comment by haseebzaki-07** [comment]
Sure, thanks for assigning me the task!
