### ISSUE TITLE
[Bug]: bookmark count message box contracted

### ISSUE THREAD

**Issue by haseebzaki-07** [HimanshuNarware/Devlabs#2535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the msg boz that shows count on the bookmark tab on the appbar is contracted 

### Expected behavior

it should not be contracted it should be its shape and form

### Add ScreenShots

![Screenshot 2024-08-02 003647](https://github.com/user-attachments/assets/d35d1650-92ca-497a-b88b-6798878cf865)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @haseebzaki-07 , i am assigning this task to you.  kindly complete within 2 days. Good luck!

**Comment by haseebzaki-07** [comment]
HI @panwar8279 please review my PR.
