### ISSUE TITLE
Allignment of Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to Allign Footer Perfectly
Can you assign me this issue under GSSOC'24 @panwar8279

### Use Case

![IMG_20240802_092354](https://github.com/user-attachments/assets/c18dddf8-a5db-4e28-bd42-1f97d62763e5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sailaja-adapa** [comment]
@panwar8279 can you assign me this issue under GSSOC'24

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , i am assigning this task to you.  kindly complete within 2 days. Good luck!
