### ISSUE TITLE
[New Tool]: I want to add new tool (course)

### ISSUE THREAD

**Issue by vishanurag** [HimanshuNarware/Devlabs#2545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

-  I want to add new course tool that provides amazing learning with certifications.

### Use Case

- By learning & getting certificate, learners can showcase their learning.

### Benefits

- By learning & getting certificate, learners can showcase their learning.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by vishanurag** [comment]
@panwar8279 please assign this issue to me under GSSoC'24

**Comment by panwar8279** [comment]
Hi @vishanurag , i am assigning this task to you.  kindly complete within 2 days. Good luck!
