### ISSUE TITLE
[New Tool]: add snakify

### ISSUE THREAD

**Issue by ImmidiSivani** [HimanshuNarware/Devlabs#2554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

In Snakify  website users can learn and practice python with interactive tutorials and exercises.

### Use Case

new course addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ImmidiSivani , i am assigning this task to you.  kindly complete within 2 days. Good luck!
