### ISSUE TITLE
[Bug]: Aling center pagination buttons 

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#2556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out

### Expected behavior

it should be in center 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0c2630b1-66f0-4a3e-acad-98f85a51fbb6)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
