### ISSUE TITLE
[Bug]: Remove Bookmark not working

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#2558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@panwar8279 

check this out,

### Expected behavior

it should removed from bookmark page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9e23a015-cb15-44dc-941e-65a133c5cfd6)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
