### ISSUE TITLE
Add suggestion for search bar

### ISSUE THREAD

**Issue by VSNSRUJANA123** [HimanshuNarware/Devlabs#256]
**[Feature] Add a suggestion search preview when searching the given data.**

![Autocomplete search box](https://github.com/HimanshuNarware/Devlabs/assets/127814497/d194c890-4223-4430-a7f9-a521ccf88e9d)

- When item is not found in search item

![nosearchitem](https://github.com/HimanshuNarware/Devlabs/assets/127814497/cb45d9cc-7118-44e6-9713-7059cfd9dc4b)

- I have checked the existing issues 
- I have read the Contributing Guidelines please assign the issue to me

**Comment by VSNSRUJANA123** [comment]
Thanks for assigned to me

**Comment by VSNSRUJANA123** [comment]
i need another one help for search suggestions bar

**Comment by aMan404deep** [comment]
Hy !! I would love to work on this project . Kindly assign me this issue.

**Comment by RekhaKushwaha01** [comment]
I would like to work on this project . Kindly assign me this issue.

**Comment by anshikatiwari20** [comment]
@HimanshuNarware I am a GSSoC contributor and would like to work on issue #256 to add suggestions for the search bar. Could you please reassign this issue to me? Thank you!
