### ISSUE TITLE
[Feature Request]: validation on Login

### ISSUE THREAD

**Issue by DevGajjar28** [HimanshuNarware/Devlabs#2565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So currently I have log in to website so see , how i improved the website then at the starting login page i have found that there is no validations or some short of Security for the user. 

### Use Case

Validations ensure that only authorized users can access certain areas of the website.
Validations help prevent malicious attacks,

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @DevGajjar28 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
