### ISSUE TITLE
User Authentication-> Login/signup page

### ISSUE THREAD

**Issue by lakshyajn** [HimanshuNarware/Devlabs#257]
**Is your feature request related to a problem? Please describe.**
So DevLaps need to have login/signup page for user authentication.
Suppose if anyone gets to our laptop and just open it and then knows in bookmark what I am doing and searching.
This is actually irritating,
Also linking will also link the sites and so the data of ours with it.

**Describe the solution you'd like**
I want to build user authentication for data privacy and user trust, hence login and sign up, and error handling

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @lakshyajn, I have assigned this work to you, Kindly complete within a week. Good Luck!

**Comment by Hitesh4278** [comment]
Hi @panwar8279  can you please assign this issue to me?
