### ISSUE TITLE
[New Tool]: Pinterest Tool

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

It is like social app for download and viewing content

### Use Case

The Pinterest tool helps us to download high-quality images for free.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , i am assigning this task to you.  kindly complete within 2 days. Good luck!

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279, @Maheshwari-Love should be assigned to those issues. He can work on the adding tools issues raised by me.
