### ISSUE TITLE
[New Tool]: Apollo Extension

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Apollo enables users to find contact info, connect with buyers, track emails, and more for free.

### Use Case

It's quite helping to get emails and numbers from LinkedIn. I

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
