### ISSUE TITLE
[New Tool]: Privacy Badger

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Privacy Badger is a browser extension that stops advertisers and other third-party trackers from secretly tracking where you go and what pages you look at on the web.

### Use Case

It help to block third party ads

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
