### ISSUE TITLE
[New Tool]: PriceHistory Tool

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

It helps to get the price range of products listed on e-commerce platform.the 

### Use Case

It helps to get the price range of products listed on e-commerce platform.the 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
@Maheshwari-Love go ahead you can work on this issue.
#2588 #2589 #2590 #2591

**Comment by Maheshwari-Love** [comment]
> @Maheshwari-Love go ahead you can work on this issue. #2588 #2589 #2590 #2591 #2593 #2592

@panwar8279 please assign me so that i can start working on this
