### ISSUE TITLE
[New Tool]: Codeium AI

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#2593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A free AI powered toolkit for developers

### Use Case

A free AI powered toolkit for developers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , i am assigning this task to you.  kindly complete within 2 days. Good luck!
