### ISSUE TITLE
Enhance Rate Us 

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to Enhance Rate us page like this in below image 

![IMG_20240706_122058](https://github.com/user-attachments/assets/4b8eb6d4-da23-4b92-8eb7-fdde6649ab94)

### Use Case

Can you assign me this issue under GSSOC'24 @panwar8279 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , i am assigning this task to you.  kindly complete within 2 days. Good luck!
