### ISSUE TITLE
[New Tool]: Adding new tools

### ISSUE THREAD

**Issue by chaanakyaaM** [HimanshuNarware/Devlabs#2606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I would like to add:

Bored Panda
A Soft Murmur
Little Alchemy 2
This Is Sand
Quick,draw
Hemingway Editor
HowStuffWorks
The Useless Web
FutureMe
Have I Been Pwned
Shapeways
The Secret Door
ZenPen
Artbreeder
Patatap
Spoonflower
Gnoosic
Doodle Cat

### Use Case

These websites are unique and each has its own specialty and use.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @chaanakyaaM , i am assigning this task to you.  kindly complete within 2 days. Good luck!
