### ISSUE TITLE
Add Dark Mode feature

### ISSUE THREAD

**Issue by Shivam250702** [HimanshuNarware/Devlabs#263]
**Is your feature request related to a problem? Please describe.**
Yes, It reduces the strain on eyes
**Describe the solution you'd like**
Introducing a dark mode feature

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Shivam250702, I have assigned this work to you, Kindly complete within a week. Good Luck!
