### ISSUE TITLE
Automatically close hamburger after selecting an option 

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#264]
Problem:
Currently, when using the hamburger menu, after selecting an option, the menu remains open, which can be inconvenient and disrupt the user experience.

Solution:
Implement automatic closure of the hamburger menu upon selecting an option, enhancing user flow and ensuring a smoother navigation experience.

** Add screenshot
![Screenshot_20240513-075103.png](https://github.com/HimanshuNarware/Devlabs/assets/140513098/d0cb2389-6005-47be-9f22-22c5c97fa012)

Checklist
Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [ x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @kushalkumar1362 , I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!

**Comment by kushalkumar1362** [comment]
> Hi @kushalkumar1362 , I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!

Ok, i will give my best, can you please add level

**Comment by kushalkumar1362** [comment]
Hii i requested you to add a level label @HimanshuNarware @panwar8279

**Comment by kushalkumar1362** [comment]
@panwar8279 Please check pull request

**Comment by kushalkumar1362** [comment]
> Hi @kushalkumar1362 , I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!

My task is done please check the pull request

**Comment by kushalkumar1362** [comment]
Please close the ticket as "successfully merged." @panwar8279 @HimanshuNarware
