### ISSUE TITLE
Add Lighting Effect to Footer Links

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add Lighting effect to Footer Links
Can you assign me this issue under GSSOC'24 @panwar8279

### Use Case

https://github.com/user-attachments/assets/40822dc6-1cea-43c0-8beb-deae43023205

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , Please start working on it.

**Comment by sailaja-adapa** [comment]
Yeah okk @panwar8279
