### ISSUE TITLE
Add Hover Effect to Social Media Links

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to Add Hover Effect to Social Media Links
Can you assign me this issue under GSSOC'24 @panwar8279

### Use Case

https://github.com/user-attachments/assets/75a151c8-bf21-4802-9110-d0e8a041ebd3

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , Start working on it.
