### ISSUE TITLE
Feature Request: Bookmark Pagination and Footer Bug Fix

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#265]
**Problem:**
When adding tools to bookmarks, the footer moves to the right side, causing a layout issue.

**Solution:**
Fix the bug causing the footer to shift to the right side when adding tools to bookmarks. Additionally, implementing pagination in the bookmark feature to manage a large number of bookmarks effectively, enhances user experience and organization.

**Screenshots**
![Screenshot_20240513-075922.png](https://github.com/HimanshuNarware/Devlabs/assets/140513098/841986e0-1662-40e5-a1fd-9d07f5897557)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @kushalkumar1362, I have assigned this issue to you, kindly complete within 3 days. Good luck for your work!

**Comment by kushalkumar1362** [comment]
Wow, this is a level 1 job, I thought of it as a level 2 job

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by kushalkumar1362** [comment]
Please close the ticket as "successfully merged." @panwar8279 @HimanshuNarware
