### ISSUE TITLE
[New Tool]: Add edclub

### ISSUE THREAD

**Issue by hars-21** [HimanshuNarware/Devlabs#2651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

This is an e-learning platform where users can be benefitted by various courses like touch typing, vocabulary, social emotional learning.

### Use Case

This E-learning platform provides many courses. 
Mainly, Touch typing: For devs to type fast and spend their time thinking and not just typing.
vocabulary: To make devs speak comfortably with clients
emotional learning : to understand emotions and control them

### Benefits

Users can get a new platform learning these things which come in handy but not required in front pace.

### Add ScreenShots

![Screen Shot 2024-08-05 at 9 59 54 PM](https://github.com/user-attachments/assets/293d14bb-e522-4341-9cfa-2f59d51df1e7)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by DOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd** [comment]
borger
