### ISSUE TITLE
[New Tool]: Add TapAway

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [HimanshuNarware/Devlabs#2658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Tap Away is a life-saving mobile application designed to prioritize your safety during emergencies and natural calamities. By registering on the app, users gain immediate access to crucial services that can make a difference in critical situations

### Use Case

- **User Registration:** Easily register yourself to access emergency services.
- **SOS Button:** In case of a calamity, a simple press of the SOS button sends your location to both concerned authorities and your designated relatives and friends.
- **Swift Response:** Our team of experts and emergency services will swiftly reach the site to provide aid to the victim and ensure their safety.

### Benefits

At Tap Away, our vision is clear - to save as many lives as possible. We believe that every life is precious, and your safety is our utmost priority. Join us in our mission to make the world a safer place, one user at a time.

Explore the "Tap Away" app and be a part of a community dedicated to saving lives and ensuring the well-being of all.

**Your safety matters. Choose Tap Away.**

### Add ScreenShots

<p>
<img center width="250" src="https://github.com/Vaibhav-kesarwani/Disaster-Management-App/assets/116189379/99c739fe-b107-4869-94f9-884ac14f0f14">
<img center width="250" src="https://github.com/Vaibhav-kesarwani/Disaster-Management-App/assets/116189379/402df0b6-7c01-49c5-a54e-2712312dcca6">
<img center width="250" src="https://github.com/Vaibhav-kesarwani/Disaster-Management-App/assets/116189379/d41c7a3e-69b7-4ebc-af5d-e4230fa74972">
</p>

![Screenshot from 2024-04-12, 17-21-46](https://github.com/Vaibhav-kesarwani/TapAway-App/assets/116189379/26bc63a4-032a-49bb-acb1-8e770d65d51e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
@panwar8279 Please assign this issue to me

**Comment by panwar8279** [comment]
Hi @Vaibhav-kesarwani , Please start working on it.
