### ISSUE TITLE
Review Form Not working!

### ISSUE THREAD

**Issue by Omi006** [HimanshuNarware/Devlabs#267]
**Describe the bug**
In the footer section of the website, their is review page, but that review  form is not working the although, I submit the form, it is not showing me that it is submitted. 

**Expected behavior**
Whenever the user , will submit the form. It must be submitted at the backend.

**Screenshots**
This is this review form:
![Screenshot 2024-05-13 105431](https://github.com/HimanshuNarware/Devlabs/assets/113918394/e997919f-904e-40a1-90f6-70ee54ae3022)

- I have checked the existing issues *
- I have read the Contributing Guidelines *
- I have starred the repository *
- Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Omi006, I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!
