### ISSUE TITLE
[New Tool]: add jofibo

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Jofibo offers user-friendly resume and cover letter templates, designed to help you create professional and polished documents quickly.

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AmruthaPariprolu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
