### ISSUE TITLE
[New Tool]: add creddle

### ISSUE THREAD

**Issue by AmruthaPariprolu** [HimanshuNarware/Devlabs#2680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Creddle provides customizable resume templates and a straightforward interface, making it easy to craft modern and effective resumes

### Use Case

tool addition

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AmruthaPariprolu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
