### ISSUE TITLE
[Bug]: Updating the navbar

### ISSUE THREAD

**Issue by manvitha984** [HimanshuNarware/Devlabs#2682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All the elements in the navbar are clustered together can me made more presentable.

### Expected behavior

Better spacing between the navbar elements will enhance the user experience.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c220c993-5472-4221-afd2-2b35cbe4e6d0)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @manvitha984 , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
