### ISSUE TITLE
[New Tool]: Add Spline

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [HimanshuNarware/Devlabs#2690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Spline is a free 3D design software with real-time collaboration to create web interactive experiences in the browser. Easy 3d modeling, animation

### Use Case

1. 3d Text
2. Interactive 3D experience in web
3. Game control and physics

### Add ScreenShots

![Screenshot from 2024-08-06 15-24-31](https://github.com/user-attachments/assets/e60497f3-85cf-4e62-bc17-d406b9f993cf)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Vaibhav-kesarwani** [comment]
@panwar8279 Please assign me this issue

**Comment by Vaibhav-kesarwani** [comment]
@panwar8279 Please assign this to me

**Comment by panwar8279** [comment]
Hi @Vaibhav-kesarwani , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
