### ISSUE TITLE
[New Tool]: Add behance

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [HimanshuNarware/Devlabs#2699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Behance allows creatives to create detailed project portfolios that can include images, videos, and even interactive content. These portfolios can be categorized by industry, such as UI/UX design, graphic design, photography, illustration, motion graphics

### Use Case

new tool

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @DharshiBalasubramaniyam , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
