### ISSUE TITLE
issue : Add favicon and title

### ISSUE THREAD

**Issue by devmusiczz** [HimanshuNarware/Devlabs#27]
![image](https://github.com/HimanshuNarware/Devlabs/assets/114563397/53ba09ad-0ebc-4b24-b6af-ccea9c639056)

**Comment by devmusiczz** [comment]
@HimanshuNarware Hey favicon and title are missing. Can you assign this issue to me under hacktoberfest ?

**Comment by HimanshuNarware** [comment]
@devmusiczz  assigned you

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can you assign me.
