### ISSUE TITLE
[New Tool]: "Scrimba"

### ISSUE THREAD

**Issue by arunimaChintu** [HimanshuNarware/Devlabs#2704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Scrimba

### Use Case

Scrimba

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @arunimaChintu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
