### ISSUE TITLE
[New Tool]: "Carbon"

### ISSUE THREAD

**Issue by arunimaChintu** [HimanshuNarware/Devlabs#2705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Carbon

### Use Case

Carbon

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @arunimaChintu ,I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
