### ISSUE TITLE
[New Tool]: Add "Streamlit"

### ISSUE THREAD

**Issue by kosuri-indu** [HimanshuNarware/Devlabs#2708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Will add Streamlit: An open-source app framework for Machine Learning and Data Science teams to create and share data applications quickly.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/02e32573-2b40-4999-8304-0eb0356bcbba)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kosuri-indu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
