### ISSUE TITLE
[New Tool]: Add "Tabby"

### ISSUE THREAD

**Issue by kosuri-indu** [HimanshuNarware/Devlabs#2711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Will add Tabby: An open-source terminal emulator for a variety of platforms. It aims to provide a customizable and extensible terminal experience.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d3bb31b8-e212-42de-95f2-8a6205f0d35f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kosuri-indu** [comment]
@panwar8279 
Please assign this issue to me

**Comment by panwar8279** [comment]
Hi @kosuri-indu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
