### ISSUE TITLE
[New Tool]: Add "Fathom"

### ISSUE THREAD

**Issue by kosuri-indu** [HimanshuNarware/Devlabs#2712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Will add Fathom: A podcast player that allows users to discover, save, and share highlights from podcasts.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/28521e92-0b36-40d4-abc0-9fb14c7a4a5c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kosuri-indu ,I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
