### ISSUE TITLE
[New Tool]: Add "Blooket"

### ISSUE THREAD

**Issue by kosuri-indu** [HimanshuNarware/Devlabs#2713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Will add Blooket: An educational platform where teachers can create games and quizzes that students can play to learn in a fun and interactive way.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/76a2e59a-1a98-4cb2-ae0b-a9ec750755f8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kosuri-indu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
