### ISSUE TITLE
[New Tool]: Add "Linear"

### ISSUE THREAD

**Issue by kosuri-indu** [HimanshuNarware/Devlabs#2715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Will add Linear: A project management tool focused on creating, tracking, and managing tasks efficiently, particularly for software development teams.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2fd4b334-2655-40aa-b1ed-e6faf70c494e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kosuri-indu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
