### ISSUE TITLE
[New Tool]: Add "Retool"

### ISSUE THREAD

**Issue by kosuri-indu** [HimanshuNarware/Devlabs#2716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Will add Retool: A platform that allows developers to build internal tools quickly using pre-built components, APIs, and databases.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/08f56522-a906-4a64-86f7-74ba23f62a91)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @kosuri-indu , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
