### ISSUE TITLE
[New Tool]: Add PyCharm

### ISSUE THREAD

**Issue by revanth1718** [HimanshuNarware/Devlabs#2718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

I want to add PyCharm tool to the section "coding".

### Use Case

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by revanth1718** [comment]
@HimanshuNarware, @panwar8279 assign me this issue

**Comment by panwar8279** [comment]
Hi @revanth1718 , I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
