### ISSUE TITLE
[New Tool]: Add EdX

### ISSUE THREAD

**Issue by revanth1718** [HimanshuNarware/Devlabs#2719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

edX is an online learning platform offering courses from universities and institutions worldwide. It provides tools for interactive learning, such as video lectures, quizzes, and discussion forums. It's useful for gaining new skills, advancing careers, or exploring new topics.

I want to add this tool

@HimanshuNarware, @panwar8279 assign me this issue under GSSOC'24

### Use Case

Academic study to professional development.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by revanth1718** [comment]
@panwar8279 assign me this issue

**Comment by panwar8279** [comment]
Hi @revanth1718 ,  I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
