### ISSUE TITLE
Scroll to the top can be added for each page

### ISSUE THREAD

**Issue by AyushShukla3466** [HimanshuNarware/Devlabs#272]
Scroll to the top can be added for each page

**Comment by ChethanaPotukanam** [comment]
Yeah , I think it will be more attractive if we fix this issue.Please assign this issue to me under GSSoC24. As I have relevant skills I want to work on this.And please add labels like gssoc and level 1,2 or 3.

**Comment by panwar8279** [comment]
Hi @AyushShukla3466, I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!

**Comment by varun1903** [comment]
Hi  @panwar8279 @HimanshuNarware   I'm Varun Tyagi and I'd like to request to be assigned to  as part of GSSoC. I'm excited to work on this project."
