### ISSUE TITLE
[New Tool]: Add Vercel

### ISSUE THREAD

**Issue by revanth1718** [HimanshuNarware/Devlabs#2720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Vercel is a cloud platform for deploying and hosting front-end applications, providing serverless functions, continuous deployment, and automatic scaling. It's popular for its seamless integration with frameworks like Next.js, allowing developers to easily build, preview, and deploy web applications with high performance and global reach.

I want to add this tool to your website

@HimanshuNarware, @panwar8279 kindly assign me this issue under GSSOC

### Use Case

Use cases include deploying static sites, serverless applications, and full-stack apps.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by revanth1718** [comment]
@panwar8279 assign me this issue

**Comment by panwar8279** [comment]
Hi @revanth1718 ,  I am assigning this task to you. Kindly complete it within 2 days. Good Luck!
