### ISSUE TITLE
pagination bar is not fixed

### ISSUE THREAD

**Issue by mohitkumar1718** [HimanshuNarware/Devlabs#278]
**Describe the bug**

the pagination bar is not fixed in length it should only previous if available, current page and the next page but in the site if 10 page are there then there is total 10 options for page for individual page 1 2 3 4 5 6 7 8 9 10 like this but it should be like this previous |..| next->

**Expected behaviour**
previous | next->

**Screenshots**
![Screenshot 2024-05-13 160141](https://github.com/HimanshuNarware/Devlabs/assets/115692399/976bf930-adb6-4066-9070-4c0bb5d3950b)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [x] Working under Gssoc'24

assign this to me I am Gssoc 2024 contributor

**Comment by panwar8279** [comment]
Hi @mohitkumar1718, I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!
