### ISSUE TITLE
card size is not fixed and not aligned

### ISSUE THREAD

**Issue by mohitkumar1718** [HimanshuNarware/Devlabs#279]
**Describe the bug**
 card section is not aligned and card size is not fixed and it look bad 

**Expected behaviour**
if it is aligned means the buttons are on the same level and the card size if fixed then it look good

**Screenshots**
![Screenshot 2024-05-13 160310](https://github.com/HimanshuNarware/Devlabs/assets/115692399/5f8a411c-95ed-48c3-9511-21736d118b34)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [x] Working under Gssoc'24

assign this to me ill fix it I am a GSSoc contributor

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
