### ISSUE TITLE
about us page ui is very bad 

### ISSUE THREAD

**Issue by mohitkumar1718** [HimanshuNarware/Devlabs#280]
**Describe the bug**
about section page UI is very bad and it reduces the user experience 

**Expected behaviour**
UI should be like heading section is left assign and the photo is on right and for the next section heading is right align and photo should be on left it can look visually good

**Screenshots**
![Screenshot 2024-05-13 160053](https://github.com/HimanshuNarware/Devlabs/assets/115692399/3cd57fe8-906c-4d6e-b72d-db2076619bf1)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [x] Working under Gssoc'24

assign this to me I am a GSSoc contributor

**Comment by Rohit1867** [comment]
please assign me this issue gssoc24
