### ISSUE TITLE
add a section so that user can request the new tool thy know 

### ISSUE THREAD

**Issue by mohitkumar1718** [HimanshuNarware/Devlabs#281]
**Is your feature request related to a problem? Please describe.**
add a section so that user can request the new tool thy know  because there is many tools which is unknown to many people and known to very limited people and they can share the tool 

**Describe the solution you'd like**
if there is a section for requestion to add new tool to the website it will be good for new tools exploration

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] Working under Gssoc'24
- [ ] I have starred the repository *

assign this task to me I am a GSSOC contributor

**Comment by panwar8279** [comment]
Hi @mohitkumar1718, I have assigned this issue to you, kindly complete within a week. Good luck for your work!
