### ISSUE TITLE
Adding hero section to the home page (enhancing UI)

### ISSUE THREAD

**Issue by AlaynaShaheen** [HimanshuNarware/Devlabs#282]
Problem:
Home page UI doesn't look good. It doesn't have any hero section under navbar (introductory part). Home page looks much better if we add hero section. 

Solution:
Home page can be made better by adding hero section which consists of the website name along with tagline and also an image related to it.

Before Screenshot:
![Screenshot 2024-05-13 184210](https://github.com/HimanshuNarware/Devlabs/assets/111679498/66962dd2-fb4f-44f1-b6e3-bd35359a88b3)

Example of how we can enhance home page:
![Screenshot 2024-05-13 185313](https://github.com/HimanshuNarware/Devlabs/assets/111679498/16360395-14b5-4a04-aea1-620d1c234cfa)
The home page will look so good after adding this feature. So please consider this issue and assign this to me.

Checklist
Example  Fill x { [x] }  into  bracket

Yes  I have checked the existing issues *
Yes I have read the Contributing Guidelines *
Yes I have starred the repository *
Yes I am working under Gssoc'24. 

Please assign this issue to me.

**Comment by panwar8279** [comment]
Hello @AlaynaShaheen , I have assigned this issue to you, kindly complete within a week. Good luck for your work!

**Comment by AlaynaShaheen** [comment]
Thank you for assigning me this issue @panwar8279.

**Comment by AlaynaShaheen** [comment]
Hello @panwar8279 ,
I have solved the issue and raised a pull request #369. But it is not getting deployed to vercel and showing that it needs authorisation. I have followed all the steps of CODE OF CONDUCT. So please check the PR once and let me know if there's anything I can do to solve this problem.
