### ISSUE TITLE
about section font size 

### ISSUE THREAD

**Issue by NitinChakrawarti** [HimanshuNarware/Devlabs#283]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem.

In about section logo and description of logo is not visible in single screen which is not a good practice and also star the repo button is big in size which is not running the ui design of website.

**Describe the solution you'd like**
i can create a design which is user friendly 

** Add screenshot 
![Screenshot 2024-05-13 191220](https://github.com/HimanshuNarware/Devlabs/assets/149225785/43f15066-772c-4339-a699-05444e767d25)
![Screenshot 2024-05-13 191234](https://github.com/HimanshuNarware/Devlabs/assets/149225785/6ef69061-9168-4e33-8830-01cc5ef28ca4)

Checklist
Example  Fill x { [x] }  into  bracket

- [ X] I have checked the existing issues *
- [ X] I have read the Contributing Guidelines *
- [ X] I have starred the repository *
- [ X] Working under Gssoc'24

@tedante assign this issue to me

**Comment by panwar8279** [comment]
Hii @NitinChakrawarti , I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!

**Comment by NitinChakrawarti** [comment]
@panwar8279 for sure,

please add label regarding level of issue.

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
