### ISSUE TITLE
product icons not visible

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#285]
- There are multiple products whose icons are not displayed properly, which affects the users experience  

![Screenshot (87)](https://github.com/HimanshuNarware/Devlabs/assets/142779809/ee9b7077-1e5f-48d4-925a-c9b9b86b740b)
![Screenshot (88)](https://github.com/HimanshuNarware/Devlabs/assets/142779809/a6c4d630-89e4-49e6-9d6a-7c27f9658151)

**Comment by panwar8279** [comment]
@root-0101 , I have assigned this issue to you, kindly complete within 2 days. Good luck for your work!

**Comment by root-0101** [comment]
- Done #288
