### ISSUE TITLE
About us page UI is not up to the mark. I want to improve it 

### ISSUE THREAD

**Issue by Mehulsingh1010** [HimanshuNarware/Devlabs#287]
![Screenshot 2024-05-13 212606](https://github.com/HimanshuNarware/Devlabs/assets/137038233/cae1e86e-6690-4d4a-b6e7-9bbe64c3e03c)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Mehulsingh1010, I have Assigned this task to you. Kindly complete within 2 days. Good Luck for your Work!

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by NAhmad231** [comment]
Hey I want to work on this issue , I am a beginner and want to explore this field . Please assign this issue to me .
