### ISSUE TITLE
New category

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#289]
**Is your feature request related to a problem? Please describe.**
Adding a new category called "productivity" which contains productivity tools focused for developers 

**Describe the solution you'd like**
Adding the new category 

**Add screenshot**

![Screenshot 2024-05-13 222344](https://github.com/HimanshuNarware/Devlabs/assets/142779809/81f9ecd5-ba27-403a-9544-d7765510dbc3)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @root-0101,  I have Assigned this task to you. Kindly complete within 2 days. Good Luck for your Work!
