### ISSUE TITLE
Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [HimanshuNarware/Devlabs#293]
**Is your feature request related to a problem? Please describe.**
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

**Describe the solution you'd like**
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others. 

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @PradnyaGaitonde,  I have Assigned this task to you. Kindly complete within 4 days. Good Luck for your Work!
