### ISSUE TITLE
Framer web designing tool

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#297]
Framer is a free no-code web designing tool where you can build beautiful websites with ease and publish them.

![Framer](https://github.com/HimanshuNarware/Devlabs/assets/125206920/5b748733-ff94-42c9-af09-642b03100d2e)

Please assign this to me

- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @Chandu6702,  I have Assigned this task to you. Kindly complete within 3 days. Good Luck for your Work!

**Comment by Karthikkariappa08** [comment]
Hi @Chandu6702,
I'm excited to tackle the task on webpage. With my experience in website development using HTML, CSS, and JavaScript.

Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!
