### ISSUE TITLE
[Footer]: Enhance Footer UI with CSS Styling

### ISSUE THREAD

**Issue by Karankumar2004** [HimanshuNarware/Devlabs#299]
As a contributor to our open-source project, my expertise in CSS styling can greatly enhance the user experience by improving the UI of the footer section. This issue focuses on refining the visual presentation, layout, and responsiveness of the footer to align with modern design standards and enhance overall website aesthetics.

Hey @khushminder270, I'm keen to contribute. Could you assign me this issue under GSSoc 24'?

**Comment by panwar8279** [comment]
Hi @Karankumar2004,  I have Assigned this task to you. Kindly complete within 2 days. Good Luck for your Work!

**Comment by Karthikkariappa08** [comment]
Hi ,
I'm excited to tackle the task on  webpage. With my experience in website development using HTML, CSS, and JavaScript.


Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by Karankumar2004** [comment]
I'm already solving the issue!!
