### ISSUE TITLE
Improve Navbar and Footer styling

### ISSUE THREAD

**Issue by vanisharma2003** [HimanshuNarware/Devlabs#300]
This project is absolutely amazing. But as per my views there should be some changes to be done for the styling of navbar and footer. So that it appears more eye catching to users.

**Comment by panwar8279** [comment]
Hi @vanisharma2003,  I have Assigned this task to you, Do this nicely without affecting design. Kindly complete within 2 days. Good Luck for your Work!

**Comment by Karthikkariappa08** [comment]
Hi ,
I'm excited to tackle the task on  webpage. With my experience in website development using HTML, CSS, and JavaScript.


Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by vanisharma2003** [comment]
@panwar8279 dii I have currently worked on this project and I have end sem exam tomorrow.Please provide me extra one day to do this task.

**Comment by himadeepthi1** [comment]
Hello @panwar8279 , I would like to work on this issue , kindly assign this issue to me
