### ISSUE TITLE
Homepage Rendering Issue When Filters Are Used

### ISSUE THREAD

**Issue by saisampath2323** [HimanshuNarware/Devlabs#308]
**Describe the bug**
When navigating to pages like "Bookmarks," "Ethical Hacking," or "About Us," and then applying a filter from the sidebar, the Homepage does not render. The filters apply correctly, but the homepage does not display.

**Expected behavior**
Regardless of the current page, when clicking on sidebar filters such as "All" or "Remote Jobs .. etc," the homepage should render correctly. This issue significantly affects user experience, as the intended content does not display when filters are applied.

**Steps to Reproduce**

1.Go to any page (e.g., "Bookmarks," "Ethical Hacking," or "About Us").
2.Apply a filter from the sidebar (e.g., "All," "Remote Jobs").
3.Observe that the homepage does not render.

**Screenshots**
![Screenshot (62)](https://github.com/HimanshuNarware/Devlabs/assets/149238854/1a2a8372-fc4b-45d2-bf1e-4ab83ac2c7fc)

kindly please assign this issue to me,  i have gone through the website and i am working on this issue...

- [1 ] I have checked the existing issues *
- [1 ] I have read the Contributing Guidelines *
- [1 ] I have starred the repository *
- [ 1] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @saisampath2323, I have assigned this issue to you. Kindly complete within 4 days. Good luck for your Work!

**Comment by saisampath2323** [comment]
@panwar8279 thank you for merging the pr could you please kindly add gssoc label to the issue so that it can be counted 
Thankyou
