### ISSUE TITLE
Adding Hover effects to the social media icons in the footer.

### ISSUE THREAD

**Issue by shreyyq** [HimanshuNarware/Devlabs#310]
I propose adding a hover effect to the social media icons located in the footer of the website. Currently, the icons remain static, but implementing a hover effect would enhance user interaction and add a dynamic element to the design.

Adding a hover effect aligns with modern web design principles and enhances the overall user experience. It adds interactivity to the website, which can help engage visitors and encourage them to explore our social media channels.

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Nirvanjha2004** [comment]
hey  can u assign me this issue ??

**Comment by panwar8279** [comment]
Hi @shreyyq,  I have assigned this work to you. Kindly complete within 2 days. Good luck for your Work!

**Comment by shreyyq** [comment]
> Hi @shreyyq, I have assigned this work to you. Kindly complete within 2 days. Good luck for your Work!

Hi Thank You @panwar8279 , can you please add gssoc label too!
