### ISSUE TITLE
Apidog API Testing and Documenting Tool

### ISSUE THREAD

**Issue by DonaldReddy** [HimanshuNarware/Devlabs#312]
Apidog is an API Testing and Documentation tool, Apidog is a complete set of tools that connects the entire API lifecycle,
helping R&D teams implement best practices for API Design-first development.

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/83972294/3d38f267-8817-44e2-854c-3a38240ee812)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @DonaldReddy, I have assigned this task to you. Kindly complete within 4 days. Good luck!
