### ISSUE TITLE
Feature request: Display a proper message when no results found for the search

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [HimanshuNarware/Devlabs#313]
Currently, if no results found for a search the page remains empty.

![Screenshot 2024-05-15 143238](https://github.com/HimanshuNarware/Devlabs/assets/139672976/4323a877-4d22-49b6-9f2e-50e2df86d3fb)

It will be great user experience if we display something like below

![image](https://github.com/HimanshuNarware/Devlabs/assets/139672976/3f7c2e56-e933-481e-a49b-10db99abc6b3)

Checklist
Example  Fill x { [x] }  into  bracket

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24

**Comment by Nirvanjha2004** [comment]
Hey @HimanshuNarware  Can i work on this issue?/

**Comment by panwar8279** [comment]
Hi @DharshiBalasubramaniyam,  I have assigned this issue to you. Kindly complete within 4 days. Good luck for your Work!

**Comment by DharshiBalasubramaniyam** [comment]
> Hi @DharshiBalasubramaniyam, I have assigned this issue to you. Kindly complete within 4 days. Good luck for your Work!

Thank you mam. I'll finish within 4 days
