### ISSUE TITLE
The Color of the component after clicking it in the navbar is not contrast with respect to Navbar Background Color

### ISSUE THREAD

**Issue by nayakswadhin** [HimanshuNarware/Devlabs#314]
**Describe the bug**
The color of the text of component in navbar is not contrast to the background color of the navbar due to which it is becoming harder to distinguish the text and also not looking good.

**Expected behavior**
The text color should be rgb(72, 5, 5) ie the color we get when we hover so after clicking it, it should hold the color and it will also look good.

**Screenshots**
![Screenshot (147)](https://github.com/HimanshuNarware/Devlabs/assets/114871538/dd6910c8-deab-4bd1-8d45-6f78fe685ca8)

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by SaranshKhandelwal977** [comment]
Hi, please assign this issue to me under GSSOC'24

**Comment by panwar8279** [comment]
Hi @nayakswadhin,  I have assigned this task to you. Kindly complete within 4 days. Good luck!
