### ISSUE TITLE
The overall design of header tile needs to be refined and improved.

### ISSUE THREAD

**Issue by Anshravicode89** [HimanshuNarware/Devlabs#322]
- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Anshravicode89** [comment]
Please assign the task of overall design improvement to me under gssoc 24. I have advanced skill in styling(CSS) and participated in many hackathons and projects

**Comment by panwar8279** [comment]
Hi @Anshravicode89,  I have assigned this task to you. Kindly complete within 3 days. Good luck!
