### ISSUE TITLE
Home button issue in sidebar

### ISSUE THREAD

**Issue by IrfanSalim** [HimanshuNarware/Devlabs#33]
**Describe the bug**
The 'Home' button on the sidebar is taking a different route ("/home") than the "Home" hyperlink on the navbar ("/"). It leads to a blank page with no navbar present

**To Reproduce**
1. Go to 'Sidebar'
2. Click on 'Home'
3. See error

**Expected behavior**
The route should be the same for both links.

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/109443065/c806f4c7-354c-4a55-a4f1-6323fc54de1d)

**Comment by IrfanSalim** [comment]
Please assign this to me.

Thank you

**Comment by HimanshuNarware** [comment]
@IrfanSalim  Assigned you

**Comment by IrfanSalim** [comment]
Please add the relevant tags under Hacktoberfest, thank you.

**Comment by prafull904434** [comment]
sir,
may i work this issue ,
can you assign to me

**Comment by HimanshuNarware** [comment]
> sir, may i work this issue , can you assign to me

@prafull904434 it already resolved, feel free to create more issues.
