### ISSUE TITLE
The Hovering of div and buttons is not Smooth

### ISSUE THREAD

**Issue by Shelbybosss** [HimanshuNarware/Devlabs#331]
The hovering animation of div and button is not smooth and does not give good experience.

I will make the hovering of div and button smooth and it will give website a good feel.

![issue](https://github.com/HimanshuNarware/Devlabs/assets/102911609/24d98976-86bb-4abb-8e1b-ab1136501d4d)

Checklist
Example  Fill x { [x] }  into  brack

- [ x ] I have checked the existing issues *
- [ x ] I have read the Contributing Guidelines *
- [ x ] I have starred the repository *
- [ x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Shelbybosss,  I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by Shelbybosss** [comment]
Completed the task, and created a pull request.
