### ISSUE TITLE
Search bar is not visible in the mobile view.

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#332]
**Describe the bug**

When i browse the website in mobile view then i didn't see the search bar maybe the search bar is hiding behind any other container .

**Expected behavior**

The search bar will be shown on the screen 

**Screenshots**

![Screenshot 2024-05-16 195253](https://github.com/HimanshuNarware/Devlabs/assets/118350936/89ab43c8-ab53-413b-9f84-eb6d6615141a)

Example  Fill x { [x] }  into  bracket

- [ x ] I have checked the existing issues *
- [  x] I have read the Contributing Guidelines *
- [ x ] I have starred the repository *
- [  x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211,  I have assigned this task to you. Kindly complete within 2 days. Good luck!
