### ISSUE TITLE
Chatbot for answering user queries

### ISSUE THREAD

**Issue by Astha86** [HimanshuNarware/Devlabs#335]
**Is your feature request related to a problem? Please describe.**

A Chatbot can be deployed for answering any user Queries

**Describe the solution you'd like**
Deploying a Chatbot on website that will be enhance the user experience.

Checklist

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

Kindly assign me this issue @HimanshuNarware  under GSSOC'24 ,
We can discuss for more Features deployment on your website, I would be happy to contribute to your project.
Thank You

**Comment by panwar8279** [comment]
Hi @Astha86,  I have assigned this task to you. Kindly complete within 2 days. Good luck!
