### ISSUE TITLE
feature enhancement : updating the screen on typing any search input in the search bar, if the input matches with any of the tools name's spelling

### ISSUE THREAD

**Issue by anwesha2002** [HimanshuNarware/Devlabs#337]
**Is your feature request related to a problem? Please describe.**
I want to update the screen of entering any search input in the search bar . As of now after typing the entire tool name in the search when users click on the search icon then it is showing on the screen. So it is making difficult for user to know that that any tool name with the letter of input whether exist or not

**Describe the solution you'd like**
I want to modify the screen or update the screen as soon as user type any search input , if any tools have the name speeling related to the search input. 
- it will enhance the search time 
- it will help user to choose the tools in a better way

** Add screenshot 

https://github.com/HimanshuNarware/Devlabs/assets/116761608/14e05f10-461c-4a3f-915d-cf4af4c98aac

Checklist
Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @anwesha2002,  I have assigned this task to you. Kindly complete within 2 days. Good luck!
