### ISSUE TITLE
Netlify devtol link is not attached to a link, rather it has only the logo of netlify

### ISSUE THREAD

**Issue by anwesha2002** [HimanshuNarware/Devlabs#338]
**Describe the bug**
Netlify devtol link is not attached to a link, rather it has only the logo of netlify

**Expected behavior**
It should be attached to a link , instead of a logo

**Screenshots**
![Screenshot 2024-05-16 161322](https://github.com/HimanshuNarware/Devlabs/assets/116761608/afbe938c-469f-4a55-ab8f-efd670dbc65a)

Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @anwesha2002,  I have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by Manaswini123456** [comment]
@panwar8279 Kindly assign this issue to me. As a full stack developer, I have the comprehensive knowledge and expertise required to handle it effectively.
