### ISSUE TITLE
Introduce IDEs as a new category and add resourses to it

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [HimanshuNarware/Devlabs#346]
Integrated Development Environment (IDE) is a software application that provides comprehensive facilities to computer programmers for software development.

I would like to add this as a new category and add some resources to it.

Resources are : intellij, vocoder, androidtuudio, pycharm and so on.

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @DharshiBalasubramaniyam, I am assigning you this task. Kindly complete within 3 days. Good luck!

**Comment by DharshiBalasubramaniyam** [comment]
Thank you @panwar8279 for assigning me
