### ISSUE TITLE
[Enhancement]  Smooth Hover Effect on Contact Us Icons

### ISSUE THREAD

**Issue by carolinelall** [HimanshuNarware/Devlabs#348]
I want to add a smooth hover effect on contact us ICONS which are present inside footer.

I also want to slow down transition speed when anyone hovers over the icon so that it can give a nice effect.

![WhatsApp Image 2024-05-17 at 2 24 40 PM](https://github.com/HimanshuNarware/Devlabs/assets/51926095/3f868eb7-2410-44e8-bf20-2fc58f77dc42)

@panwar8279  Ma'am Pls assign this issue to me. 

- [✔] I have checked the existing issues *
- [ ✔] I have read the Contributing Guidelines *
- [✔ ] I have starred the repository *
- [✔ ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @carolinelall , I am assigning you this task. Kindly complete within 3 days. Good luck!
