### ISSUE TITLE
Over flow issue

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#35]
Over flow issue on the sidebar during hover state
![img4](https://github.com/HimanshuNarware/Devlabs/assets/83147410/fd50b58f-5224-4962-bf95-256e3f90dcbb)

**Comment by OgaDavid** [comment]
Hi @HimanshuNarware i'd love to fix this issue under hacktoberfest. Please assign it to me. Thank you!

**Comment by theavitw** [comment]
I am willing to work on this @HimanshuNarware

**Comment by OgaDavid** [comment]
Hi @HimanshuNarware can I please be assigned this issue under hacktoberfest. 🙌

**Comment by Anayverma** [comment]
Hey @HimanshuNarware  Please assign this issue to me. I would like to work on this issue
.

**Comment by HimanshuNarware** [comment]
@Anayverma  Assigned you

**Comment by Anayverma** [comment]
Hey @HimanshuNarware 
#35 Over flow issue resolved #206
I have solved issues along with additional features, please review and merge.
