### ISSUE TITLE
Adding animations to the Page on loading and scrolling

### ISSUE THREAD

**Issue by MHusain22** [HimanshuNarware/Devlabs#350]
**New Feature**
I can Add animations to the Page on loading and scrolling just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.

-  I have checked the existing issues *
- I have read the Contributing Guidelines *
- I have starred the repository *
-  Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @MHusain22, I am assigning you this task. Kindly complete within 3 days. Good luck!

**Comment by MHusain22** [comment]
@panwar8279 Yes I will complete it within 3 days.

**Comment by MHusain22** [comment]
@panwar8279 I have added the animations and created a pull request please review it and let me know if any changes.

**Comment by MHusain22** [comment]
@panwar8279 please add the label of gssoc and level 2 in the merged pull request.
