### ISSUE TITLE
Adding Whimsical

### ISSUE THREAD

**Issue by m-tabish** [HimanshuNarware/Devlabs#352]
Whimsical is a collaborative tool for teams to come together to brainstorm ideas for their next big project.

**Describe the solution you'd like**
Add the Link to Whimsical

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/67482503/5ff3f698-865c-475d-82cd-921f31beae2d)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

Kindly Assign this issue to me and 
# Add the labels gssoc24 and level[x] label please so that it is counted for the points

**Comment by panwar8279** [comment]
Hi @m-tabish, I am assigning this task to you. Kindly complete within 2 days. Good luck!
