### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [HimanshuNarware/Devlabs#354]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by panwar8279** [comment]
Hi @suhanipaliwal , I am assigning this task to you. Kindly complete within 2 days. Good luck!
