### ISSUE TITLE
UI is not looking Good for page navigation

### ISSUE THREAD

**Issue by Ujjwal807** [HimanshuNarware/Devlabs#355]
**Is your feature request related to a problem? Please describe.**
UI and UX for the page navigation and contact us links are not looking good it should be better.
**Describe the solution you'd like**
I can enhance the UI for the mentioned sections, and we should change the hover effects for the contact us links that look weird now so if we change it to a better-looking UI then it should also help in making a better User experience.

Here is the section that I'm talking about
![image](https://github.com/HimanshuNarware/Devlabs/assets/121127299/a4bcc370-fac0-42e3-90c1-afec6af1c38c)

Checklist
- I have checked the existing issues 
- I have read the Contributing Guidelines 
- I have starred the repository 
- Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Ujjwal807 ,I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by simi-9112** [comment]
Hello @panwar8279 I would also like to work on the issue I have prior experience in ui designing and have worked on similar issues. You can check out my previous works here https://drive.google.com/drive/folders/1_96R2o7S2-EZ0r8vpwI7ChpJypkHxzz5.
I would also complete the work within a set deadline. looking forward to your response

**Comment by HimeshSrivastava** [comment]
Hi I want to contribute on this issue. Please allow me.
