### ISSUE TITLE
Adding Discord under a new category of Collaboration

### ISSUE THREAD

**Issue by m-tabish** [HimanshuNarware/Devlabs#361]
**Describe the solution you'd like**
A place where you can belong to a school club, a gaming group or a worldwide art community. Where just you and a handful of friends can spend time together. A place that makes it easy to talk every day and hang out more often.

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/67482503/c490a3de-0c1f-4784-8fcc-2deb02295394)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x]  I have read the Contributing Guidelines *
- [x]  I have starred the repository *
-[x]  Working under Gssoc'24*

# Kindly assign and add labels. Thank you

**Comment by panwar8279** [comment]
Hi @m-tabish , I am assigning this task to you. Kindly complete within 2 days. Good luck!
