### ISSUE TITLE
Adding light mode theme toggle button to the screen

### ISSUE THREAD

**Issue by AdhithiManjunath** [HimanshuNarware/Devlabs#363]
hey @HimanshuNarware , i think adding light mode thewme with a button on top right to switch between light and dark mode would be a great idea . i would like to contribute for thids. please assign me this issue so that i  can contribute.

**Comment by panwar8279** [comment]
Hi @AdhithiManjunath ,  I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by AdhithiManjunath** [comment]
I have resolved it , please do check once and let me know if u need further changes too !! 
Thank you 🙏
