### ISSUE TITLE
Improve Notification Style for Bookmark Added

### ISSUE THREAD

**Issue by panam1916** [HimanshuNarware/Devlabs#364]
I can Add good notification for bookmark added using Toast in React
![bookmark_enhance](https://github.com/HimanshuNarware/Devlabs/assets/92396633/9c424758-25d4-4208-95cd-fc3a8aab2e28)

And also Add notifiaction for Bookmark Removed from Bookmark section

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @panam1916 , I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by panam1916** [comment]
Ok,Thanks for assign it to me!

**Comment by panam1916** [comment]
![solution1](https://github.com/HimanshuNarware/Devlabs/assets/92396633/e840da88-9717-4c05-90cc-f1333be557f9)
![Solution2](https://github.com/HimanshuNarware/Devlabs/assets/92396633/df29f7be-bcba-4005-ad95-18155bfa4392)

which of you want  
do you want to put name of course instead of bookmark or only bookmark

**Comment by panam1916** [comment]
I raise my pr

**Comment by panam1916** [comment]
Hey Can you Tell me why deployment not happen in my PR?

**Comment by panam1916** [comment]
> Hi @panam1916 , I am assigning this task to you. Kindly complete within 2 days. Good luck!

I face some problems today i resolve dit and create new pr

**Comment by panam1916** [comment]
Can you Please Read my problem?

**Comment by panam1916** [comment]
Hi Can you Give me proper way for raise pr i dont know where i face issue
