### ISSUE TITLE
The Text area of review page is not fixed

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#366]
**Describe the bug**
Its size can be changed by dragging it.

**Expected behavior**
If we try to drag it up or down the text area increases or decreases

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/126975547/941412dd-f89f-4d5f-9c38-2577bce46e71)

![image](https://github.com/HimanshuNarware/Devlabs/assets/126975547/3fad642e-553f-4330-8c1b-556461d5b29e)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by ayush-848** [comment]
@panwar8279 I can make the text area fixed and if you permit or instruct, I can make it to not take more than 'N' characters as message.

**Comment by panwar8279** [comment]
Hi @ayush-848 , I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by ayush-848** [comment]
@panwar8279 I have followed the PR template and filled it with the required info.
Please have a look at my PR #391

**Comment by ayush-848** [comment]
@panwar8279 please merge my PR
