### ISSUE TITLE
Icons Are not visible in Contact us section

### ISSUE THREAD

**Issue by anwesha2002** [HimanshuNarware/Devlabs#373]
**Describe the bug**
The icons of the contact US sections are not visible for social links. Instead it is showing some white circle

**Expected behavior**
It should show some Logo of the social links (like linkedIn etc)

**Screenshots**
![Screenshot 2024-05-18 142819](https://github.com/HimanshuNarware/Devlabs/assets/116761608/d171d310-aa5f-4396-8146-ee24bf709126)

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc'24

**Comment by himadeepthi1** [comment]
Hello @panwar8279 , can I work on this issue ?
