### ISSUE TITLE
Remove Unnecessary Pagination Buttons on Project List Page

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#375]
### Description
**Issue:**
The "Previous" and "Next" pagination buttons are currently displayed on the project list page even when there is no additional data to paginate through. This results in an unnecessary user interface element that can be confusing and clutter the page.

**Steps to Reproduce:**
1. Open the project list page on the website to open source.
2. Observe the presence of "Previous" and "Next" buttons at the bottom of the page even when all projects fit on a single page.

**Expected Behavior:**
Pagination buttons should only be displayed when there are enough projects to warrant multiple pages.

**Actual Behavior:**
Pagination buttons are displayed regardless of the number of projects.

**Suggested Fix:**
Implement a check to conditionally render the pagination buttons only when there are enough projects to require pagination.

**Additional Context:**
- The issue can be seen on the project list page Open source.
- This improvement will enhance the user experience by keeping the interface clean and intuitive.

![Screenshot_20240519-103249.png](https://github.com/HimanshuNarware/Devlabs/assets/140513098/45f45b3f-5697-4476-8a2d-af15e44000dd)

**Comment by panwar8279** [comment]
Hi @kushalkumar1362 , I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by kushalkumar1362** [comment]
> Hi @kushalkumar1362, I am assigning this task to you. Kindly complete it within 2 days. Good luck!

I will submit this on May 21st, two days from now, before 10 p.m.

**Comment by kushalkumar1362** [comment]
@HimanshuNarware please change labels

**Comment by kushalkumar1362** [comment]
Why reopened?

**Comment by kushalkumar1362** [comment]
@HimanshuNarware  @panwar8279  Please close this issue as successful completed

**Comment by kushalkumar1362** [comment]
@HimanshuNarware  @panwar8279 CLose this issue as completed
