### ISSUE TITLE
Improvement of the Twitter Logo Icon to X

### ISSUE THREAD

**Issue by vinayakhegde1** [HimanshuNarware/Devlabs#38]
**Describe the bug**
Improvement of the Twitter Logo Icon to X

**Screenshots**
![Devlads contacts](https://github.com/HimanshuNarware/Devlabs/assets/73926849/8c6a70d0-1d74-4edd-b950-6b21fb1ba674)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Brave]
 - Version [1.58]
 
Please Assign me the issue under hacktoberfest

**Comment by vinayakhegde1** [comment]
@HimanshuNarware I've created the PR please do check

**Comment by yash8000** [comment]
assign me this

**Comment by HimanshuNarware** [comment]
@yash8000  assigned you
