### ISSUE TITLE
The social icons on the footer are not visible.

### ISSUE THREAD

**Issue by yashi-15** [HimanshuNarware/Devlabs#380]
**Describe the bug**
The social icons on the footer are not visible due to some bug.

I want to solve this issue under GSSOC'24. Kindly assign it to me, so that I can start working on it.

**Screenshots**

![Screenshot (497)](https://github.com/HimanshuNarware/Devlabs/assets/132138302/dd1a7797-028f-4143-af4f-9e54b3811bbd)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by root-0101** [comment]
Hey @HimanshuNarware please assign me this issue

**Comment by panwar8279** [comment]
Hi @yashi-15,  I am assigning this task to you. Kindly complete within 2 days. Good Luck!
