### ISSUE TITLE
SpinBot  AI Tool

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#390]
SpinBot tool specialty: One-Click Text Summaries With AI Summarizer.
It is a Paraphrasing Tool,AI Grammar Checker, and Text Rewriting Tool.
Have some fun with it! Discover how SpinBot can enhance your writing within seconds

![Screenshot 2024-05-20 133702](https://github.com/HimanshuNarware/Devlabs/assets/125206920/6ddb351f-890c-4e3a-9dfb-ec047f684200)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @Chandu6702,  I am assigning this task to you. Kindly complete within 2 days. Good Luck!
