### ISSUE TITLE
Want to add a new tool to the website

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#392]
To add Hashnode as a tool in the website

Hashnode helps developers, and people in tech connect and share knowledge easily!

Checklist
Example  Fill x { [x] }  into  bracket

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24*

**Comment by ayush-848** [comment]
@panwar8279 please assign this issue to me.

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.

**Comment by panwar8279** [comment]
Hi @ayush-848,  I am assigning this task to you. Kindly complete within 2 days. Good Luck!

**Comment by ayush-848** [comment]
@panwar8279 I did the tasks in PR #413

**Comment by ayush-848** [comment]
@HimanshuNarware @panwar8279 This task has been completed in PR #461, please do check it.
