### ISSUE TITLE
Adding hover effect to booked card

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#393]
- There is no hover effect in booked card in the bookmark section

![Screenshot 2024-05-20 150444](https://github.com/HimanshuNarware/Devlabs/assets/142779809/06b45106-0617-4b96-babf-1e4e28f27d20)

**Comment by ARPITBAJPAI0098** [comment]
Himanshu boss can you assign this task to me i have a 1 year experience in full stack web developement currently working on nextjs and typescript stack .. worked as a technical executive in Rajasthan largest techno fest Sphinx

**Comment by panwar8279** [comment]
Please do it nicely.

**Comment by root-0101** [comment]
- Thanks for assigning me, I will raised my PR soon with the changes
