### ISSUE TITLE
z-index issue in page number

### ISSUE THREAD

**Issue by Jagpreet153** [HimanshuNarware/Devlabs#397]
**Describe the bug**
The page number section comes over the navbar when user scrolls to bottom

**Expected behavior**
The page number section should remain under navbar

**Screenshots**
![Screenshot 2024-05-20 182316](https://github.com/HimanshuNarware/Devlabs/assets/119691733/30bb1614-270e-46cf-a2b5-75acee559bb0)

![Screenshot 2024-05-20 182332](https://github.com/HimanshuNarware/Devlabs/assets/119691733/c2a2c3b5-0634-4c13-aa2f-20e5a862ceba)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Jagpreet153 , I am assigning this issue to you. Kindly complete within 2 days. Good luck!
