### ISSUE TITLE
Footer Icons not visible

### ISSUE THREAD

**Issue by avayyyyyyy** [HimanshuNarware/Devlabs#401]
**Describe the bug**

footer icons are not visible
please assign this issue to me

<img width="204" alt="image" src="https://github.com/HimanshuNarware/Devlabs/assets/111121419/16767cbc-ee63-4ddf-9e4a-b68bae0daba0">

Example  Fill x { [x] }  into  bracket

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [ x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Someone is already working on it.
