### ISSUE TITLE
[Feat]: Auto Commenting when an Issue is Closed by maintainer

### ISSUE THREAD

**Issue by Asymtode712** [HimanshuNarware/Devlabs#408]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to the problem of lack of communication and acknowledgment when issues are closed in the repository. Contributors may feel neglected or uncertain about the status of their issues if they are closed without any feedback or acknowledgment. This can lead to frustration and a decrease in motivation to contribute further.

**Describe the solution you'd like**
The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.

**Add screenshot**

![issue closed](https://github.com/HimanshuNarware/Devlabs/assets/115717746/579ecf2e-4312-4008-92c7-a82875838632)

**Checklist**

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24

**Comment by Asymtode712** [comment]
@panwar8279 please assign me this issue under gssoc'24

**Comment by Asymtode712** [comment]
@panwar8279 kindly assign me this issue too

**Comment by panwar8279** [comment]
Hi @Asymtode712,  I am assigning this task to you. Kindly complete within 3 days. Good luck!
