### ISSUE TITLE
[Feat]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [HimanshuNarware/Devlabs#410]
**Is your feature request related to a problem? Please describe.**
Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

**Describe the solution you'd like**
Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

**Checklist**

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24

**Comment by Asymtode712** [comment]
@panwar8279 please assign me this issue under gssoc'24

**Comment by panwar8279** [comment]
Hi @Asymtode712,  I am assigning this task to you. Kindly complete within 4 days. Good Luck!
