### ISSUE TITLE
Footer section is not working properly in Dark Mode and Light Mode

### ISSUE THREAD

**Issue by panwar8279** [HimanshuNarware/Devlabs#411]
If someone want to working in it. Then I will assign to them.
![Screenshot_2024-05-21-08-28-58-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/HimanshuNarware/Devlabs/assets/102457440/0bf78871-73d7-4cf0-bb00-f2668c6513ac)

**Comment by DonaldReddy** [comment]
@panwar8279 I would like to work on this issue.

**Comment by panwar8279** [comment]
Hi @DonaldReddy , I am assigning this issue to you. Kindly complete it as soon as possible with clean code. Good luck !
