### ISSUE TITLE
Modify Hero image

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#418]
- The image used on Hero section is blur not in high quality , that affects the users experience.

![Screenshot 2024-05-21 140520](https://github.com/HimanshuNarware/Devlabs/assets/142779809/6ca4b5e1-fb55-41fa-86fe-0926a1d138af)

**Comment by panwar8279** [comment]
Hi @root-0101 ,  I am assigning this task to you. Kindly complete within 2 days. Good luck!
