### ISSUE TITLE
Redesign footer section

### ISSUE THREAD

**Issue by Vanicoding27** [HimanshuNarware/Devlabs#420]
I want to redesign the footer section using media query for better experience in mobile screens as well.

![b5a6f133-899f-4edf-8abc-ba6031319ac6](https://github.com/HimanshuNarware/Devlabs/assets/165997406/ee42f02c-3d45-4b62-b2a3-63eda158a6c2)

**Comment by panwar8279** [comment]
Hi @Vanicoding27,  I am assigning this task to you. Kindly complete within 4 days and also solve dark mode & light mode issue in footer section. Good luck for your work!
