### ISSUE TITLE
Issue in Navbar !!

### ISSUE THREAD

**Issue by Jivi-this-side** [HimanshuNarware/Devlabs#423]
**Describe the bug**
As u can see in ss the last row is unwanted and would like to make navbar component more clean and organised! 
 I am to updated navbar!

**Screenshots**

<img width="1440" alt="Screenshot 2024-05-21 at 6 29 41 PM" src="https://github.com/HimanshuNarware/Devlabs/assets/156334435/0bc55ca2-ce32-46a3-a042-92521d249fe5">

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by Jivi-this-side** [comment]
@panwar8279 please assign me this issue under gssoc'24

**Comment by panwar8279** [comment]
Hi @Jivi-this-side , I am assigning this task to you. Kindly complete within 2 days. Good luck!
