### ISSUE TITLE
Mode icon needs to be replaced somewhere else because it is hiding content of header 

### ISSUE THREAD

**Issue by kapilG0** [HimanshuNarware/Devlabs#428]
**Is your feature request related to a problem? Please describe.**
Mode icon needs to be replaced somewhere else because it is hiding content of header 

**Describe the solution you'd like**

** Add screenshot 

![Screenshot_20240521_212102](https://github.com/HimanshuNarware/Devlabs/assets/59639410/961eeec1-e2fc-4263-9c31-01435e98c150)

Checklist
Example  Fill x { [x] }  into  bracket

- [ ] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by kapilG0** [comment]
Hello @HimanshuNarware please assign this issue to me under gssoc 24

**Comment by panwar8279** [comment]
Hi @kapilG0 , I am assigning this issue to you. Kindly complete within 3 days. Good luck!

**Comment by kapilG0** [comment]
Hello @panwar8279 I raised pr for this issue https://github.com/HimanshuNarware/Devlabs/pull/432. Please check and any modifications required let me know. Thank you.

**Comment by EmazinUs** [comment]
Hello @HimanshuNarware please assign this issue to me under gssoc 24
