### ISSUE TITLE
Data is hiding in footer in mobile view 

### ISSUE THREAD

**Issue by kapilG0** [HimanshuNarware/Devlabs#429]
**Is your feature request related to a problem? Please describe.**
Data is hiding in footer in mobile view 

**Describe the solution you'd like**

** Add screenshot 

![Screenshot_20240521_212346](https://github.com/HimanshuNarware/Devlabs/assets/59639410/8d7f29a9-f88e-4d88-9d78-e4b24f1ff591)

Checklist
Example  Fill x { [x] }  into  bracket

- [ ] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [ ] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by kapilG0** [comment]
Hello @HimanshuNarware please assign this issue to me under gssoc 24

**Comment by panwar8279** [comment]
Hi @kapilG0  , I am assigning this issue to you. Kindly complete this within 4 days. Good luck!

**Comment by ravijat2026** [comment]
Hello @HimanshuNarware Please assign me this issue.
