### ISSUE TITLE
Pagination is causing issues (All tools are not loading on the homepage)

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#43]
**Describe the bug**
the current number of items is not showing on the home  page

**Comment by insane-22** [comment]
Hey @HimanshuNarware, I would like to contribute to your project under hactoberfest 2023.
Could you please assign the issue to me?
I plan to add a div just above pagination, displaying "Showing {x} to {y} form {total}"
Your feedback would be highly appreciated,
Thank you for your consideration!

**Comment by insane-22** [comment]
Hello @HimanshuNarware 
Thanks for assigning me the issue!
I've made certain additions and the page looks like this:-
![image](https://github.com/HimanshuNarware/Devlabs/assets/116253210/c2001b5b-9641-4673-ad09-4566b5aa6f44)
Is it ok or do you expect anything ele?

**Comment by HimanshuNarware** [comment]
> Hello @HimanshuNarware Thanks for assigning me the issue! I've made certain additions and the page looks like this:- ![image](https://user-images.githubusercontent.com/116253210/272480281-c2001b5b-9641-4673-ad09-4566b5aa6f44.png) Is it ok or do you expect anything else?

@insane-22  nice, but can share a 15 sec video of you changes

**Comment by insane-22** [comment]
@HimanshuNarware Yeah, sure!
Video of website:-

https://github.com/HimanshuNarware/Devlabs/assets/116253210/4b723661-0816-4bce-85c1-b3ade9af9601


Files changed:- Pagination.css and Home.js

**Comment by insane-22** [comment]
Hey @HimanshuNarware ! Kindly approve the changes so that I may submit a pull request for the same.
