### ISSUE TITLE
Adding New Twitter logo

### ISSUE THREAD

**Issue by PrashantAnand03** [HimanshuNarware/Devlabs#436]
**Describe the bug**
The Twitter logo used in this project is outdated. It will be changed to the updated version.

**Expected behavior**
In DEVLAPS, the outdated Twitter logo is causing a bug; I will fix this issue by removing the old logo and replacing it with the updated version, which features the X symbol.

**Screenshots**
![DEVLAPS_old twitter logo](https://github.com/HimanshuNarware/Devlabs/assets/106450463/eff37f16-a360-400d-af2f-7fe0da50bc39)

Example  Fill x { [x] }  into  bracket

- [Yes ] I have checked the existing issues *
- [Yes] I have read the Contributing Guidelines *
- [Yes] I have starred the repository *
- [Yes] Working under Gssoc'24

**Comment by PrashantAnand03** [comment]
I would like to work on this issue. Please assign me to it and label it under GSSoc '24. Also, categorize it as level (1, 2, or 3). I have implemented the same change in my recent project, so I could easily fix this issue.

**Comment by panwar8279** [comment]
Hi @PrashantAnand03 , I am assigning this task to you. Kindly complete within 2 days. Good luck!
