### ISSUE TITLE
To enhance text readability 

### ISSUE THREAD

**Issue by PrashantAnand03** [HimanshuNarware/Devlabs#437]
**Describe the bug**
sentence is mostly correct but some changes can be made in order to Simplify the structure for better readability.

**Expected behavior**
1. Devlabs is an application that is used to search for free tools that are both free and helpful for our needs. It is built by the amazing open-source community.   
 In your project's "About Us" section, "free" is repeated twice. Instead, you can write:

"Devlabs is an application used to search for tools that are both free and helpful for our needs. It is built by the amazing open-source community."

2. Great things are never created in isolation. Thanks to our amazing contributors, we've brought this product to life. With your help, we can continue to make it even better. If you're a developer or a tech enthusiast, you can help us create a better experience for everyone. We are excited to hear your thoughts and ideas.
In your project's "About Us" section, the second paragraph can be improved for readability by removing "And" at the beginning. Additionally, "Contributors" and "Developer" should be Lowercase for consistency. Instead, you can write:

"Great things are never created in isolation. Thanks to our amazing contributors, we've brought this product to life. With your help, we can continue to make it even better. If you're a developer or a tech enthusiast, you can help us create a better experience for everyone. We are excited to hear your thoughts and ideas."

**Screenshots**
![readability-1](https://github.com/HimanshuNarware/Devlabs/assets/106450463/4a8947a9-7cd2-4084-8a84-4781488d3636)
![readability-2](https://github.com/HimanshuNarware/Devlabs/assets/106450463/1286d21a-14b8-4917-bc1d-85a17b791a6b)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by PrashantAnand03** [comment]
I would like to work on this issue. Please assign me to it and label it under GSSoc '24. Also, categorize it as level (1, 2, or 3). I  can easily fix this issue, which will enhance consistency and readability.

**Comment by panwar8279** [comment]
Hi @PrashantAnand03 , I am assigning this task to you. Kindly complete within 2 days. Good luck!
