### ISSUE TITLE
Modify the buttons 

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#438]
- It would be great if we also Modify all the Tools card buttons as per the image mentioned below

![Screenshot 2024-05-22 011132](https://github.com/HimanshuNarware/Devlabs/assets/142779809/6424f07d-faab-48fc-aab2-98832ec789f0)

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by mtg718** [comment]
Please assign this isue to me
