### ISSUE TITLE
Organizing Sections by Adding 'Explore' Category

### ISSUE THREAD

**Issue by PrashantAnand03** [HimanshuNarware/Devlabs#441]
**Is your feature request related to a problem? Please describe.**
organizing the sections of the project by adding a new category named "Explore." This addition will help users easily navigate and discover relevant resources related to Frontend tools, ethical hacking, coding platforms, and course platforms.
**Describe the solution you'd like**
I will name the third category section which lists (Frontend tools, ethical hacking, coding platforms, and course platforms.) as  Explore it will effectively Communicate the purpose of the section. to provide users with a platform to discover various resources 

** Add screenshot 
![idea-1](https://github.com/HimanshuNarware/Devlabs/assets/106450463/35233caf-c0d5-49e6-bd1c-9b35817881ec)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by PrashantAnand03** [comment]
I would like to work on this issue. Please assign me to it and label it under GSSoc '24. Also, categorize it as level (1, 2, or 3). I can easily fix this issue, after naming "Explore" it will effectively Communicate the purpose of the Section.

**Comment by panwar8279** [comment]
Hi @PrashantAnand03 , I am assigning this task to you. Kindly complete within 4 days. Good luck!
