### ISSUE TITLE
Next button position

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#442]
**Describe the bug**
 - When the next button is on active state it's position in not right and is visible over the navbar

**Expected behavior**
- It should not visible over the navbar

**Screenshots**

![Screenshot 2024-05-22 031815](https://github.com/HimanshuNarware/Devlabs/assets/142779809/c664866f-65c7-409a-a9d5-7bcecde71c5a)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete within 2 days. Good luck!
