### ISSUE TITLE
makking footer attractive texts are not visible

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [HimanshuNarware/Devlabs#443]
**Describe the bug**

**Expected behavior**

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/125277258/830cabd3-b929-444e-a1c7-7e1e72d095d2)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @RamakrushnaBiswal , I am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by RamakrushnaBiswal** [comment]
@panwar8279 sure

**Comment by RamakrushnaBiswal** [comment]
PR #454 solved issue.
