### ISSUE TITLE
Fixing navigation bar issue

### ISSUE THREAD

**Issue by Vanicoding27** [HimanshuNarware/Devlabs#446]
There is a issue as scroll bar is hiding behind the navigation bar.
Assign this task to me so that I can fix the problem.

![Screenshot (496)](https://github.com/HimanshuNarware/Devlabs/assets/165997406/e202236e-cf37-41d4-ab37-d2a1e4cb1bdf)

**Comment by arpit4521** [comment]
Please assign me this issue so that i can start working , please assign me this issue under gssoc label @HimanshuNarware  as i have not got any assigned  yet and wanted to learn open source
