### ISSUE TITLE
Image text overlapping in about US

### ISSUE THREAD

**Issue by dev04sa** [HimanshuNarware/Devlabs#447]
**Describe the bug**
Image text overlapping in about US section and some space is required over there.
i can fix it . kindly assign it to me.

**Expected behavior**
there should be some padding from bottom
**Screenshots**
![Screenshot 2024-05-22 123922](https://github.com/HimanshuNarware/Devlabs/assets/129666293/d59e9180-de28-46ea-b596-bac28ba294de)

Example  Fill x { [x] }  into  bracket

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @dev04sa , I am assigning this task to you. Kindly complete within 2 days. Good luck!
