### ISSUE TITLE
Page should scroll down when we search for a tool

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#448]
**Is your feature request related to a problem? Please describe.**

The Page should scroll down when we search for a tool to show results.
If not First-time users may get confused by it.

**Describe the solution you'd like**

The page should scroll down to show results when we search for a tool.

** Add screenshot 

https://github.com/HimanshuNarware/Devlabs/assets/125206920/0106dfb0-e045-4d6e-90ed-c25f4f4220b8

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Chandu6702 , I am assigning this task to you. Kindly complete within 2 days. Good luck!
