### ISSUE TITLE
Redesign Review page

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#459]
- Redesign the review page would enhance the user experience, and the submit is not outstand after hovering on it light mode

![Screenshot 2024-05-22 185903](https://github.com/HimanshuNarware/Devlabs/assets/142779809/039117dc-765c-4012-b4ee-566a5f8a8a4d)

**Comment by EmazinUs** [comment]
Please assign this job to me ,I can do really good work in this

**Comment by panwar8279** [comment]
Hi @root-0101,  I am assigning this task to you. Kindly complete this task within 2 days. Good Luck!
