### ISSUE TITLE
Adding Slidesgo(AI Presentation Maker)

### ISSUE THREAD

**Issue by riyaguptaa-01** [HimanshuNarware/Devlabs#463]
Slidesgo offers an extensive catalog of free Google Slides themes and PowerPoint templates for creative presentations. These are customizable to better suit the needs of any given user, so the possibilities are endless.
It also offers a feature which helps to create presentations in one click using AI.

screenshot
![image](https://github.com/HimanshuNarware/Devlabs/assets/147939046/2b7f780f-2fbd-433e-9a1d-363f5848ad93)

Checklist

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by riyaguptaa-01** [comment]
Kindly assign this issue to me @panwar8279 @HimanshuNarware

**Comment by panwar8279** [comment]
hi @riyaguptaa-01 , I am assigning this task to you. Kindly complete this task within 2 days. Good Luck!
