### ISSUE TITLE
Padding and Position issue 

### ISSUE THREAD

**Issue by Vanicoding27** [HimanshuNarware/Devlabs#469]
There is a issue I have shown you below in the screenshot and also provide the screenshot after solving the problem. 
I want to improve it for better user experience, kindly assign this task to me.

![Screenshot (503)](https://github.com/HimanshuNarware/Devlabs/assets/165997406/124bf5e5-4dd0-440d-a29d-94a19109612f)

![Screenshot (497)](https://github.com/HimanshuNarware/Devlabs/assets/165997406/d933ecf1-e050-4bcc-9870-e3ad0587a6b2)

**Comment by panwar8279** [comment]
Hi @Vanicoding27 , Please share the demo video in both dark and light modes.

**Comment by Vanicoding27** [comment]
I send the PR as style change #511 please merge the PR 

https://github.com/HimanshuNarware/Devlabs/assets/165997406/b8675700-f8bd-46dc-a8c4-4ab10a62eaa9
