### ISSUE TITLE
Adding hover effect to the ChatBot icon while both opening and closing

### ISSUE THREAD

**Issue by Amruta7203** [HimanshuNarware/Devlabs#470]
**Is your feature request related to a problem? Please describe.**
ChatBot icon remains the same when the mouse is hovered which makes it less visually appealing.

**Describe the solution you'd like**
I would like to include hovering for the chatbot icon before opening and while closing it.

** Add screenshot 
Before opening:
![image](https://github.com/HimanshuNarware/Devlabs/assets/116087736/9d2fca61-a1d4-4b6c-a161-1f025af24fe5)

While closing:
![image](https://github.com/HimanshuNarware/Devlabs/assets/116087736/12222d91-03ff-4086-8e8b-76abdf5cbe88)

Checklist
Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by Amruta7203** [comment]
@HimanshuNarware Request you to assign this issue to me under GSSOC'24.

**Comment by panwar8279** [comment]
hi @Amruta7203 ,  i am assigning this issue to you, kindly complete within 3 days. Good Luck!
