### ISSUE TITLE
Redirecting Social Media links to a New Tab

### ISSUE THREAD

**Issue by Amruta7203** [HimanshuNarware/Devlabs#471]
**Is your feature request related to a problem? Please describe.**
The social media links like linkedIn and Twitter opens on the same page on which the website is open. This decreases the user convenience.

**Describe the solution you'd like**
I propose redirecting the social media links to ensure that the links open in a new tab.

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Amruta7203 ,  i am assigning this issue to you, kindly complete within 2 days. Good Luck!
