### ISSUE TITLE
Contribution bug

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#472]
Describe the bug

# **On clicking next, it displays as follows.**

![Screenshot_20240523-105310.png](https://github.com/HimanshuNarware/Devlabs/assets/140513098/d2e09c25-4229-4c9d-b29f-e8153cfda577)

![Screenshot_20240523-105338.png](https://github.com/HimanshuNarware/Devlabs/assets/140513098/492a153d-f1a6-4647-8acc-7fbc028da144)

# Expected behavior
Here, we observe two issues:

in the above picture, it should display Showing 25-29 from 29 results. Or don't show negative if the user pres prev.

It is allowed to click on next indefinite times, even though it has nothing to display.

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by kushalkumar1362** [comment]
#328 is unable to be solved within the time limit please assign this to me.

**Comment by kushalkumar1362** [comment]
@panwar8279 @HimanshuNarware please assign this to me

**Comment by panwar8279** [comment]
@kushalkumar1362 , please start working on it.

**Comment by kushalkumar1362** [comment]
> @kushalkumar1362 , please start working on it.

Ok, I will try to complete this withIn 2,3 days because I have to go to the hospital due to a health issue.
