### ISSUE TITLE
Custom scroll bar for the side Navbar

### ISSUE THREAD

**Issue by Amruta7203** [HimanshuNarware/Devlabs#474]
**Is your feature request related to a problem? Please describe.**
The default scroll bar seems to decrease user experience. 

**Describe the solution you'd like**
Customizing the scroll bar for the side Navigation bar enhances the user interface and gives better user experience.

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/116087736/8476dd75-14d6-4a8c-98b9-73bf363d7273)

Checklist
Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
hi @Amruta7203 ,  i am assigning this issue to you, kindly complete within 2 days. Good Luck!
