### ISSUE TITLE
Prealoader

### ISSUE THREAD

**Issue by Jagpreet153** [HimanshuNarware/Devlabs#475]
**Is your feature request related to a problem? Please describe.**
Yes ,  adding a preloader will increase the interest of user in the website . So that it does not look boring 

**Describe the solution you'd like**
I would be adding a preloader , a short animation which renders until the page is fully loaded

** Add screenshot 
![Screenshot 2024-05-23 115821](https://github.com/HimanshuNarware/Devlabs/assets/119691733/869981e7-71d3-4e94-bef6-8bdf8e84fb57)

Checklist

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Jagpreet153 ,  i am assigning this issue to you, kindly complete within 3 days. Good Luck!
