### ISSUE TITLE
Important for gssoc

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#478]
### Discussed in https://github.com/HimanshuNarware/Devlabs/discussions/457

<div type='discussions-op-text'>

<sup>Originally posted by **kushalkumar1362** May 22, 2024</sup>
Please assign a label in PR otherwise points will be not counted 😕 

![image](https://github.com/HimanshuNarware/Devlabs/assets/140513098/5f5a2b9a-2059-4b95-aa0d-8e009df1b0ca)

Level 3 -->
https://github.com/HimanshuNarware/Devlabs/pull/384

Level 1-->
https://github.com/HimanshuNarware/Devlabs/pull/316

Level 2 --> 
https://github.com/HimanshuNarware/Devlabs/pull/290

</div>

**Comment by panwar8279** [comment]
@kushalkumar1362 , Thanks for reminding.
