### ISSUE TITLE
Enhanced Chatbot Functionality with Activity-based History Storage.

### ISSUE THREAD

**Issue by AnkitLuhar** [HimanshuNarware/Devlabs#483]
**Is your feature request related to a problem? Please describe.**

Users are often frustrated when the chatbot closes upon re-clicking the bot button. This disrupts the user experience and diminishes the website's professionalism. Additionally, there is currently no provision for users to view their chatbot interaction history, which limits usability and continuity.

**Describe the solution you'd like:**

**Solution Proposed:**

**1.Retain Chatbot Open State:** Adjust the chatbot behavior so that clicking the bot button again does not close the chatbot. This will ensure continuity in the user experience and prevent frustration.

**2.Close Chatbot on External Click:** Modify the chatbot functionality to close only when users click outside the chatbot area. This will provide a more intuitive user experience and prevent inadvertent closure of the chatbot.

**3.Implement Chatbot History:** Introduce a feature that stores the chatbot conversation history. This will allow users to review previous interactions, enhancing usability and providing continuity in their conversations with the chatbot.

**Additional context:**
![Screenshot (367)](https://github.com/HimanshuNarware/Devlabs/assets/142730608/6aad8019-0305-43f5-a12c-d639a36a2ad2)

Checklist:

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by AnkitLuhar** [comment]
**This feature request is assigned under GSoc24. Awaiting your feedback to commence work promptly.**

**Comment by panwar8279** [comment]
hi @AnkitLuhar ,  i am assigning this issue to you, kindly complete within 2 days. Good Luck!
