### ISSUE TITLE
Adding new tools

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#485]
**Is your feature request related to a problem? Please describe.**
Adding new tools to collaboration tool category 

**Describe the solution you'd like**
- Github : [Link](https://github.com/) 
- Gitlab : [Link](https://gitlab.com/)  
- Bitbucket : [Link](https://bitbucket.org/)
- Codesandbox : [Link](https://codesandbox.io/)
- Replit : [Link](https://replit.com/)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @root-0101 ,  i am assigning this issue to you, kindly complete within 4 days. Good Luck!

**Comment by root-0101** [comment]
Hey @panwar8279 Please assign me the level for the merged PR
