### ISSUE TITLE
Modify scroll bar

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#486]
Modifying the scroll bar would enhance the overall user experience and increase the engagement of the user

![Screenshot 2024-05-23 222238](https://github.com/HimanshuNarware/Devlabs/assets/142779809/d3d298d9-9ad6-47c9-b882-6fa8955d7977)

**Comment by panwar8279** [comment]
hi @root-0101 , i am assigning this issue to you, kindly complete within 2 days. Good Luck!
