### ISSUE TITLE
[Feature]: The UI of the Dev Labs Main Page is not Interactive and Good-Looking

### ISSUE THREAD

**Issue by Priyanshu2743** [HimanshuNarware/Devlabs#488]
### The Main Page of the Website is not interactive and good looking
As a User, I don't like the Ui of the main landing page of the website 
The UI of it must be enhanced to engage a greater number of users to interact and use the website

### I will make the enhancements in the UI of the website 
** by enhancing the color scheme of the website
** by creating a new logo for the website 
** by using new techniques for improving the UI of the website

### Kindly, Assign me the task of enhancing the UI of the website under GSSOC-2024 and add labels of level and gssoc

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Priyanshu2743 ,  i am assigning this issue to you, kindly complete within 5 days. Good Luck!

**Comment by Priyanshu2743** [comment]
### The way it is coded for the UI of the main page 
will take 2-3 more days for me to make it a better UI as the UI needs a lot of improvement 
So, If you can pls update the level of the Issue to level 3 
It will be helpful and encouraging
