### ISSUE TITLE
[FEAT] : Make Hero Section Responsive for All devices 

### ISSUE THREAD

**Issue by dhruv389** [HimanshuNarware/Devlabs#492]
**Is your feature request related to a problem? Please describe.**

- On smaller screens (e.g., mobile devices), text may overlap or become too small to read.
- Images may not scale correctly, leading to distortion or improper display.
- Layout elements may be positioned awkwardly or off-screen.

**Describe the solution you'd like**

- Use flexible grid layouts and media queries to adjust the hero section's design based on screen size.
- Ensure text scales properly and remains legible on all devices.
- Optimize images to prevent distortion and overflow issues.
- Adjust spacing and positioning of elements for better visual hierarchy and usability.

**Add screenshot**
![image](https://github.com/HimanshuNarware/Devlabs/assets/117587892/913fdc95-b661-499e-a3b7-4c7d242e5c00)

Checklist
Example  Fill x { [x] }  into  bracket

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi, @dhruv389 ,  i am assigning this issue to you; kindly complete within 2 days. Good Luck!

**Comment by Tarungupta18** [comment]
assign me excited to contribute
