### ISSUE TITLE
Booked card content overflow for discord card

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#502]
**Describe the bug**
the content for the discord card overflow in the bookmark category

**Expected behavior**
The content within the card should not overflow 

**Screenshots**
![Screenshot 2024-05-25 123348](https://github.com/HimanshuNarware/Devlabs/assets/142779809/f8604dc1-1207-4319-9d7b-560aa5a5abde)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by root-0101** [comment]
The issue still exist, Please assign me this issue

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete this task within 2 days. Good Luck!
