### ISSUE TITLE
Adding a new tool Eraser.io

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#509]
**Describe the solution you'd like**
I want to add a new coding tool Eraser.io, which is a docs and diagrams platform.

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/126975547/343925d9-b428-44dc-a0da-a2d58c25587d)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @ayush-848 ,  I am assigning this task to you. Kindly complete within 3 days. Good Luck!
