### ISSUE TITLE
Add 'Remove Bookmark' Button Directly on Main Page for Easier Bookmark Management

### ISSUE THREAD

**Issue by kushalkumar1362** [HimanshuNarware/Devlabs#520]
### **Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to go to the bookmark page to remove a bookmark. This makes the process of managing bookmarks time-consuming. For example, if I mistakenly bookmark a product, I have to navigate to the bookmark page, find the product, and then remove the bookmark. This is not user-friendly and can be improved.

### **Describe the solution you'd like**
I would like to have the ability to **remove bookmarks directly from the main page** where all the products are listed. This would make the process of managing bookmarks much easier and more intuitive. Specifically, I suggest adding a 'Remove Bookmark' button next to the existing 'Bookmark' button. When a product is bookmarked, the 'Bookmark' button should be replaced with a 'Remove Bookmark' button, allowing users to quickly and easily remove the bookmark if needed.

### ** Add screenshot 
![Screenshot (361)](https://github.com/HimanshuNarware/Devlabs/assets/140513098/9b9b1b8c-cacc-4a7f-b7af-d7fa30040b4c)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
hi @kushalkumar1362 , I am assigning this task to you. Kindly complete within 2 days. Good luck!
