### ISSUE TITLE
responsive device

### ISSUE THREAD

**Issue by Varsani2520** [HimanshuNarware/Devlabs#523]
**Describe the bug**
in mobile device display only search icon instead of search text filed 

**Expected behavior**
in full device display as it is but in mobile device display only search icon 

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/137641079/4fd42c49-d8db-42b7-82a4-99c186dd85de)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24
