### ISSUE TITLE
[BUG] : Hero section in responsive

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#525]
**Describe the bug**
@HimanshuNarware 

hero section in responsive is not looking good

**Expected behavior**

there are very high margin - y

**Screenshots**

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/4b3ccbd3-475d-43e2-9a0b-f96119825d87)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24
