### ISSUE TITLE
Icon not changing menu to close on sidebar

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#53]
![closeicon iss](https://github.com/HimanshuNarware/Devlabs/assets/83147410/c8bf2982-5f56-44ea-b670-04c2d92a75e0)
![icons iss](https://github.com/HimanshuNarware/Devlabs/assets/83147410/31e601fb-f4cc-4e99-a740-3fabf5d481a5)

**Comment by sarthaksharma27** [comment]
hey @HimanshuNarware Can i work on it ?

**Comment by Anayverma** [comment]
Hi @HimanshuNarware ,I want to work on this issue. Please assign it to me.

**Comment by gitshanmukh123** [comment]
can you assign  this issue to me as I already faced this issue in my personal project too and had solved it ,so you can trust me ,And I will try to do it as soon as possible
