### ISSUE TITLE
Email validation to improve security

### ISSUE THREAD

**Issue by saketh-05** [HimanshuNarware/Devlabs#530]
**Describe the bug**
In the review form, input email section is accepting any text without any pattern or format. This may lead to security issues for backend.

**Expected behavior**
There should a email pattern to validate it while submitting which improves security of the website and also this will prevent any SQL injections or other related issues.

**Screenshots**
![Screenshot 2024-05-27 202710](https://github.com/HimanshuNarware/Devlabs/assets/134281589/208a0922-b295-4467-9ba4-633648b14d4d)

Please assign me this issue under GSSOC 2024

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @saketh-05 , I am assigning this task to you. Kindly complete this within 3 days. Good Luck!

**Comment by saketh-05** [comment]
@panwar8279 I have had end semester exams that's why I was busy till yestarday. Sorry for the late response. I shall complete this issue by today.
