### ISSUE TITLE
bottom to top button

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [HimanshuNarware/Devlabs#538]
**Is your feature request related to a problem? Please describe.**
bottom to top button

**Describe the solution you'd like**

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @RamakrushnaBiswal, I am assigning this task to you. Kindly complete this within 2 days. Good luck!

**Comment by RamakrushnaBiswal** [comment]
issue completed pr #542
