### ISSUE TITLE
The Navbar should be fixed at top in all pages

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#540]
**Is your feature request related to a problem? Please describe.**
The Navbar should be fixed at top while scrolling on the page but it is scrolling with the page.

**Describe the solution you'd like**
I would make it fix at top for all the pages and adjust padings to keep the design same.

** Add screenshot 
![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/b2c89e58-5850-41be-aa1f-1a3627de6070)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Utsavladia , I am assigning this task to you. Kindly complete within 2 days. Good luck!
