### ISSUE TITLE
Unable to use chatbot on Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#541]
**Describe the bug**
The chatbox is not opened properly in Mobile scrren and user will be unable to use it.
The size and design need to be fixed.

**Expected behavior**
The chatbox should be in proper size according to the screen size to give the better user experience.
**Screenshots**

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/5b4a46e8-8b6c-4181-a982-f5c19764cd3b)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Utsavladia ,I am assigning this task to you. Kindly complete within 4 days. Good luck!
