### ISSUE TITLE
BUG: Background and text has poor contrast ratio in error 404 page

### ISSUE THREAD

**Issue by Programmer-Arvind** [HimanshuNarware/Devlabs#546]
**Describe the bug**
Currently, the website has a error page which has a poor contrast ratio making the text unreadable. Both the light theme and dark theme have poor contrast ratio as shown in the screenshots below.

**Expected behavior**
The contrast ratio must be such that any person must be able to read the contents without any difficulty. This will increase the accessibility of the webpage.

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/96773379/31ba14d2-349b-4be6-ac51-169e1c0253dc)
![image](https://github.com/HimanshuNarware/Devlabs/assets/96773379/c97d3fd9-08bb-4b3a-a198-12f0ae79f073)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Programmer-Arvind , I am assigning this task to you. Kindly complete within 3 days. Good Luck!
