### ISSUE TITLE
Adding a opening animation for chat bot 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#551]
**Is your feature request related to a problem? Please describe.**
Adding a opening animation will looks good as the whole website contains lot of animation and after including animation in chat bot popup will definitely increase the UI of the website .

** Add screenshot 

https://github.com/HimanshuNarware/Devlabs/assets/118350936/b26379b6-34ae-45b5-ad9f-8349234eb3d7

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 , I am assigning this task to you. Kindly complete within 3 days. Good luck!

**Comment by Ayushmaanagarwal1211** [comment]
Sure
