### ISSUE TITLE
Improve the sidebar and navbar

### ISSUE THREAD

**Issue by Rishita1304** [HimanshuNarware/Devlabs#553]
The navbar and sidebar can be improved

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @Rishita1304 , I am assigning this task to you & please use the updated code. Kindly complete this task within 3 days. Good Luck!
