### ISSUE TITLE
Chatbot is hiding behind the image at header

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#555]
**Describe the bug**
At header when i open the chatbox then it is hiding behind the image at the header maybe due to the z-index .

**Expected behavior**
The chatbot comes over image 

**Screenshots**
![Screenshot 2024-05-30 085501](https://github.com/HimanshuNarware/Devlabs/assets/118350936/3dc337c0-5f65-457d-866d-89ea5d77930b)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by hunxjunedo** [comment]
kindly assign this to me, would like to contribute.

**Comment by panwar8279** [comment]
Resolved!
