### ISSUE TITLE
Removing an white empty space below navbar 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#562]
**Is your feature request related to a problem? Please describe.**
I don't know whether the white space is place intentionally or not but IMO their is no need to place the white space below the navbar 

**Describe the solution you'd like**
I want to remove that empty space .

** Add screenshot 
![Screenshot 2024-05-30 164306](https://github.com/HimanshuNarware/Devlabs/assets/118350936/f0eca336-7a9f-4eb3-bee2-95437bec64f3)

Checklist
- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Already Resolved this issue.
