### ISSUE TITLE
Booked card content not visible

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#563]
**Describe the bug**
As the content within the booked card is not showing 

**Expected behavior**
It should be visible in both dark and light mode

**Screenshots**
![Screenshot 2024-05-30 182059](https://github.com/HimanshuNarware/Devlabs/assets/142779809/c04767ee-7948-4bb7-949a-ac1565f039f6)
![Screenshot 2024-05-30 182206](https://github.com/HimanshuNarware/Devlabs/assets/142779809/1ef5a1ed-01a5-4b81-a897-6de2803485f5)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete this task within 4 days. Good Luck!
