### ISSUE TITLE
Modify background color

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#564]
As the background color for dark and light mode is too bright and too dark. So, it would be great if we  modify the bg-color and make it user friendly.

![Screenshot 2024-05-30 182628](https://github.com/HimanshuNarware/Devlabs/assets/142779809/61a2944c-0747-47ff-b47b-84a48850b527)

![Screenshot 2024-05-30 182641](https://github.com/HimanshuNarware/Devlabs/assets/142779809/01bbaf91-104a-40a8-9ae0-0c642cf03dcc)

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete this task within 3 days. Good Luck!
