### ISSUE TITLE
Chatbot position

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#565]
**Describe the bug**
As when we open the chatbot it hides behind the hero image

**Expected behavior**
It should be on top of the hero image

**Screenshots**
![Screenshot 2024-05-30 183122](https://github.com/HimanshuNarware/Devlabs/assets/142779809/545bf8b4-ad37-4e4a-91fe-9d175d052dbf)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Please use the updated code for this. Good Luck!
