### ISSUE TITLE
About us buttons content not visible on hover

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#566]
**Describe the bug**
On Hover the content of the button of the About section is not visible 

**Expected behavior**
The text color changes on hover so the content of the buttons would be visible for both dark and light mode

**Screenshots**

https://github.com/HimanshuNarware/Devlabs/assets/142779809/579e3506-5e93-46c8-9713-8fac86159dfa

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Someone Already Working on it!
