### ISSUE TITLE
Adding a contact button in the nav bar

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#570]
**Is your feature request related to a problem? Please describe.**
I want to add a contact button in the navbar.

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @ayush-848 , I am assigning this task to you. Kindly complete this task within 3 days. Good Luck!

**Comment by Shubhamsingh2110** [comment]
i have to work on this #570. please assign me

**Comment by ayush-848** [comment]
> i have to work on this #570. please assign me
This issue's PR is already merged
