### ISSUE TITLE
Unsplash

### ISSUE THREAD

**Issue by jahnaviyallamelli** [HimanshuNarware/Devlabs#572]
**Is your feature request related to a problem? Please describe.**
for free images
**Describe the solution you'd like**
adding unsplash into the website

** Add screenshot 

Checklist
Example  Fill x { [x] }  into  bracket

- [X] I have checked the existing issues *
- [X] I have read the Contributing Guidelines *
- [X] I have starred the repository *
- [X] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @jahnaviyallamelli , I am assigning this task to you. Kindly complete this task within 3 days. Good Luck!
