### ISSUE TITLE
There is no closing option for chatbot

### ISSUE THREAD

**Issue by mukilan2815** [HimanshuNarware/Devlabs#577]
**Describe the bug**
There is no closing button or icon to close that chatbot 

**Expected behavior**
When user press close button , it should close the chatbot .
**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/71129858/795c8fa0-d186-400a-921c-0d07b502a43c)

- [ x] I have checked the existing issues *
- [ x] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @mukilan2815  , i am assigning this task to you. Kundly complete this within 3 days. Good luck!

**Comment by VaibhavYT** [comment]
can you please assign me this , I also want to work on this.😊

**Comment by mukilan2815** [comment]
I have completed this issue.
