### ISSUE TITLE
Empty values are accepting

### ISSUE THREAD

**Issue by mukilan2815** [HimanshuNarware/Devlabs#578]
**Describe the bug**
The chatbot accepts the empty values also , which cause downgrade for user experience 

**Expected behavior**
It should not accept empty values

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/71129858/9ea43f2d-f0ea-48be-87f3-0ee63e72ebc4)

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [x ] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @mukilan2815  , i am assigning this task to you. Kundly complete this within 2 days. Good luck!
