### ISSUE TITLE
Fixed position of screen when new page renders

### ISSUE THREAD

**Issue by paulkrishanu4** [HimanshuNarware/Devlabs#579]
The website should show the content from the top once new page renders but in the current version new page opens from the position of the previous page position 

Bug:

https://github.com/HimanshuNarware/Devlabs/assets/169196836/71f7fbbd-45cb-4f55-8784-1eee4fa81a2c

what it should be like:

https://github.com/HimanshuNarware/Devlabs/assets/169196836/a5954def-5c8d-4efd-98e7-44bf40861843

Assign me to fix it.

Example  Fill x { [x] }  into  bracket

- [x ] I have checked the existing issues *
- [x ] I have read the Contributing Guidelines *
- [ x] I have starred the repository *
- [x ] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @paulkrishanu4  , i am assigning this task to you. Kundly complete this with in 2 days. Good luck!

**Comment by paulkrishanu4** [comment]
Thankyou! @panwar8279 , within tomorrow I will submit the pr
