### ISSUE TITLE
Issue: Website does't have a 404 page

### ISSUE THREAD

**Issue by sarthaksharma27** [HimanshuNarware/Devlabs#58]
**Issue:**
The project currently lacks a user-friendly 404 error page, and the link to return to the home page. I propose the addition of a custom 404 page with improved styling and a button link to enhance user experience.

**Details:**
1. **Custom 404 Page:** A custom 404 error page will be created to provide a more visually appealing and informative experience for users when they encounter a non-existent page.

**Proposed Changes:**
- Create a custom 404 page component.
- Add an image to the 404 page to make it more visually appealing.
- Style the 404 page for a professional look.
- A back to home page button.

**Expected Benefits:**
- Improved user experience for users encountering 404 errors.
- Better aesthetics and professionalism.

**Additional Information:**
This issue aims to improve the overall user experience of the project by addressing the 404 error page's appearance and functionality. These changes will make the project more user-friendly and visually appealing.

**Issue Type:** Enhancement

**Comment by HimanshuNarware** [comment]
@sarthaksharma27 Assigned you
