### ISSUE TITLE
Adding a FAQ's Section

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#585]
**Is your feature request related to a problem? Please describe.**
I will add a FAQ's section .

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24*

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211  , i am assigning this task to you. Kundly complete this within a week. Good luck!

**Comment by Ayushmaanagarwal1211** [comment]
Sure
