### ISSUE TITLE
Your Cool Website need Contributors page!!

### ISSUE THREAD

**Issue by pandeyji711** [HimanshuNarware/Devlabs#588]
@HimanshuNarware 
A "Contributors" page on Your Cool Website acknowledges and appreciates the individuals who have contributed, fostering community and credibility. It serves as a networking tool, inspiring collaboration and providing visibility for contributors' work. By showcasing names, bios, contributions, and contact information, it creates connections and motivates further engagement. Ultimately, the page enhances Your Cool Website's reputation and encourages ongoing participation.

** Like this

![Screenshot 2024-06-01 004143](https://github.com/HimanshuNarware/Devlabs/assets/154527778/1f9924ab-18c0-4730-bd6d-6a35e405128a)

- [X ] I have checked the existing issues *
- [ XI have read the Contributing Guidelines *
- [X ] I have starred the repository *
- [X ] Working under Gssoc'24

**Comment by pandeyji711** [comment]
@HimanshuNarware Please assign this to me

**Comment by pandeyji711** [comment]
@HimanshuNarware please Review

**Comment by panwar8279** [comment]
Hi @pandeyji711 , I am assigning this task to you. Kindly complete this task within 5 days. Good Luck!

**Comment by pandeyji711** [comment]
@panwar8279 ok thanks
