### ISSUE TITLE
Description Text need to be Fixed in Bookmark section

### ISSUE THREAD

**Issue by sri766** [HimanshuNarware/Devlabs#596]
### Problem Description
------------------------------------------------
**Text is not visible in the Bookmark Section** 

Images of UI issues: 

<img src="https://github.com/HimanshuNarware/Devlabs/assets/84568590/ee989668-211c-4a41-bcb9-925fceeb35e2" width="600" />
<img src="https://github.com/HimanshuNarware/Devlabs/assets/84568590/5354f1a3-b35c-4ebd-9c7b-fa396e85e402" width="600" />

I want to fix it. can you assign it to me.

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc'24

**Comment by panwar8279** [comment]
Hi @sri766 , I am assigning this task to you. Kindly complete this task within 3 days. Good Luck!

**Comment by sri766** [comment]
Sure

**Comment by sri766** [comment]
### @panwar8279 Please assign this to me .....without this I can proceed with #597
