### ISSUE TITLE
pagination causing error

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#61]
![imgae](https://github.com/HimanshuNarware/Devlabs/assets/83147410/f9d8f8e9-a03b-4f79-a26c-3bd11bc378ee)

**Comment by suvraghosh** [comment]
I would like to work on this project.Can u please assign this project to me

**Comment by gitshanmukh123** [comment]
>I would like to  solve this issue as soon and as better as possible if you assign this issue to me
