### ISSUE TITLE
Mobile view navbar is static

### ISSUE THREAD

**Issue by paulkrishanu4** [HimanshuNarware/Devlabs#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Want to change the display condition of mobile view navbar , in the current version it is always displayed along with main navbar. It should come into action only in mobile view or tab view. Assign me to fix it.

before:

https://github.com/HimanshuNarware/Devlabs/assets/169196836/602bdb2d-65fe-4baf-b3f2-8759a43c7adb

### Expected behavior

After:

https://github.com/HimanshuNarware/Devlabs/assets/169196836/a5194943-0db4-4282-9607-748e07dfae84

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HimanshuNarware** [comment]
@paulkrishanu4 not needed
