### ISSUE TITLE
[Feature Request]: Add "Buy Me a Coffee" or "Sponsor Me" Button to Footer

### ISSUE THREAD

**Issue by MrPC7** [HimanshuNarware/Devlabs#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I aim to enhance our website/application by adding a "Buy Me a Coffee" or "Sponsor Me" button in the footer. This feature will allow users to support the project financially, helping us sustain and improve our work through community contributions.

**Objectives:**
**Design and Placement**: Integrate a visually appealing button into the footer, ensuring it matches the overall design aesthetic and is positioned in a prominent yet unobtrusive location.
**Functionality**: The button should link to a chosen sponsorship platform such as Buy Me a Coffee, Patreon, or GitHub Sponsors.
**Responsiveness**: Ensure the button is responsive and displays well on all devices, including desktop, tablet, and mobile.

### Use Case

**Use Case:** Supporting the Project via Footer Button

**Actor:** User
**Goal:** Support the project financially

**Steps:**

- User navigates to the website/application.
- User sees the "Buy Me a Coffee" or "Sponsor Me" button in the footer.
- User clicks on the button.
- User is redirected to the chosen sponsorship platform.
- User completes the financial support process.

**Extensions:**

- If on mobile, ensure button is easy to tap.
- If the platform link is broken, display an error message.
- Frequency: Users who appreciate the project are expected to use it frequently.

### Benefits

Provides users with a convenient way to financially support the project, contributing to its sustainability and growth.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/91939963/9c0229f1-8377-403c-a10e-25bc33034939)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @MrPC7, Kindly complete this within 4 days. Good luck!
