### ISSUE TITLE
[Feature Request]: Create Ethical Hackign Page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

we can create `/ethical-hacking` rotue when user click on footer link `Ethical Hacking` they will redicted to here

### Use Case

it help user to understand ethcial hacking concept and how to prevent our data by hackers.

### Benefits

we can create blogs page for ethical hacking where user can read blogs related to `ethical hacking`

### Add ScreenShots

somethign like this,

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/fb7774eb-6cc3-4ea4-831e-3610ad17f8a5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I am assigning this task to you. Kindly complete this within 4 days. Good luck!

**Comment by dhruv8433** [comment]
Hey @panwar8279 

please merge previous pull request
so i  can make new pr for this issue
