### ISSUE TITLE
[Feature Request]: Create Coding Plateform Page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

we can create `/coding-plateform` when user click on footer link `Coding Plateform` will be redirected  to here

### Use Case

A coding platform integrated into a job website allows users to demonstrate their skills through coding challenges and assessments, which can be directly viewed by potential employers.

### Benefits

it helpp user to test their coding skills where all user can use coding editior 
we provide multiple codign editors link
based on user preference they can use it

### Add ScreenShots

when user click on particualr code editore link it open somethig like this

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/30fb8421-9746-41f2-b928-174685f4dd4e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I am assigning this task to you. Kindly complete this within 5 days. Good luck!

**Comment by dhruv8433** [comment]
@panwar8279 
thank you so much
