### ISSUE TITLE
[Feature Request]: Create Cource Plateform Page

### ISSUE THREAD

**Issue by dhruv8433** [HimanshuNarware/Devlabs#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@panwar8279 

we can create `/cource-plateform` page when user click on footer link `Cource Plateform` will be redirected to here

### Use Case

A courses page on a job website enhances candidates' employability by offering targeted learning resources and certifications relevant to their desired roles. It provides users with opportunities to upskill and stay competitive in the job market through continuous education. Additionally, employers can verify applicants' proficiency in key areas, leading to better hiring decisions and improved job matches.

### Benefits

it help user to find particular cource and improve their skills by registering on that.
A courses page on a job website offers significant benefits by enhancing users' skill sets and employability through access to targeted learning resources and certifications. 

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/114583978/b23250cf-9383-476f-8e8f-1c2fba800b0c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dhruv8433** [comment]
I would like to work with you 
Please assign me

**Comment by panwar8279** [comment]
Hi @dhruv8433 ,  I am assigning this task to you. Kindly complete this within 4 days. Good luck!
