### ISSUE TITLE
[Feature Request]:  Adding a new link in footer 'Contribute here'

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This will be located in the footer

### Use Case

on clicking it, user will get direct to this repo.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ayush-848 , i am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by ayush-848** [comment]
@panwar8279 The recent merges have made the code quality drop
![image](https://github.com/HimanshuNarware/Devlabs/assets/126975547/dfe86f79-d877-455b-a4f7-bca0cf545724)
![image](https://github.com/HimanshuNarware/Devlabs/assets/126975547/b34bfc43-7860-4337-8079-f228530355a1)

Courses is written as Cources
CodingPlatform is written as CodeingPlateform
people are not closing the div
