### ISSUE TITLE
[Bug]: Chatbot problem

### ISSUE THREAD

**Issue by ayush-848** [HimanshuNarware/Devlabs#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/HimanshuNarware/Devlabs/assets/126975547/25e47d69-1b88-48ec-b6f6-1f3cb57c80dd)

### Expected behavior

Those 2 chatbot images should not be there

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ayush-848 , i am assigning this task to you. Kindly complete within 3 days. Good luck!
