### ISSUE TITLE
🐞BUG: "Chatbot" and "Scroll-to-Top button" is Overlapping 

### ISSUE THREAD

**Issue by MastanSayyad** [HimanshuNarware/Devlabs#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @HimanshuNarware and @panwar8279 
The chatbot button and scroll to top buttons are overlapping 

### Expected behavior

The "Scroll to Top" button and the WebChat bot should not overlap. Both elements should be easily accessible without interfering with each other.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/101971980/2b9dcdd4-2c78-4d9f-a7c6-ce415e7fe404)

### After clicking chatbot:

![image](https://github.com/HimanshuNarware/Devlabs/assets/101971980/1fd08da4-d099-4949-883a-63d317508729)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @MastanSayyad ,i am assigning this task to you. Kindly complete within 3 days. Good luck!
