### ISSUE TITLE
Display Issue: Link and Bookmark Button Overlap

### ISSUE THREAD

**Issue by Venkateeshh** [HimanshuNarware/Devlabs#64]
**Describe the bug**
This bug report highlights an issue where the link and bookmark buttons on the page are slightly overlapping, causing a visual display problem. We need to address this to ensure a seamless user experience.Description: The issue involves a display anomaly where the link and bookmark button exhibit a slight overlap, potentially impacting the user interface. Screenshots and additional details will be provided to facilitate a comprehensive understanding and resolution of the problem.

**Expected behavior**
 The link and bookmark buttons should be properly spaced and not overlap, ensuring a clean and user-friendly interface.

**Screenshots**
![Screenshot 2023-10-07 222733](https://github.com/HimanshuNarware/Devlabs/assets/117290841/3dacc792-8db0-4760-88fe-bd4e6d92715a)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *

**Comment by HimanshuNarware** [comment]
@Venkateeshh  assigned you
