### ISSUE TITLE
Want to Change the backgroud of  the webapp

### ISSUE THREAD

**Issue by chetansonare03** [HimanshuNarware/Devlabs#65]
Want to Change the backgroud of  the webapp

**Comment by harshjais369** [comment]
Hey @chetansonare03 , I would like to contribute onto this issue. Could you please assign it to me? Additionally, do share me the further details for this task specific to your need.

**Comment by HimanshuNarware** [comment]
@harshjais369  assigned you ,

**Comment by sakshipatil4403** [comment]
@HimanshuNarware pls assign me this issue

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me @HimanshuNarware
