### ISSUE TITLE
[Feature Request]: Change title bar name from Streamlit

### ISSUE THREAD

**Issue by Programmer-Arvind** [HimanshuNarware/Devlabs#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On the title bar of the browser college.ai displayed.

### Use Case

This would enhance the user experience in browser.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/96773379/655fbbff-9579-4961-95b8-4d919cb2c53c)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Programmer-Arvind , I am assigning this task to you. Kindly complete this within 3 days. Good luck!
