### ISSUE TITLE
[Bug]: No proper alignment of FAQ's and Contact in the navbar

### ISSUE THREAD

**Issue by the-code-artist** [HimanshuNarware/Devlabs#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

FAQ's and contact elements are aligned in the same column in the navbar though they are redirecting to 2 different pages and common underline effect upon hover on FAQ's and contact elements

### Expected behavior

Properly align the navbar elements such that all the elements are in a single row which will help in easy navigation

### Add ScreenShots

Issue lies in 
![image](https://github.com/HimanshuNarware/Devlabs/assets/115625321/075213b7-ff74-429b-89b1-1cb0f0e0f26a)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by the-code-artist** [comment]
Hey @panwar8279
Please assign me this issue under GSSOC'24...i am excited in contributing to DEVLAPS!

**Comment by panwar8279** [comment]
Hi @the-code-artist , i am assigning this task to you. Kindly complete within 2 days. Good luck!
