### ISSUE TITLE
[Bug]: wrong position for search bar and spacing 

### ISSUE THREAD

**Issue by dnyandeepchute** [HimanshuNarware/Devlabs#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

wrong position for search bar
as it is better to place at center and need better spacing inside nav bar

### Expected behavior

search bar should be in center.

### Add ScreenShots

![Screenshot 2024-06-05 153507](https://github.com/HimanshuNarware/Devlabs/assets/158272735/9479a95b-9965-4b8b-b5b7-2fbb2aabb859)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dnyandeepchute** [comment]
hey @HimanshuNarware , please assign this to me, thank you.

**Comment by bhaskar-2024** [comment]
assign this to me please
