### ISSUE TITLE
Contributor section already exist in about us page so need to remove contributor section from home page.

### ISSUE THREAD

**Issue by panwar8279** [HimanshuNarware/Devlabs#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If anyone want to work on this. Please so you interest.

### Expected behavior

Contributor section already exist in about us page so need to remove 

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by bhaskar-2024** [comment]
assign this to me please

**Comment by panwar8279** [comment]
Hi @bhaskar-2024 ,  i have assigned this task to you. Kindly complete within 2 days. Good luck!
