### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by kashi-verma** [HimanshuNarware/Devlabs#688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As we can see in the navbar the FAQ's and Contact Us section is overlapping each other, that not looking so fine .
so my feature is to solve this issue and align the navbar components perfectly.so I request to @HimanshuNarware to assign me this issue. As a developer I will fix it in just some day.
Thank you

### Use Case

this will make the project more user friendly.

### Benefits

The navbar will look much better.

### Add ScreenShots

<img width="959" alt="Screenshot 2024-06-07 132151" src="https://github.com/HimanshuNarware/Devlabs/assets/153519624/94fb7e4d-f9e3-4789-9a5d-79c18748842b">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Someone already working on this problem
