### ISSUE TITLE
[Bug]: Minor syntax error in sidebar.js

### ISSUE THREAD

**Issue by arpy8** [HimanshuNarware/Devlabs#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There's a minor syntax error in the `sidebar.js` script in line 115.

### Expected behavior

-

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/74809468/ffced4e8-d6a2-49ef-81ba-2536222ba4ea)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by bhaskar-2024** [comment]
assign this to me

**Comment by arpy8** [comment]
![image](https://i.pinimg.com/originals/44/0f/ba/440fbafa6d3a0b4a673636037b937192.gif)
