### ISSUE TITLE
[style] Modify contributors section

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#707]
As of now the contributor section is not organized and has dose not have a proper styling. so, modify them will increase the user experience

![Screenshot 2024-06-09 043707](https://github.com/HimanshuNarware/Devlabs/assets/142779809/d5b44fef-5775-4e7b-8f0f-2509fc28e109)

**Comment by HimanshuNarware** [comment]
@root-0101 Do one thing remove the contributor's section from the home, we already have the contributors section on the About Us page, if you want to update anything you can do

**Comment by root-0101** [comment]
Hey @HimanshuNarware I have some success merged PR with levels please provide me the required levels

**Comment by root-0101** [comment]
Ok I got it and please consider my issue
