### ISSUE TITLE
Enhancing User Experience with Hover Effects on Cards

### ISSUE THREAD

**Issue by sarthaksharma27** [HimanshuNarware/Devlabs#71]
Is your feature request related to a problem? Please describe.
The problem is that without hover effects, cards on a web page may appear static and less engaging to users. This can lead to a less immersive and interactive user experience.

Describe the solution you'd like
The solution is to add hover effects to cards. When a user hovers their mouse pointer over a card, various visual changes can occur, such as:

1- Highlighting: The card can change color, making it clear that it's interactive.
2- Scaling: The card can slightly enlarge to provide a subtle 3D effect.
3-Shadow: Adding a shadow beneath the card can create the illusion of depth.
4- Information Display: Additional information or actions can be displayed when hovering, like showing a button for more details.

  These hover effects not only make the cards more visually appealing but also convey interactivity, encouraging users to engage 
  with the content.

** Add screenshot
![Screenshot (40)](https://github.com/HimanshuNarware/Devlabs/assets/130299888/3c522d60-3d5e-4fb1-8632-d29f44b8aff0)

Checklist
Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *

**Comment by sarthaksharma27** [comment]
> @sarthaksharma27 don't raise PR before getting assigned

I understand and i make sure that form next time

**Comment by gitshanmukh123** [comment]
can you assign me this  issue to me ,I promise you that yoy wont get disappointed by my work,
i would like to give them a neat and respomsive css and hovering effects that suits your actual styling
