### ISSUE TITLE
Add transition property on the sidebar

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#73]
The transition  of sidebar is so random, add transition property

**Comment by harshjais369** [comment]
@HimanshuNarware I would like to contribute on this issue. Can you assign it to me?

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware I would like to contribute on this issue. Can you assign it to me?

Under hacktomberfest or slop 3.0 program ?

**Comment by harshjais369** [comment]
> > @HimanshuNarware I would like to contribute on this issue. Can you assign it to me?
> 
> Under hacktomberfest or slop 3.0 program ?

Hacktoberfest

**Comment by HimanshuNarware** [comment]
> can i work on this issue ??
@Rawshansharma this issue is already assigned to @harshjais369 , but you can work on the UI of the back-to-top button

**Comment by Nupoor10** [comment]
Hey, Can I work on this under KWOC'23 ??

**Comment by vaishnavi192** [comment]
HEY @HimanshuNarware  I would like to work on this issue under DWOC'24. plz assign me

**Comment by Nirvanjha2004** [comment]
Heyy @HimanshuNarware  Can u assign me this issue >?
