### ISSUE TITLE
[Feature Request]: Trailing Cursor 

### ISSUE THREAD

**Issue by Chandu6702** [HimanshuNarware/Devlabs#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the customized mouse movement  for cursor like in  the sample video.Observe the cursor
https://github.com/HimanshuNarware/Devlabs/assets/125206920/73a4ed95-7661-44a9-83a1-853f559f2244

### Use Case

A trailing effect adds for the cursor while moving through out the page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Chandu6702** [comment]
@panwar8279 please assign this to me

**Comment by panwar8279** [comment]
Hi @Chandu6702 , I am assigning this task to you. Kindly complete within 3 days. Good luck!
