### ISSUE TITLE
[Feature Request]: Filling remote jobs section

### ISSUE THREAD

**Issue by The-Phoenics** [HimanshuNarware/Devlabs#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently there the Remote jobs section on the website has not resources.

![remote-jobs](https://github.com/HimanshuNarware/Devlabs/assets/96228962/8e38b250-e5ab-4f23-a052-dbab2a490084)

I would like to add some useful resources components for the remote jobs section.

### Use Case

It would add more content to the web application and provide more resources to the users who are looking for remote jobs tools and resources.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by The-Phoenics** [comment]
Hey @HimanshuNarware 
Can you please take a look at this issue? I would like to work on this for GSSoC'24.

**Comment by panwar8279** [comment]
Hi @The-Phoenics , I am assigning this task to you. Kindly complete within 3 days. Good luck!
