### ISSUE TITLE
Modify and clean up the FAQ section

### ISSUE THREAD

**Issue by enzorod10** [HimanshuNarware/Devlabs#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- The contrast on the heading of the FAQ's are hard to read, both on light and dark mode.
- The space between the icons, the heading, and the arrow is quite unappealing.
- Minor grammatical issues that can be fixed.

### Expected behavior

The FAQ section should appear cleaner and should stay loyal to the general theme of the website.

### Add ScreenShots

![FAQ Section](https://github.com/HimanshuNarware/Devlabs/assets/93365813/bb20f55b-f68d-4e5b-b5db-fc6700f6232c)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by root-0101** [comment]
Hey @HimanshuNarware @panwar8279 please assign me this issue

**Comment by panwar8279** [comment]
Hi @enzorod10 ,  i have assigned this task to you. Kindly complete within 2 days. Good luck!

**Comment by enzorod10** [comment]
Fixed on new PR request. Can be further improved if you'd like @root-0101
