### ISSUE TITLE
[New Tool]:Udemy 

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Udemy democratizes education by providing a vast array of online courses, catering to diverse interests and skill levels. Its self-paced learning model enables individuals worldwide to acquire new skills and advance their careers conveniently and affordably.

### Use Case

Udemy democratizes education by providing a vast array of online courses, catering to diverse interests and skill levels. Its self-paced learning model enables individuals worldwide to acquire new skills and advance their careers conveniently and affordably.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 3 days. Good luck!
