### ISSUE TITLE
[New Tool]: Coding Ninjas

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Coding Ninjas offers comprehensive coding courses designed to equip learners with the skills needed for success in the tech industry. With expert-led instruction and hands-on projects, it provides a supportive environment for mastering programming languages and building real-world applications.

### Use Case

Coding Ninjas offers comprehensive coding courses designed to equip learners with the skills needed for success in the tech industry. With expert-led instruction and hands-on projects, it provides a supportive environment for mastering programming languages and building real-world applications.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 4 days. Good luck!
