### ISSUE TITLE
[New Tool]: edx

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

EDX stands as a beacon of accessible education, bridging the gap between learners and prestigious institutions worldwide. Its versatile platform cultivates a culture of continuous learning

### Use Case

EDX stands as a beacon of accessible education, bridging the gap between learners and prestigious institutions worldwide. Its versatile platform cultivates a culture of continuous learning, empowering individuals to thrive in an ever-evolving world.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 2 days. Good luck!
