### ISSUE TITLE
[New Tool]: copilot ai

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 Microsoft's Copilot AI fosters collaboration, streamlining coding processes with innovative suggestions and insights.

### Use Case

Microsoft's Copilot AI fosters collaboration, streamlining coding processes with innovative suggestions and insights.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 2 days. Good luck!
