### ISSUE TITLE
[Bug]: spacing in footer

### ISSUE THREAD

**Issue by aashkaaaaaa** [HimanshuNarware/Devlabs#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

looks uneven

### Expected behavior

need the proper spacing

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/138461600/f2905041-f547-450f-b5e5-7ebae7622f7a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @aashkaaaaaa ,  i am assigning this task to you. Kindly complete within 2 days. Good luck!
