### ISSUE TITLE
[Bug]: Fix all the coding errors in App.js

### ISSUE THREAD

**Issue by woodwolfswee** [HimanshuNarware/Devlabs#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is huge number of unnecessary imports and errors in the App.js file.

### Expected behavior

There should be no errors in the App.js as it would help improve the performance of the overall website.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @woodwolfswee ,  i am assigning this task to you. Kindly complete within 4 days. Good luck!
