### ISSUE TITLE
[Feature Request]: Containerize the backend and frontend

### ISSUE THREAD

**Issue by AMS003010** [HimanshuNarware/Devlabs#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wanted to propose the containerization of the backend and frontend by adding Dockerfile, dockerignore and docker-compose.yaml files

### Use Case

By containerizing the backend and frontend, the benefits are
 - Can be deployed as a microservice in the future
 - It solves the obvious problem of "it works on my machine"
 - This makes it more scalable
 - Faster deployment and also features like CI/CD can be added easily

I am planning to reduce the image sizes by using multi stage builds

### Benefits

As modern application are adopting a microservice architecture due to better scalability and fault tolerance, containerizing it would help keep the application in par with present standards

### Add ScreenShots

None

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AMS003010** [comment]
Hello @HimanshuNarware 🤗

I would like to be assigned this issue under gssoc'24

**Comment by panwar8279** [comment]
Hi @AMS003010 ,  i am assigning this task to you. Kindly complete within 2 days. Good luck!

**Comment by AMS003010** [comment]
Hello @panwar8279 🤗

There are a lot of errors in the frontend folder. Without rectifying it, I cannot containerize the frontend. How should I proceed

**Comment by AMS003010** [comment]
@panwar8279
I have made the PR.
Please do review it.
