### ISSUE TITLE
Improve the UI of the About section

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#77]
Improve the UI of the About section

**Comment by ayushshukla011** [comment]
please assign this issue to me 
@HimanshuNarware

**Comment by HimanshuNarware** [comment]
@ayushshukla011  you are working under hacktomberfest or slop 3.0

**Comment by HimanshuNarware** [comment]
@ayushshukla011 ok assigned you

**Comment by Nupoor10** [comment]
Hey, Can I work on this under KWOC'23 ??

**Comment by vaishnavi192** [comment]
@HimanshuNarware  does this comes under DWOC'24? I want to work on this issue. plz assign

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me @HimanshuNarware

**Comment by Mohammad-Qamar** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me @HimanshuNarware

**Comment by Nirvanjha2004** [comment]
Hey Can u Assign me this issue.. @HimanshuNarware

**Comment by Shelbybosss** [comment]
@HimanshuNarware,
I will improve the UI can you assign me
