### ISSUE TITLE
[New Tool]: Material UI

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

MUI provides a simple, customizable, and accessible library of React components.

### Use Case

MUI provides a simple, customizable, and accessible library of React components.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 4 days. Good luck!
