### ISSUE TITLE
[New Tool]: React Bootstrap

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

 React Bootstrap is also one of the most popular React UI libraries. Built on top of the popular Bootstrap framework,

### Use Case

 React Bootstrap is also one of the most popular React UI libraries. Built on top of the popular Bootstrap framework,

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 2 days. Good luck!
