### ISSUE TITLE
[New Tool]: Flex Box Froggy

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

In this game, you must bring the frogs home to their lilypads by mastering CSS flexbox. This helps users to master flexbox css

### Use Case

In this game, you must bring the frogs home to their lilypads by mastering CSS flexbox. This helps users to master flexbox css

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 ,  i am assigning this task to you. Kindly complete within 3 days. Good luck!
