### ISSUE TITLE
[New Tool]: Blender 3D

### ISSUE THREAD

**Issue by VaishnaviMankala19** [HimanshuNarware/Devlabs#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, even video editing and game creation.

### Use Case

Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, even video editing and game creation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @VaishnaviMankala19 , i am assigning this task to you. Kindly complete within 2 days. Good luck!
