### ISSUE TITLE
[Bug]: Multiple home page

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is multiple home page 

### Expected behavior

There should be only one main Home page

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/142779809/91354a1e-f769-4e99-9552-abb0349eebe2

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by root-0101** [comment]
Hey @HimanshuNarware @panwar8279 As I have multiple unleveled successfully merged PR from last week, please assign me the required levels 
- #495
- #494 
- #453
- #306 
- #288 
- #246 
- #218

**Comment by panwar8279** [comment]
@root-0101 , Please start working on it and fix it as soon as possible.

**Comment by root-0101** [comment]
> Hey @HimanshuNarware @panwar8279 As I have multiple unleveled successfully merged PR from last week, please assign me the required levels 
> - #495
> - #494 
> - #453
> - #306 
> - #288 
> - #246 
> - #218
> 

Hey @panwar8279 can you please look into this
