### ISSUE TITLE
[Bug]: Remove Duplicate Footer

### ISSUE THREAD

**Issue by jency1** [HimanshuNarware/Devlabs#784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a duplicate footer section on the homepage that needs to be removed. The presence of two footers is redundant and affects the overall design and user experience.

I am a GSSOC Contributor.

Please assign this issue to me. So that I can make the required changes as soon as possible.

@HimanshuNarware @panwar8279 

### Expected behavior

There should be only one footer at the bottom of the homepage.

Removing the duplicate footer will help streamline the page layout and improve user experience.

### Add ScreenShots

![Duplicate footers](https://github.com/HimanshuNarware/Devlabs/assets/149723236/2378049e-61ea-45d8-abba-16cebef9fc39)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by jency1** [comment]
@panwar8279 @HimanshuNarware 

I'm GSSOC'24 Contributor. 

Please assign this issue to me. It need to be resolved as soon as possible for better user experience. 

Thank you!

**Comment by jency1** [comment]
@panwar8279 @HimanshuNarware 

Can I start working on this issue?

**Comment by panwar8279** [comment]
@jency1 , Please start working on it.

**Comment by jency1** [comment]
> @jency1 , Please start working on it.

@panwar8279 Thanks for looking into this matter. I will resolve this issue by tomorrow. 

Thank you!
