### ISSUE TITLE
[Bug]: Remove Duplicate Home Pages 

### ISSUE THREAD

**Issue by jency1** [HimanshuNarware/Devlabs#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are multiple instances of the home page, which leads to confusion and redundancy. We need to identify and remove the duplicate home pages to ensure there is only one authoritative home page.

Having multiple home pages can negatively affect user experience and SEO performance. Consolidating to a single home page will improve site navigation and search engine rankings.

Priority : High

Please assign this issue to me. This issue needs to be resolved as soon as possible.

@panwar8279 @HimanshuNarware  

### Expected behavior

There should be only one home page.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by jency1** [comment]
@panwar8279 @HimanshuNarware 

I'm GSSOC'24 Contributor. 

Please assign this issue to me. It needs to be resolved as soon as possible for better user experience. 

Also User gets bored and confused while scrolling 4-5 home pages to reach the footer section. 

Thank you!

**Comment by jency1** [comment]
@HimanshuNarware  Thanks for assigning this issue to me. 

I will resolve this problem as soon as possible. 

Please add the gssoc and level labels. 

Thank you.

**Comment by root-0101** [comment]
Hey @HimanshuNarware I have raised the same issue in #777
