### ISSUE TITLE
Username may go outside of the container if it's too long

### ISSUE THREAD

**Issue by davidkrupa** [HimanshuNarware/Devlabs#79]
**Describe the bug**
If the username is too long, it may  go beyond borders of the container on some screen sizes (I'm on 13" laptop, viewportsizer shows screen size: 1263 × 571)

**Expected behavior**
Hide some part of username that i overflowing the container

**Screenshots**
<img width="868" alt="3" src="https://github.com/HimanshuNarware/Devlabs/assets/126403373/92d150ea-7da3-469b-8252-a7d1ba21b2cd">

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] Working under Hacktomberfest*

**Comment by hrid-chakraborty** [comment]
I would like to contribute to fixing this issue, can you please assign it to me?

**Comment by HimanshuNarware** [comment]
@davidkrupa Assigned you, Also imprope the UI of the contributor section, remove the number of commits from my name and add founder over there, also remove my profile  from the grid layout and add on the top of the contributor list

**Comment by HimanshuNarware** [comment]
> I would like to contribute to fixing this issue, can you please assign it to me?

@hrid-chakraborty  this issue has been assigned, but you can work on the UI or responsiveness of the About us page
