### ISSUE TITLE
[Bug]: Multiple imports and Unnecessary Code

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/078c48f6-7d96-4729-9bde-b0f29f4bdbbd)
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/8e89bd8d-cf8d-4124-82e5-ed9cd772d69a)
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/f4a0fe2f-c861-42eb-a855-3a9e74f69093)
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/8fdeea12-fbd4-4f7c-91b0-e47712f8491c)
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/071e3f7e-c578-49cd-927c-b22221469d6a)
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/39947827-06fe-4c31-a43a-bb8fd04767d2)

### Expected behavior

There shouldn't repetitive code in the codebase

### Add ScreenShots

@HimanshuNarware @panwar8279 This issue has to be resolved as soon has possible.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279, can u help me with setting up the backend and frontend environment 
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/e135a716-adf5-439b-af62-3c8c7202c764)

**Comment by panwar8279** [comment]
@Kiran-pande-30 , Start working on it.

**Comment by Kiran-pande-30** [comment]
Should I also resolve this warnings ?
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/5e7a42f3-98a8-445c-b227-c8bcc7d3398c)

**Comment by Kiran-pande-30** [comment]
@panwar8279 I will also solve the repetitive content in the footer in the same issue

![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/343a7eca-f39b-4fa4-9332-fe1118bd0b42)
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/9247091a-2754-406b-a8fc-927710c67bad)

**Comment by Kiran-pande-30** [comment]
Most of the Changes in this issue were resolved after I raised the issue, still have to fix the duplicate links in the footer and minor bug fixes.
