### ISSUE TITLE
Scroll To Top Button 

### ISSUE THREAD

**Issue by Vishal-1004** [HimanshuNarware/Devlabs#8]
At the present state the website really looks very well but it can be enhanced even more by adding a "Scroll To Top" button in the bottom right of the website. 
This enhancement of feature will really come in handy for many users.

##
I would like to work on this feature, so can you please assign me this task

**Comment by harshjais369** [comment]
Hello, I want to contribute onto this issue. Could you assign it to me?

**Comment by HimanshuNarware** [comment]
@harshjais369  Under hacktomber fest or a slop 3.0 ?

**Comment by harshjais369** [comment]
> @harshjais369 Under hacktomber fest or a slop 3.0 ?

Hacktoberfest

**Comment by vaishnavi192** [comment]
hey @HimanshuNarware I want to work on this issue under DWOC'24. kindly assign me
