### ISSUE TITLE
[Bug]: header needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [HimanshuNarware/Devlabs#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot_20240614_115954](https://github.com/HimanshuNarware/Devlabs/assets/59639410/5a302e05-9f91-4b68-b170-3ca3f1f4a345)

### Expected behavior

All header needs to be aligned 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by kapilG0** [comment]
Hello @HimanshuNarware please assign this issue to me under gssoc 24

**Comment by panwar8279** [comment]
Hi @kapilG0 , I am assigning this task to you. Kindly complete within 2 days. Good luck for your work.

**Comment by kapilG0** [comment]
Hello @panwar8279 i am closing this as i am start working but it has fixed thanks
![image](https://github.com/HimanshuNarware/Devlabs/assets/59639410/7aac8de0-19c8-46ec-bcfe-34ecd51a2dfe)
