### ISSUE TITLE
[Bug]: Footer Content is Duplicated and Misaligned

### ISSUE THREAD

**Issue by Amulya-Codes** [HimanshuNarware/Devlabs#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are two primary issues observed with the footer in the application:

Footer Content Duplication: The footer content is being rendered twice, leading to a redundant and cluttered appearance.

Alignment Issue: The footer content is not centered properly, resulting in a visually unappealing layout.

![Screenshot (1112)](https://github.com/HimanshuNarware/Devlabs/assets/118996055/15ac270b-b8ef-4e12-a91b-ecd5f33b092c)
![Screenshot (1113)](https://github.com/HimanshuNarware/Devlabs/assets/118996055/618fb71a-f575-44ed-925b-b8715df1fc46)
![Screenshot (1114)](https://github.com/HimanshuNarware/Devlabs/assets/118996055/203de286-165a-40b2-8c09-f238274e91ab)

### Expected behavior

The footer content should be displayed only once.
All elements within the footer should be properly centered to ensure a neat and organized appearance.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Amulya-Codes , I am assigning this task to you. Kindly complete within 2 days. Good luck for your work.

**Comment by jency1** [comment]
> Hi @Amulya-Codes , I am assigning this task to you. Kindly complete within 2 days. Good luck for your work.

@panwar8279 I have already raised this issue #784 2 days ago. As this is based on first come first serve, I should be assigned to this issue because I have raised this issue first. 

Please do check this and re-assign this issue to me as soon as possible.
