### ISSUE TITLE
Improving UI of the card

### ISSUE THREAD

**Issue by Anjali-Kedia** [HimanshuNarware/Devlabs#83]
**Problem**
The current design for cards, does not work well with the background and the site because most of the logos get hidden away due to the transparency, and in others the card size is affecting how the logo is displayed. For eg: in the image below cuvette logo cannot be seen and internshala logo isn't clear either.
<img width="1357" alt="image" src="https://github.com/HimanshuNarware/Devlabs/assets/91176852/57b8cf53-fb2f-4977-8bba-b3ed793ab873">

**Solution**
A better card design would be having a solid background colour with an increased width so that each row contains max of 4 cards, but everything is clear and concise. Kindly refer to the below image for better understanding. This also solves the problem of overflow of text and brings uniformity to the website. We can discuss the colours as per your requirement. 

<img width="406" alt="Screenshot 2023-10-18 at 1 28 55 AM" src="https://github.com/HimanshuNarware/Devlabs/assets/91176852/3c37e3ab-d815-4028-a990-586019c70274">

Checklist

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Hacktoberfest/Hacksquad*
- [ ] Working under Slop 3.0 *
Looking forward to collaborating!

**Comment by HimanshuNarware** [comment]
@Anjali-Kedia  assigned you

**Comment by Anjali-Kedia** [comment]
@HimanshuNarware Added a PR for the same. Do let me know for any changes!
