### ISSUE TITLE
Remove Unnecessary Footer

### ISSUE THREAD

**Issue by sailaja-adapa** [HimanshuNarware/Devlabs#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to remove unnecessary footer from the page as you can see in the below video i pointed it through mouse pointer

Again unnecessarily a footer is present below the Footer

Can you please assign me this issue under gssoc'24 @panwar8279 

### Use Case

It will increase User Experience and Make Website to look Attractive 

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/161804629/70b2fee9-e387-4402-bba9-c657de7b5484

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sailaja-adapa , I am assigning this issue to you. Kindly complete within 2 days good luck!
