### ISSUE TITLE
[Documentation Update]:  add  tech stack logo in  this project

### ISSUE THREAD

**Issue by Debayan-Ghosh2005** [HimanshuNarware/Devlabs#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

no techstack logo added 

### Suggested Change

i will add the tech stack logo for good looking the project

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Debayan-Ghosh2005** [comment]
i am new at gssoc24 . so can you assign this task to me

**Comment by panwar8279** [comment]
Start working on it.

**Comment by Debayan-Ghosh2005** [comment]
@panwar8279 close the issue?
