### ISSUE TITLE
Implement Search Functionality in a website 

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#85]

**Comment by abhaysinghr516** [comment]
I would like to work on this

**Comment by HimanshuNarware** [comment]
@abhaysinghr516  assigned you

**Comment by yash8000** [comment]
assign me this

**Comment by HimanshuNarware** [comment]
@yash8000  this issue already has been resolved ,but you can add onChange effect instead of onClick on searchbar functionnality

**Comment by yash8000** [comment]
hey himanshu i want some help
i am trying to run the project on my laptop but it is not working
i tried taking help of a friend but he cant find how to run it too
[image: WhatsApp Image 2023-12-15 at 12.00.35_49152957.jpg]
[image: WhatsApp Image 2023-12-15 at 12.00.11_98f5aa01.jpg]

**Comment by yash8000** [comment]
i also solved the twitter new loog issue but cant raus epr as i cant make
sure the change happened

**Comment by yash8000** [comment]
it is my first time doing contribution i hope i dont bother you much , but
i need help on this

**Comment by HimanshuNarware** [comment]
you can contact me on linkedin https://www.linkedin.com/in/himanshunarware
