### ISSUE TITLE
[Feature Request]: Responsive ui

### ISSUE THREAD

**Issue by mukilan2815** [HimanshuNarware/Devlabs#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In some screen size , the layout is not proper and the search bar is over those navbar.
i can make this responsive

### Use Case

This will make user to use in multiple screen size devices

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/71129858/4a1059ba-2529-44c8-b2e8-0609e95a656b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @mukilan2815 , i am assigning this issue to you. Kindly complete within 2 days. Good luck!
