### ISSUE TITLE
Improve the UI of the searchbar section

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#86]

**Comment by abhaysinghr516** [comment]
I would like to work on this

**Comment by insane-22** [comment]
Hey @HimanshuNarware , I would like to contribute to your project under hacktoberfest, kindly assign this issue to me,
Thanks for your consideration!

**Comment by HimanshuNarware** [comment]
@insane-22  Assinged you, @abhaysinghr516  you can  work on the search functionality #85
