### ISSUE TITLE
[Bug]: Console Bug Fixes - 1

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Two bugs can be seen in the console from the localhost
![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/3aa240d9-2ce4-4de4-a177-2022bec906f9)

### Expected behavior

There should be less errors and warning in the console.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @panwar8279, These issues need to be resolved. While not currently causing UI errors, they could become major problems as the project progresses.

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , I am assigning this task to you. Kindly complete within 3 days. Also add 30sec demo video with PR Good luck!
