### ISSUE TITLE
[Feature Request]:  Tilt effect on the header image 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to apply the tilt animation on the header image i think this looks awesome .

### Use Case

It makes website more user friendly 

### Add ScreenShots
Here is the example of other website

https://github.com/HimanshuNarware/Devlabs/assets/118350936/dfdf10ee-085a-4b69-a12e-314bb1a1a8e6

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanjay-kv** [comment]
@HimanshuNarware need access to this repo for managing labels. Kindly add me into the same

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!

**Comment by Ayushmaanagarwal1211** [comment]
Ya Sure
