### ISSUE TITLE
Improve the UI of the header section

### ISSUE THREAD

**Issue by coder-pink** [HimanshuNarware/Devlabs#88]
**Is your feature request related to a problem? Please describe.**
Improve the header section of the website. make it responsive and its UI better.

**Comment by coder-pink** [comment]
@HimanshuNarware I would like to work on it. Please assign it to me.

**Comment by HimanshuNarware** [comment]
@coder-pink can explain ,what is your plan

**Comment by Anjali-Kedia** [comment]
@HimanshuNarware I suggest a navbar like the following design, I'd like to work on this issue
<img width="644" alt="Screenshot 2023-10-22 at 11 55 03 AM" src="https://github.com/HimanshuNarware/Devlabs/assets/91176852/5caf8a8d-2da9-44e2-84ef-8f45bae0309c">

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware I suggest a navbar like the following design, I'd like to work on this issue <img alt="Screenshot 2023-10-22 at 11 55 03 AM" width="644" src="https://user-images.githubusercontent.com/91176852/277148587-5caf8a8d-2da9-44e2-84ef-8f45bae0309c.png">

@Anjali-Kedia  ok start working on it
