### ISSUE TITLE
[New Tool]: UI Component Library - Acertinity

### ISSUE THREAD

**Issue by ThisIsSahaj** [HimanshuNarware/Devlabs#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A component library with most trending components to use them in your websites without having to worry about styling and animations.

### Use Case

Can  be used in your website without having to code it completely from scratch and worrying about the responsiveness and styling

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/118066299/d14be99b-000a-4e08-a98d-6f4cefe5add9)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ThisIsSahaj ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!
