### ISSUE TITLE
[New Tool]: Magic UI - A UI component library

### ISSUE THREAD

**Issue by ThisIsSahaj** [HimanshuNarware/Devlabs#886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A component library with most trending components to use them in your websites without having to worry about styling and animations.

### Use Case

Can be used in your website without having to code it completely from scratch and worrying about the responsiveness and styling

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/118066299/af305d57-19bc-455f-ba4f-9d7b2a470a91)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @ThisIsSahaj ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!
