### ISSUE TITLE
[Bug]: Footer Bug

### ISSUE THREAD

**Issue by mukilan2815** [HimanshuNarware/Devlabs#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in footer the content is repeated

### Expected behavior

Repeated content should be deleted

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/71129858/cf9a68aa-c92e-4038-af54-348dd87070ee)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @mukilan2815 , I am assigning this task to you. Kindly complete within 2 days. And also add 30sec demo video with PR. Good luck!
