### ISSUE TITLE
Title and Logo have different name | footer section content are not in centered | fixing the Search bar

### ISSUE THREAD

**Issue by AnkitMourya12** [HimanshuNarware/Devlabs#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. In which title have name  Devlabs but in your website logo have different name such as Devlaps. 
2.  Search bar are not on required place.
<img width="953" alt="devlabslogo1" src="https://github.com/HimanshuNarware/Devlabs/assets/121748364/bf0fe7d6-764d-4361-80dc-94cc417c275b">

3. Footer content are not in centered.
<img width="937" alt="devlabsFoo2" src="https://github.com/HimanshuNarware/Devlabs/assets/121748364/cc6f74eb-1f8f-4a28-a4a1-f4f018bc3f04">

### Expected behavior

after fixing it then it show more interactive to user

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AnkitMourya12** [comment]
can you assign me this issue @HimanshuNarware under gssoc lable

**Comment by panwar8279** [comment]
Hi @AnkitMourya12 , I am assigning this task to you. Kindly complete within 2 days. And also add 30sec demo video with PR. Good luck!
