### ISSUE TITLE
[Feature Request]: Add contents on the AI page.

### ISSUE THREAD

**Issue by meetarora10** [HimanshuNarware/Devlabs#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add the cards on the AI page added with proper styling and animations.

### Use Case

The AI page is empty. I can add contents to that page n the form of cards with animations similar to other pages like ethical hacking page.

### Add ScreenShots

![Screenshot (473)](https://github.com/HimanshuNarware/Devlabs/assets/143121854/bc51514a-4926-41f9-8afc-6efd3d94cd5f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @meetarora10 , I am assigning this task to you. Kindly complete within 2 days. And also add 30sec demo video with PR. Good luck!

**Comment by meetarora10** [comment]
Hi @panwar8279 thanku for assigning me this issue. I will start working on it.
