### ISSUE TITLE
Update Project name devlaps with Devlabs

### ISSUE THREAD

**Issue by AnkitMourya12** [HimanshuNarware/Devlabs#892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Your Project repo name is Devlabs but in the content of readme writes devlaps so just i to update this with Devlabs .
<img width="953" alt="readmeDev4" src="https://github.com/HimanshuNarware/Devlabs/assets/121748364/1316aaf4-149b-4f7c-a2e1-9e80c96f1df9">

### Suggested Change

Top header of ReadMe Devlaps replace with Devlabs . 

### Rationale

because understanding for user 

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AnkitMourya12** [comment]
can you assign me this issue @HimanshuNarware under gssoc lable

**Comment by panwar8279** [comment]
Hi @AnkitMourya12 , I am assigning this task to you. Kindly complete within 2 days. And also add 30sec demo video with PR. Good luck!
