### ISSUE TITLE
[Feature Request]:  Creating a Contact us Form

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am thinking about creating a contact us form because when i click on contact then then it goes to linkedin but may be it is possible that user may not have an account on that so i will create a contact us form so that user can directly share their thought to the respected email with a single click 

### Use Case

It will help users to share their thoughts easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @Ayushmaanagarwal1211, this issue is already raised and assigned to #807
