### ISSUE TITLE
[Feature Request]:  Adding 3d effect cards 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a 3d effect card except the also present cards on the website .

### Use Case

It looks attractive 

### Add ScreenShots

![Screenshot 2024-06-17 154707](https://github.com/HimanshuNarware/Devlabs/assets/118350936/b3a8020c-e25d-4b15-87c8-23eb1ad23776)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!

**Comment by Ayushmaanagarwal1211** [comment]
Ya Sure
