### ISSUE TITLE
[Bug]: Replace Twitter with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [HimanshuNarware/Devlabs#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/HimanshuNarware/Devlabs/assets/140897461/26dd2a38-fd9c-44d7-bc18-0672ad2e3484)
Replace Twitter with X in footer

### Expected behavior

More professional outlook

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AkhilaSunesh ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!
