### ISSUE TITLE
[Feature Request]: Include the type of feedback

### ISSUE THREAD

**Issue by AkhilaSunesh** [HimanshuNarware/Devlabs#899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/HimanshuNarware/Devlabs/assets/140897461/894f050b-c900-48ae-a7ab-dfe125b326c5)
Include the type of feedback
![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/HimanshuNarware/Devlabs/assets/140897461/1cf20d17-3810-49b5-adbf-2a6adf9cc229)

### Use Case

Review forms will be easy to segregate

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AkhilaSunesh ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!
