### ISSUE TITLE
Want to enhance the Design of Default Scroll Bar provided 

### ISSUE THREAD

**Issue by Vishal-1004** [HimanshuNarware/Devlabs#9]
As you know browser provides you with a default scroll bar in the right side of the screen. This Scroll bar doesn't matches with the Design of the website do I intend to give it a matching design i.e color same as that of nav-bar and modifying the its thickness.

##
I really wish to work on this task, so can you assign me this one too. Its a easy task so I can complete it within no time.

**Comment by HimanshuNarware** [comment]
@Vishal-1004  assigned you

**Comment by Vishal-1004** [comment]
Thank you for assigning this task to me,

Here is a screen shot of the changes which I have made in the Default Scroll bar, I hope you would like it:
![Screenshot (1384)](https://github.com/HimanshuNarware/Devlabs/assets/94651481/aea56ba5-c7d0-482a-a278-c84951ea5a1a)
