### ISSUE TITLE
Add dark and light theme on the website

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#90]

**Comment by Mayank77maruti** [comment]
Hey @HimanshuNarware , I would like to contribute to your project under hacktoberfest, kindly assign this issue to me,
Thanks for your consideration!

**Comment by Mayank77maruti** [comment]
@HimanshuNarware , Sir can you please assign this task to me i am really passionate to complete this task.

**Comment by HimanshuNarware** [comment]
@Mayank77maruti  Assigned you

**Comment by brewcoder6113** [comment]
@HimanshuNarware sir please assign me this task under DWOC'23 , Thank You
