### ISSUE TITLE
[Bug]: `Nav bar` hide Logo

### ISSUE THREAD

**Issue by sivaprasath2004** [HimanshuNarware/Devlabs#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- In this project `Desktop` mode click the `Menu` option open the navigation bar, But the navigation bar can be hide the `logo`.

### Expected behavior

- Adjust for the `top` size it can be fixed..

### Expected Behaviour

![Screenshot from 2024-06-18 14-46-52](https://github.com/HimanshuNarware/Devlabs/assets/121082414/e6819f31-2498-4b7a-88dc-fc4b1baaa61b)

### Actual Behaviour

![Screenshot from 2024-06-18 14-53-30](https://github.com/HimanshuNarware/Devlabs/assets/121082414/44129444-8258-4d4d-b59c-312f7a4912e7)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @sivaprasath2004 ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR Good luck!
