### ISSUE TITLE
[Bug]: About buttons content not visible on hover

### ISSUE THREAD

**Issue by root-0101** [HimanshuNarware/Devlabs#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

on hovering over the button in the about section the content in not visible in both dark and light mode.

### Expected behavior

It should change the color of the text within the button on hovering

### Add ScreenShots

https://github.com/HimanshuNarware/Devlabs/assets/142779809/f26f2457-ebe3-4f30-8855-6b52c28c51ab

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @root-0101 , I am assigning this task to you. Kindly complete within 3 days. Also add a 30sec demo video. Good luck!

**Comment by root-0101** [comment]
Hey @panwar8279 Please look into this #486
