### ISSUE TITLE
Improve the UI of the backtotop button

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#91]
**Describe the solution you'd like**
Improve the UI of the backtotop button

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] Working under Slop 3.0 *

**Comment by HimanshuNarware** [comment]
@SxxAq  are you working under hacktomberfest or slop 3.0

**Comment by SxxAq** [comment]
> @SxxAq  are you working under hacktomberfest or slop 3.0

hacktoberfest

**Comment by HimanshuNarware** [comment]
@SxxAq  Assigned you
