### ISSUE TITLE
[Bug]: Updating product.json

### ISSUE THREAD

**Issue by Kiran-pande-30** [HimanshuNarware/Devlabs#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following tools have multiple entries 
1. Canva
2. Trello
3. copy.io
4. webflow
5. frame motion
6. icon finder
7. 1337x
8. Resume Worded
9. Resumer Maker.AI

(2) As we move forward into the product, we have to keep the categories as fixed there are almost 22+ different categories, and these numbers may keep growing.

(3) We need to update our contribution guidelines. Contributors should select among these categories only.

### Expected behaviour

There should only be a single entry for every tool in product.json

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/105718863/a71974b0-1129-4266-8336-f58b0b116261)
and similar entries

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Kiran-pande-30 , ,  I am assigning this issue to you. Kindly complete within 2 days. Also add 30sec demo video with PR. Good luck!
