### ISSUE TITLE
Improve the UI of  the about section

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#92]
**Describe the solution you'd like**
Improve the UI of the About section

** Add screenshot 

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] Working under Slop 3.0 *

**Comment by ankittyagi140** [comment]
Hi @HimanshuNarware,
I have figured out some quick changes which will increase consistency on you about page 
![image](https://github.com/HimanshuNarware/Devlabs/assets/72274173/31ebe12f-b3a5-4603-80dd-bcbb6278e998)

**Comment by ankittyagi140** [comment]
Hi @HimanshuNarware 
changes are done, but when I try to push my changes it gives me permissions denied option can you give me permission to push my code changes and can you please add this change in hoctober fest?

**Comment by HimanshuNarware** [comment]
@ankittyagi140 I think you  have forked the repo from my username, fork repo from your username,
