### ISSUE TITLE
[Feature Request]: Programmiz

### ISSUE THREAD

**Issue by maradadivyasree020** [HimanshuNarware/Devlabs#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Programiz is an online platform designed to help users learn programming languages such as Python, Java, C, and C++ through interactive tutorials, examples, and coding exercises. It provides a structured learning path from beginner to advanced levels, covering fundamental concepts and practical applications. Programiz also offers code playgrounds for practicing code snippets and exploring programming challenges in a supportive online community environment.

### Use Case

Programiz is an online platform designed to help users learn programming languages such as Python, Java, C, and C++ through interactive tutorials, examples, and coding exercises. It provides a structured learning path from beginner to advanced levels, covering fundamental concepts and practical applications. Programiz also offers code playgrounds for practicing code snippets and exploring programming challenges in a supportive online community environment.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Kiran-pande-30** [comment]
Hello @maradadivyasree020, As you are adding tools to our project. You should choose "New Tool" Template instead of "Feature Request" Template while raising the issues

**Comment by maradadivyasree020** [comment]
ok
