### ISSUE TITLE
Add responsive layout on the About section

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#93]

**Comment by vihar-s1** [comment]
I would like to work on this issue under SLoP3.0 and hacktoberfest. Can you please assign this to me?

**Comment by HimanshuNarware** [comment]
@vihar-s1  assigned you

**Comment by vihar-s1** [comment]
Do you need me to make some further improvements for the page responsiveness as this issue is still open?
