### ISSUE TITLE
[New Tool]: Vagrant

### ISSUE THREAD

**Issue by maradadivyasree020** [HimanshuNarware/Devlabs#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Vagrant is an open-source tool for building and managing virtualized development environments. It simplifies the setup process by providing a consistent workflow across different platforms, allowing developers to quickly create and configure virtual machines with specific software configurations.

### Use Case

Vagrant is an open-source tool for building and managing virtualized development environments. It simplifies the setup process by providing a consistent workflow across different platforms, allowing developers to quickly create and configure virtual machines with specific software configurations.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @maradadivyasree020 , ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR. Good luck!
