### ISSUE TITLE
[New Tool]: Github Copilot

### ISSUE THREAD

**Issue by maradadivyasree020** [HimanshuNarware/Devlabs#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

GitHub Copilot is an AI-powered code completion tool that helps developers write code faster and with fewer errors by suggesting entire lines or blocks of code based on the context of the current file. It integrates directly into the editor and supports multiple programming languages.

### Use Case

GitHub Copilot is an AI-powered code completion tool that helps developers write code faster and with fewer errors by suggesting entire lines or blocks of code based on the context of the current file. It integrates directly into the editor and supports multiple programming languages.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @maradadivyasree020 , ,  I am assigning this task to you. Kindly complete within 3 days. Also add 30sec demo video with PR. Good luck!
