### ISSUE TITLE
[Feature Request]: Creating a seperate page for contact us 

### ISSUE THREAD

**Issue by mukilan2815** [HimanshuNarware/Devlabs#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Instead of navigating to linkedin we can make it in website even.

### Use Case

Users can stay in our website even

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @mukilan2815 , ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR. Good luck!
