### ISSUE TITLE
[New Tool]: Kubernetes

### ISSUE THREAD

**Issue by maradadivyasree020** [HimanshuNarware/Devlabs#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications. It provides a robust environment for managing complex, multi-container applications.

### Use Case

Kubernetes is an open-source container orchestration platform that automates the deployment, scaling, and management of containerized applications. It provides a robust environment for managing complex, multi-container applications.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @maradadivyasree020 ,  I am assigning this task to you. Kindly complete within 4 days. Also add 30sec demo video with PR. Good luck!
