### ISSUE TITLE
[New Tool]: Jenkins

### ISSUE THREAD

**Issue by maradadivyasree020** [HimanshuNarware/Devlabs#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

In this , you must automate the software development process by mastering Jenkins. This helps users to master Jenkins concepts and commands.

### Use Case

In this , you must automate the software development process by mastering Jenkins. This helps users to master Jenkins concepts and commands.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @maradadivyasree020 ,  I am assigning this task to you. Kindly complete within 2 days. Also add 30sec demo video with PR. Good luck!
