### ISSUE TITLE
[Bug]: Unwanted text

### ISSUE THREAD

**Issue by AkhilaSunesh** [HimanshuNarware/Devlabs#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Location: FAQ
![image](https://github.com/HimanshuNarware/Devlabs/assets/140897461/0645e6da-7641-4554-9340-bceee80ab40a)
Unwanted text related to this repository. Marked in the image

### Expected behavior

Improve the website content

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @AkhilaSunesh , I am assigning this issue to you. Kindly complete within 2 days. Also add 30sec demo video with PR. Good luck!
