### ISSUE TITLE
New Tool & Feature

### ISSUE THREAD

**Issue by Khushalsarode** [HimanshuNarware/Devlabs#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

- image background remover
- video background remover

Feature suggestion:
- search bar to be shifted above the tools card list where its show best use!

### Use Case

- just drag and drop image/video it will provide an object removed from item with download option!
- the search bar in navbar to be shifted to the home page above the card list of tools for better UX

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Khushalsarode , I am assigning you this task, Kindly complete within 2 days and also add 30sec demo video.

**Comment by Khushalsarode** [comment]
> Hi @Khushalsarode , I am assigning you this task, Kindly complete within 2 days and also add 30sec demo video.

Can you review this?
