### ISSUE TITLE
Feature 🌟: "Scroll to Top" Button and "Chat-Bot" are Overlapping 

### ISSUE THREAD

**Issue by Tejashri-Taral** [HimanshuNarware/Devlabs#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I noticed that the "Scroll to Top" button and the Webchat bot are overlapping on the website.
This overlap affects the usability and accessibility of both features, making it difficult for users to effectively interact with the WebChat bot and the scroll top button.

### Expected behavior

The "Scroll to Top" button and the WebChat bot should not overlap. Both elements should be easily accessible without interfering with each other.

### Add ScreenShots

******Screenshots******

So, Before Opening the Chatbot:

![image](https://github.com/HimanshuNarware/Devlabs/assets/160386036/5a028785-c1e0-4de8-be9b-ef880d5b0413)

After opening Chatbot:

![image](https://github.com/HimanshuNarware/Devlabs/assets/160386036/4d4c1072-0b90-447d-a1f1-62e14f45bddd)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Tejashri-Taral , I am assigning this task yo you. Kindly complete within 2 days and also will add 30sec demo video. Good luck!
