### ISSUE TITLE
[New Tool]: Aceternity Ui

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Copy paste the most trending components and use them in your websites without having to worry about styling and animations.

### Use Case

User can have interesting and trendy design in there website

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/792613c5-7ee6-4d5b-aed7-4b54ddd89a31)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
hi @Utsavladia, i am assigning this task to you. Kindly complete within 2 days and Also add 30sec demo video with pr. Good Luck!
