### ISSUE TITLE
[New Tool]:  Easeus Vocal remover AI

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Vocal Remover Online Free
Separate voice and music from any song free with powerful AI technolog

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/fb326f63-d9d6-4fb8-a412-3c16e1c58392)

### Use Case

User can remove vocal from the music

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
