### ISSUE TITLE
[New Tool]:  Interview warmup by Google

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A iinterview preperation website by Google

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/73192025-ec0d-4e38-b628-23932351d25a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
hi @Utsavladia ,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
