### ISSUE TITLE
[New Tool]:  Maths GPT

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A AI tool that solves maths problem using the using the image of question or mixed conttent

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/4d41e442-99a0-488b-b471-03b01b99d599)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within a week and also add a 30-second demo video with PR. Good Luck!
