### ISSUE TITLE
[New Tool]: Oh My Git

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

An open source game about learning git

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/83b4cc23-6c0b-4d45-b087-98e007c6294a)

### Use Case

It gives and exciting way to learn about git

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
