### ISSUE TITLE
[New Tool]: Bright Data Web Scrapper

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

A tool to use as web scrapper and implement in the websites.

### Use Case

User can implement in website and use webscrapper using its services

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
hi @Utsavladia ,  i am assigning this task to you. Kindly complete within 2 days and also add a 30-second demo video with PR. Good Luck!
