### ISSUE TITLE
[New Tool]:  National Digital library of India

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

National digital library of India allow user to have the variety of sections of library by government of india.

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/8d3a6e95-5435-41b0-b95d-4bccd75e1067)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within a week and also add a 30-second demo video with PR. Good Luck!
