### ISSUE TITLE
[New Tool]:  InstaHire

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

hiring platform 

### Use Case

Hiring platform only few people know about

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 3 days and also add a 30-second demo video with PR. Good Luck!
