### ISSUE TITLE
[New Tool]: Bootstrap

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins.

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/6a431cce-5bd3-4cb6-9e2c-9e3cfa39fe12)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 4 days and also add a 30-second demo video with PR. Good Luck!
