### ISSUE TITLE
Console errors in the deployed version

### ISSUE THREAD

**Issue by vihar-s1** [HimanshuNarware/Devlabs#98]
**Bug Description**
A bunch of unresolved errors and log statements in the console in development server and in the deployed version as well.

**Expected behavior**
A clear console helps for better debugging, user error tracking, and provide improved security by protecting sensitive data.

**Screenshots**
![image](https://github.com/HimanshuNarware/Devlabs/assets/96971096/f921d771-e439-449d-bf43-0df2b560b1b8)

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Hacktomberfest/Hacksquad*
- [x] Working under Slop 3.0 *

**Comment by vihar-s1** [comment]
I want to work on this issue. Can you please assign this to me

**Comment by vihar-s1** [comment]
I am officially assigned to your project under SLoP3.0 but I have participated in Hacktoberfest as well.

**Comment by vihar-s1** [comment]
I can go stop asking for hacktoberfest as well if it is a problem going for both (SLoP and hacktoberfest) simultaneously.

**Comment by HimanshuNarware** [comment]
@vihar-s1  no, you can work on both simultaneously but

> I am officially assigned to your project under SLoP3.0 but I have participated in Hacktoberf

> I can go stop asking for hacktoberfest if it is a problem going for both (SLoP and hacktoberfest) simultaneously.

@vihar-s1  you can work on both simultaneously if you selected in slop and working under hacktomberfest,

**Comment by vihar-s1** [comment]
I have found about 18-20 logo links for the tools where the responses are either Gone (410), Forbidden (403), or Not Found (404). Should I update those links as well?

Also, it is just a request but could make it SLoP-25 instead of SLoP-5 since these errors required change of code in 3+ files along with updating the logos in public folder as well due to size mismatch, and would require fix those 20 links as well if say yes to above issue.
