### ISSUE TITLE
[New Tool]:  I love Img tool to compress images

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Compress JPG with the best quality and compression.
Reduce the filesize of many JPG images at once online

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/d27de0ed-6018-464d-af81-ee6cc137a14b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 4 days and also add a 30-second demo video with PR. Good Luck!
