### ISSUE TITLE
[New Tool]:  Relight a free tool to edit images using AI

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Relight your photos & drawings in seconds
Free AI tool with many features

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/8b3a9c78-7a53-4f75-be80-7925694351db)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 4 days and also add a 30-second demo video with PR. Good Luck!
