### ISSUE TITLE
[New Tool]:  OverApi Cheat sheet of almost all techs

### ISSUE THREAD

**Issue by Utsavladia** [HimanshuNarware/Devlabs#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New Tool Description

Website having cheet sheet of all techs..

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/20f35e6e-8d34-4e77-9b60-25fd82670342)

### Use Case

![image](https://github.com/HimanshuNarware/Devlabs/assets/124615886/8c9b9d2d-d5b5-4e90-af1e-8627ecc7cec0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Utsavladia,  i am assigning this task to you. Kindly complete within 3 day and also add a 30-second demo video with PR. Good Luck!
