### ISSUE TITLE
[Feature Request]: Enhancement of Coding Platforms Page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HimanshuNarware/Devlabs#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The dark mode is not properly applied on the page and the content is overlapping with the navbar . I will fix it and change all the cards with the latest dark theme .

### Use Case

This will make constant theme for all pages .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by panwar8279** [comment]
Hi @Ayushmaanagarwal1211 ,  i am assigning this task to you. Kindly complete within 3 days and also add a 30-second demo video with PR. Good Luck!
