### ISSUE TITLE
[Feature Request]: Develop Remote jobs page

### ISSUE THREAD

**Issue by the-code-artist** [HimanshuNarware/Devlabs#988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Develop Remote jobs page

### Use Case

as the feature is already mentioned in the footer section but it is not developed
thus i want to develop such that users can learn about various Remote jobs

### Benefits

will create better user experience and serves the goal of the project.

### Add ScreenShots

![image](https://github.com/HimanshuNarware/Devlabs/assets/115625321/75c81014-7c43-4c08-9c4b-8d4760c8b49c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by the-code-artist** [comment]
hey @panwar8279 
I am interested in contributing this feature to the project.
please do assign me this issue under GSSOC'24!!

**Comment by panwar8279** [comment]
Hi @the-code-artist,  i am assigning this task to you. Kindly complete within 3 days and also add a 30-second demo video with PR. Good Luck!
