### ISSUE TITLE
Improve responsiveness of the homepage

### ISSUE THREAD

**Issue by davidkrupa** [HimanshuNarware/Devlabs#99]
Homepage doesn't have proper responsiveness between 425px - 650px

<img width="425" alt="issue" src="https://github.com/HimanshuNarware/Devlabs/assets/126403373/9187878c-43e7-4c07-9d16-eb182636d2b1">

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Hacktomberfest*

**Comment by davidkrupa** [comment]
@HimanshuNarware please assign this to me

**Comment by HimanshuNarware** [comment]
@davidkrupa  dont raise PR before getting assigned
